"""Assemble side/farm.py = port2/h_over.py (tape + sell overlay) + side/_tail.py.

Kaggle `exec`s main.py with __file__ undefined, so the shipped agent has to be
one file with no path-based loading and no local imports -- same recipe as
port/build_main.py.  Run with:  ./.venv/bin/python side/build.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
BASE = os.path.join(REPO, "port2", "h_over.py")
TAIL = os.path.join(HERE, "_tail.py")
OUT = os.path.join(HERE, "farm.py")

HEAD = '''"""port2/h_over.py (tape replay + sell overlay) + a side farm on the SE quadrant.

    MEASURED RESULT: THE SIDE FARM LOSES.  DO NOT SUBMIT THIS FILE.

    vs port2/h_over.py, both seat orders, two disjoint seed sets:
        seeds   1..12   margin -4446   0.083 wr   (2/24)
        seeds 101..112  margin -4244   0.000 wr   (0/24)
    evalpool -n 4 -w 8: 0.889 (64/72) against h_over's 0.972 (70/72).

    The decomposition is clean, because two h_over seats play byte-identically
    and therefore always bank the same amount:

        side_hands=0 (buy the SE quadrant, farm nothing)  ->  -3973 .. -4000
        the farm on top of that                           ->   -446 .. +271

    So the quadrant's 25 tiles, worked by the extra hand, earn back that hand's
    wages and nothing more, and the $4000 of land is dead loss.  The reason is
    not the planner: by day 12 the town absorbs roughly 120 units a day across
    all nine products and the two 75-tile farms already produce more than that,
    so marginal output sells at $15-30 an action while the 13th hand costs $233
    a day.  Set side_on=0 to get port2/h_over.py back bit-for-bit.

Generated by side/build.py -- do not edit by hand; edit side/_tail.py instead.

Original docstring:
'''


def main():
    base = open(BASE).read()
    tail = open(TAIL).read()

    assert base.startswith('"""'), "h_over.py must start with a docstring"
    base = HEAD + base[3:]

    old = "def agent(observation, configuration=None):"
    assert base.count(old) == 1, base.count(old)
    base = base.replace(old, "def _base_agent(observation, configuration=None):")

    out = base + tail
    with open(OUT, "w") as fh:
        fh.write(out)
    print("wrote %s: %d bytes, %d lines" % (OUT, len(out), out.count("\n") + 1))


if __name__ == "__main__":
    main()
