"""Generate port2 variants from port/main.py by exact-source patching.

Emits three single-file, __file__-free candidates:

  h_guard.py  port + the six-day budget guard's settings and the route rule as P
  h_over.py   port + h1's selling overlay (our market model)
  h_both.py   both of the above, one merged P

Run:  ./.venv/bin/python port2/gen.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(ROOT, "port2")
SRC = open(os.path.join(ROOT, "port/main.py")).read()
MARK = "# <<PARAMS>>"


def sub(text, old, new, n=1):
    if text.count(old) != n:
        raise SystemExit("patch anchor %r found %d times (want %d)"
                         % (old[:70], text.count(old), n))
    return text.replace(old, new)


def retitle(text, what):
    return text.replace(
        '"""Pure-Python port of ``the-35-0-tape-a-causal-shop-router``.',
        '"""port/main.py + %s.\n\nGenerated by port2/gen.py -- do not edit by hand.\n'
        '\nOriginal docstring:\nPure-Python port of ``the-35-0-tape-a-causal-shop-router``.' % what, 1)


# ==========================================================================
# the guard / route patch
# ==========================================================================
GUARD_P = '''    # --- six_day_budget_guard.hpp: SixDayBudgetGuardSettings ---------------
    interval=72,        # guard cadence in turns (policy.cpp uses kSegmentTurns=72)
    horizon=72,         # how many turns of the tape the budget is computed over
    min_price=2,        # minimum_unit_price
    sales_first=1,      # sales_first
    protect=1,          # protect_static_consumption
    budget_mult=1.0,    # scale the computed purchase budget
    cash_floor=0.0,     # flat cash cushion demanded on top of the budget
    # --- policy.cpp route switch -------------------------------------------
    route=-1,           # -1 = the tape's own rule, 0/1 = force that route
    route_step=216,     # kDecisionStep
    route_geese=1,      # rival goose tiles must exceed this
    route_shops=1,      # 1 = require the ICE_CREAM/FM/FM prefix, 0 = ignore shops
'''


def patch_guard(t):
    t = sub(t, '''# six_day_budget_guard.hpp: SixDayBudgetGuardSettings, as set by policy.cpp
GUARD_INTERVAL_TURNS = K_SEGMENT_TURNS
GUARD_MIN_UNIT_PRICE = 2
GUARD_SALES_FIRST = True
GUARD_PROTECT_STATIC_CONSUMPTION = True
''', MARK + "\n")
    t = sub(t, '''    if (state.step < 0 or GUARD_INTERVAL_TURNS <= 0 or
            state.step % GUARD_INTERVAL_TURNS != 0):
        return action''', '''    _interval = int(P["interval"])
    if (state.step < 0 or _interval <= 0 or
            state.step % _interval != 0):
        return action''')
    t = sub(t, '''    shortfall = purchase_budget - available_cash''',
            '''    shortfall = (purchase_budget * float(P["budget_mult"])
                 + float(P["cash_floor"]) - available_cash)''')
    t = sub(t, '''        if price < GUARD_MIN_UNIT_PRICE:''',
            '''        if price < int(P["min_price"]):''')
    t = sub(t, '''        protected_total = starting_items[item] if GUARD_PROTECT_STATIC_CONSUMPTION else 0''',
            '''        protected_total = starting_items[item] if P["protect"] else 0''')
    t = sub(t, '''    if added > 0 and GUARD_SALES_FIRST:''', '''    if added > 0 and P["sales_first"]:''')
    t = sub(t, '''        if state.step == K_DECISION_STEP:
            self.selected_route = 1 if _choose_observed_tail(state) else 0
''', '''        if state.step == int(P["route_step"]):
            forced = int(P["route"])
            if forced in (0, 1):
                self.selected_route = forced
            else:
                self.selected_route = 1 if _choose_observed_tail(state) else 0
''')
    t = sub(t, '''        if state.step % K_SEGMENT_TURNS != 0:
            return action
        end = min(K_TURNS, state.step + K_SEGMENT_TURNS)''',
            '''        interval = int(P["interval"])
        if interval <= 0 or state.step % interval != 0:
            return action
        end = min(K_TURNS, state.step + int(P["horizon"]))''')
    t = sub(t, '''def _choose_observed_tail(state):
    if (state.n_shops < 3 or
            state.shops[0] != SHOP_ICE_CREAM_SHOP or
            state.shops[1] != SHOP_FARMERS_MARKET or
            state.shops[2] != SHOP_FARMERS_MARKET):
        return False
    return float(state.rival_animal_tiles(GOOSE)) > 1''',
            '''def _choose_observed_tail(state):
    if P["route_shops"]:
        if (state.n_shops < 3 or
                state.shops[0] != SHOP_ICE_CREAM_SHOP or
                state.shops[1] != SHOP_FARMERS_MARKET or
                state.shops[2] != SHOP_FARMERS_MARKET):
            return False
    return float(state.rival_animal_tiles(GOOSE)) > float(P["route_geese"])''')
    return t


# ==========================================================================
# the overlay patch
# ==========================================================================
OVER_P = '''    # --- h1 selling overlay -------------------------------------------------
    mode="lookahead",       # 'off' | 'greedy' | 'lookahead' | 'model'
    items=["STRAWBERRY", "MILK", "WOOL", "FERTILIZER", "MELON", "CARROT", "TOMATO", "EGG"],
    lookahead=40,           # turns of the tape's own schedule to pull forward
    wheat=1,                # 1 -> also manage WHEAT (animal feed: keep a reserve)
    wheat_days=1.0,
    wheat_start=300,
    fert_keep=0,
    start_step=0,
    price_gate=0.0,
    hold_gain=0.0,
    sell_bias_glut=2.2,
    sell_bias_tight=2.0,
    hinge_meter=0.5,
    shed_target=88,
    unlock_trust=1.0,
    opp_weight=0.85,
    opp_mirror=0.7,
    mine_w=0.7,
    horizon_days=0.6,
    tranche=99,
    drain_gate=4,
    window_cap=24,
    win4=[0, 4, 3, 2],
    hold_horizon=0.2,
    opp_press=0.0,
    endgame_day=30,
    guard_protect=1,        # 1 -> honour the guard's static consumption reserve
'''

OVERLAY = r'''

# ==========================================================================
# h1's selling overlay: our market model, re-pointed at this tape's shed.
#
# It only ever ADDS units to a SELL order (or appends one when a free order
# slot exists), and books what it pulled forward as debt repaid out of the
# tape's own later SELL orders.  The tape's order ORDER is never changed and
# nothing is ever pushed off the 10-slot cliff.
# ==========================================================================
_OV_CROPS = {
    "WHEAT":      {"myd": 4,  "interval": 0, "maxy": 6, "ongoing": False},
    "CARROT":     {"myd": 3,  "interval": 0, "maxy": 4, "ongoing": False},
    "TOMATO":     {"first": 8,  "myd": 8,  "interval": 1, "maxy": 4, "ongoing": True},
    "STRAWBERRY": {"first": 10, "myd": 10, "interval": 2, "maxy": 4, "ongoing": True},
    "MELON":      {"myd": 12, "interval": 0, "maxy": 6, "ongoing": False},
}
_OV_ANIMALS = {
    "GOOSE": {"interval": 1, "held": 4, "product": "EGG"},
    "COW":   {"interval": 2, "held": 6, "product": "MILK"},
    "SHEEP": {"interval": 3, "held": 6, "product": "WOOL"},
}
_OV_PRODUCTS = list(_PRODUCTS)
_OV_MARKET = {
    "WHEAT":      {"base":  25, "T": 400, "bf": "sqrt",   "bt": 0.80, "af": "log",    "at": 0.20},
    "CARROT":     {"base":  35, "T": 450, "bf": "hinge",  "bt": 1.00, "af": "sqrt",   "at": 0.70},
    "TOMATO":     {"base":  60, "T": 200, "bf": "hinge",  "bt": 0.40, "af": "sqrt",   "at": 0.60},
    "STRAWBERRY": {"base": 120, "T": 100, "bf": "sqrt",   "bt": 0.70, "af": "linear", "at": 1.60},
    "MELON":      {"base": 250, "T": 300, "bf": "log",    "bt": 0.20, "af": "sq",     "at": 3.60},
    "EGG":        {"base":  50, "T": 332, "bf": "hinge",  "bt": 0.40, "af": "log",    "at": 0.20},
    "MILK":       {"base": 160, "T": 122, "bf": "sqrt",   "bt": 0.60, "af": "linear", "at": 1.60},
    "WOOL":       {"base": 200, "T": 105, "bf": "log",    "bt": 0.20, "af": "sq",     "at": 3.20},
    "FERTILIZER": {"base": 100, "T": 200, "bf": "linear", "bt": 0.40, "af": "linear", "at": 0.40},
}
_OV_SHOPS = {
    "BAKERY":         ["EGG", "WHEAT"],
    "PIZZA_SHOP":     ["MILK", "TOMATO", "WHEAT"],
    "BRUNCH_SPOT":    ["EGG", "WHEAT", "STRAWBERRY"],
    "YARN_STORE":     ["WOOL"],
    "ICE_CREAM_SHOP": ["STRAWBERRY", "MILK", "WHEAT"],
    "PET_CAFE":       ["CARROT"],
    "SMOOTHIE_SHOP":  ["STRAWBERRY", "MILK"],
    "FARMERS_MARKET": ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY"],
}
_OV_PULL = {p: 0.0 for p in _OV_PRODUCTS}
for _shop, _prods in _OV_SHOPS.items():
    _m = 2.0 if len(_prods) == 1 else 1.0
    for _p in _prods:
        _OV_PULL[_p] += _m / len(_OV_SHOPS)
_OV_SHOP_INTERVAL = 3
_OV_MAX_SHOPS = 8
_OV_TICKS_PER_DAY = 6
_OV_I0 = 10000
_OV_HINGE_GAIN = 8.0
_OV_LAST_DAY = 29


def _ov_shape(func, x, T):
    if x < 0.0:
        x = 0.0
    if func == "linear":
        return x
    if func == "sq":
        return x * x
    if func == "sqrt":
        return math.sqrt(x)
    if func == "log":
        return math.log(1.0 + x)
    if func == "hinge":
        if not T or T <= 0:
            return x
        u = x / T
        d = u - 1.0
        return u + _OV_HINGE_GAIN * (d * d if d > 0 else 0.0)
    return x


def _ov_price(item, inv):
    p = _OV_MARKET[item]
    base, T = p["base"], p["T"]
    if inv < _OV_I0:
        amp = p["bt"] * base / _ov_shape(p["bf"], T, T)
        price = base + amp * _ov_shape(p["bf"], _OV_I0 - inv, T)
    else:
        amp = p["at"] * base / _ov_shape(p["af"], T, T)
        price = base - amp * _ov_shape(p["af"], inv - _OV_I0, T)
    v = int(round(price))
    return 1 if v < 1 else v


# _OV_CUM[route][item][t] = units of `item` this tape sells over steps 0..t-1.
_OV_CUM = []
for _tape in _TAPES:
    _sched = {p: [0] * K_TURNS for p in _OV_PRODUCTS}
    for _s in range(K_TURNS):
        _nu, _units, _no, _orders = _tape[_s]
        for _i in range(_no):
            _op, _it, _n = _orders[_i]
            if _op == M_SELL and 0 <= _it < N_PRODUCTS:
                _sched[_ITEMS[_it]][_s] += max(0, _n)
    _cum = {}
    for _p in _OV_PRODUCTS:
        _run = 0
        _c = [0] * (K_TURNS + 1)
        for _s in range(K_TURNS):
            _c[_s] = _run
            _run += _sched[_p][_s]
        _c[K_TURNS] = _run
        _cum[_p] = _c
    _OV_CUM.append(_cum)


def _sched_window(route, item, lo, hi):
    """Units of `item` the tape sells over steps lo..hi inclusive."""
    lo = max(0, lo)
    hi = min(K_TURNS - 1, hi)
    if hi < lo:
        return 0
    c = _OV_CUM[route][item]
    return c[hi + 1] - c[lo]


def _pickup_reserve(action, item):
    reserve = 0
    for order in [action.get("farmer", ["PASS"]), *list(action.get("hands") or [])]:
        if (isinstance(order, (list, tuple)) and len(order) >= 2
                and order[0] == "PICKUP" and order[1] == item):
            try:
                reserve += max(0, int(order[2])) if len(order) >= 3 else 1
            except (TypeError, ValueError):
                reserve += 1
    return reserve


def _town_demand_now(shops, item, step):
    demand = 1 if item != "FERTILIZER" and step % 24 == 0 else 0
    if step % 4 != 0:
        return demand
    for shop in shops:
        products = _OV_SHOPS.get(shop, ())
        if item in products:
            demand += 2 if len(products) == 1 else 1
    return demand


class _Overlay(object):
    def __init__(self):
        self.reset(0)

    def reset(self, step):
        self.last_step = step
        self.debt = {}
        self.sold_today = {}
        self.day = -1
        self.opp_pipe = {p: 0.0 for p in _OV_PRODUCTS}

    # ------------------------------------------------------------- observation
    def observe(self, obs, step):
        me = int(_read(obs, "player", 0) or 0)
        farms = list(_read(obs, "farms", []) or [])
        self.me = me
        self.farm = farms[me] if me < len(farms) else {}
        priv = _read(obs, "private", {}) or {}
        self.shed = dict(_read(priv, "shed", {}) or {})
        self.invs = list(_read(priv, "inventories", []) or [])
        market = _read(obs, "market", {}) or {}
        self.inv = dict(_read(market, "inventory", {}) or {})
        self.price = dict(_read(market, "prices", {}) or {})
        town = _read(obs, "town", {}) or {}
        self.shops = list(_read(town, "unlocked_shops", []) or [])
        self.day = step // 24
        self.hour = step % 24
        self.day_left = _OV_LAST_DAY - self.day
        self.drain = self.drain_rates(self.shops)
        self.n_animals = 0
        self.pipeline = {p: 0.0 for p in _OV_PRODUCTS}
        for row in (_read(self.farm, "tiles", []) or []):
            for t in row or []:
                if not isinstance(t, dict):
                    continue
                if t.get("kind") == "PLANT":
                    self.pipeline[t["crop"]] += self.plant_future(t)
                elif "animal" in t:
                    self.n_animals += 1
                    a = _OV_ANIMALS[t["animal"]]
                    rem = max(0, self.day_left - 1)
                    per = min(1 + a["interval"], a["held"]) / a["interval"]
                    self.pipeline[a["product"]] += t["yield_units"] + rem * per
                    self.pipeline["FERTILIZER"] += rem
        for p in _OV_PRODUCTS:
            self.pipeline[p] += self.shed.get(p, 0) + self.carried(p)
        if step % 6 == 0 or self.opp_pipe is None:
            self.opp_pipe = self.scan_opponent(farms[1 - me] if len(farms) > 1 else {})

    def carried(self, p):
        return sum(iv.get(p, 0) for iv in self.invs)

    def plant_future(self, t):
        cd = _OV_CROPS[t["crop"]]
        age = self.day - t["planted_day"]
        if not cd["ongoing"]:
            room = cd["maxy"] - t["yield_units"]
            last = min(cd["myd"], age + self.day_left)
            days = max(0, last - max(age, (cd["myd"] + 1) // 2) + 1)
            return t["yield_units"] + min(room, days)
        k = age - cd["first"]
        done = (k // cd["interval"] + 1) if k >= 0 else 0
        left = max(0, cd["maxy"] - done)
        left = min(left, self.day_left // max(1, cd["interval"]) + 1)
        return t["yield_units"] + left * 1.5

    def scan_opponent(self, farm):
        pipe = {p: 0.0 for p in _OV_PRODUCTS}
        for row in (_read(farm, "tiles", []) or []):
            for t in row or []:
                if not isinstance(t, dict):
                    continue
                if t.get("kind") == "PLANT":
                    pipe[t["crop"]] += self.plant_future(t)
                elif "animal" in t:
                    a = _OV_ANIMALS[t["animal"]]
                    rem = max(0, self.day_left - 1)
                    per = min(1 + a["interval"], a["held"]) / a["interval"]
                    pipe[a["product"]] += t["yield_units"] + rem * per
                    pipe["FERTILIZER"] += rem
        return pipe

    # ------------------------------------------------------------ market model
    def drain_rates(self, shops):
        d = {p: 0.0 for p in _OV_PRODUCTS}
        for shop in shops:
            prods = _OV_SHOPS.get(shop)
            if not prods:
                continue
            mult = 2.0 if len(prods) == 1 else 1.0
            for p in prods:
                d[p] += mult * 6.0
        for p in _OV_PRODUCTS:
            if p != "FERTILIZER":
                d[p] += 1.0
        return d

    def mean_drain(self, item, days_ahead):
        n = int(days_ahead)
        if n <= 0:
            return self.drain[item]
        base = 1.0 if item != "FERTILIZER" else 0.0
        known = self.drain[item] - base
        n_now = len(self.shops)
        tot = 0.0
        for t in range(self.day, self.day + n + 1):
            future = max(0, min(_OV_MAX_SHOPS, (t + 1) // _OV_SHOP_INTERVAL) - n_now)
            tot += known + base + future * _OV_TICKS_PER_DAY * _OV_PULL[item] * P["unlock_trust"]
        return tot / (n + 1)

    def forecast(self, item, days_ahead, extra=0.0):
        d = self.mean_drain(item, days_ahead)
        return _ov_price(item, self.inv[item] - d * days_ahead + extra)

    def supply(self, item, horizon=None):
        if horizon is None or self.day_left <= 0:
            scale = 1.0
        else:
            scale = min(1.0, float(horizon) / max(1.0, self.day_left))
        mine = self.pipeline[item] * scale * P["mine_w"]
        theirs = max(self.opp_pipe[item] * scale, mine * P["opp_mirror"])
        return mine + theirs * P["opp_weight"]

    # ------------------------------------------------------------------ policy
    def model_q(self, item, avail):
        horizon = max(1, self.day_left + 1)
        total = max(avail, self.pipeline[item])
        q = total / horizon
        q *= P["sell_bias_glut"] if total > self.drain[item] * horizon else P["sell_bias_tight"]
        if _OV_MARKET[item]["bf"] == "hinge" and self.inv[item] < _OV_I0:
            q *= P["hinge_meter"]
        q = int(math.ceil(q)) - self.sold_today.get(item, 0)
        shed_total = sum(max(0, v) for k, v in self.shed.items() if k in _OV_PRODUCTS)
        carried_total = sum(sum(v for k, v in iv.items() if k in _OV_PRODUCTS) for iv in self.invs)
        overflow = shed_total + carried_total - P["shed_target"]
        if overflow > 0:
            q = max(q, min(avail, int(math.ceil(overflow * avail / max(1, shed_total)))))
        return max(0, q)

    def window(self, item, step):
        g = int(P["drain_gate"])
        k = int(P["lookahead"])
        if g == 0:
            return k
        if g == 1:
            return 0 if _town_demand_now(self.shops, item, step) > 0 else k
        if g == 4:
            return min(k, int(P["win4"][step % 4]))
        if g == 2:
            free = (4 - (step % 4)) % 4
            return min(k, free)
        shop = 0.0
        for s in self.shops:
            prods = _OV_SHOPS.get(s)
            if prods and item in prods:
                shop += 2.0 if len(prods) == 1 else 1.0
        cap = int(P["window_cap"])
        for d in range(0, cap + 1):
            s = step + d
            pull = shop if s % 4 == 0 else 0.0
            if item != "FERTILIZER" and s % 24 == 0:
                pull += 1.0
            if pull > 0:
                return min(k, d)
        return min(k, cap)

    def hold(self, item):
        spot = float(self.price.get(item, 0) or 0)
        if spot <= 0:
            return False
        base = _OV_MARKET[item]["base"]
        if P["price_gate"] > 0 and spot < base * P["price_gate"]:
            return True
        if P["hold_gain"] > 0:
            h = float(P["hold_horizon"])
            nxt = self.forecast(item, h, extra=self.supply(item, h) * P["opp_press"])
            if (nxt - spot) / spot > P["hold_gain"]:
                return True
        return False

    def __call__(self, action, obs, step, route, protect):
        self.last_step = step
        if P["mode"] == "off" or step < int(P["start_step"]):
            return action
        self.observe(obs, step)
        if self.hour == 0:
            self.sold_today = {}

        market = [list(o) for o in (action.get("market") or [])]

        # 1. Repay what we pulled forward out of the tape's own later orders.
        #    Anything still owed after this turn is forgiven: the tape's sell
        #    quantities are aspirational, so a carried ledger would choke real
        #    sales later.
        if self.debt:
            kept = []
            for o in market:
                if len(o) >= 3 and o[0] == "SELL" and self.debt.get(o[1], 0) > 0:
                    try:
                        n = max(0, int(o[2]))
                    except (TypeError, ValueError):
                        n = 0
                    cut = min(n, self.debt[o[1]])
                    self.debt[o[1]] -= cut
                    n -= cut
                    if n <= 0:
                        continue
                    o = [o[0], o[1], n]
                kept.append(o)
            market = kept
            self.debt = {}

        items = [i for i in P["items"] if i in _OV_PRODUCTS]
        if P["wheat"] and step >= int(P["wheat_start"]):
            items = items + ["WHEAT"]
        endgame = self.day >= int(P["endgame_day"])

        extra = {}
        for item in items:
            stock = max(0, int(self.shed.get(item, 0) or 0))
            reserve = _pickup_reserve(action, item)
            if item == "WHEAT":
                reserve += int(self.n_animals * P["wheat_days"])
            elif item == "FERTILIZER":
                reserve += int(P["fert_keep"])
            if P["guard_protect"]:
                reserve += protect.get(item, 0)
            already = sum(max(0, int(o[2])) for o in market
                          if len(o) >= 3 and o[0] == "SELL" and o[1] == item)
            surplus = stock - reserve - already
            if surplus <= 0:
                continue
            if endgame:
                extra[item] = surplus
                continue
            if P["mode"] == "greedy":
                want = surplus
            else:
                k = self.window(item, step)
                if k <= 0:
                    continue
                want = _sched_window(route, item, step + 1, step + k)
                if P["mode"] == "model":
                    want = max(want, self.model_q(item, surplus))
            want = min(surplus, want, int(P["tranche"]))
            if want <= 0:
                continue
            if self.hold(item):
                continue
            extra[item] = want
            self.debt[item] = self.debt.get(item, 0) + want

        # 2. Merge into the existing order for that item, else append -- but only
        #    while a free slot exists.  Never reorder, never push a tape order
        #    off the 10-slot cliff.
        for item, q in extra.items():
            hit = None
            for o in market:
                if len(o) >= 3 and o[0] == "SELL" and o[1] == item:
                    hit = o
                    break
            if hit is not None:
                hit[2] = max(0, int(hit[2])) + q
            elif len(market) < CFG_MAX_ORDERS:
                market.append(["SELL", item, int(q)])
            else:
                self.debt[item] = max(0, self.debt.get(item, 0) - q)
        action["market"] = market
        return action


_OVERLAYS = [_Overlay(), _Overlay()]
'''


def patch_overlay(t, has_params_mark):
    t = sub(t, '''# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------
def agent(observation, configuration=None):''',
            OVERLAY.strip("\n") + '''


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------
def agent(observation, configuration=None):''')
    if not has_params_mark:
        t = sub(t, "_OV_LAST_DAY = 29\n", "_OV_LAST_DAY = 29\n\n" + MARK + "\n")

    t = sub(t, '''    __slots__ = ("selected_route",)

    def __init__(self):
        self.selected_route = 0''',
            '''    __slots__ = ("selected_route", "protect")

    def __init__(self):
        self.selected_route = 0
        self.protect = {}''')
    t = sub(t, '''    def act(self, state, seat):
        if state.step < 0 or state.step >= K_TURNS:
            return _DEFAULT_ACTION''',
            '''    def act(self, state, seat):
        if state.step < 0 or state.step >= K_TURNS:
            self.protect = {}
            return _DEFAULT_ACTION''')
    # capture the guard's static-consumption reserve for the overlay to honour
    old_tail = ('''        requirements = _calculate_six_day_requirements(
            state, _TAPES[self.selected_route], state.step, end)
        return _apply_six_day_budget_guard(state, action, requirements)''')
    new_tail = ('''        requirements = _calculate_six_day_requirements(
            state, _TAPES[self.selected_route], state.step, end)
        self.protect = {
            _ITEMS[i]: max(0, requirements[2][i] - state.owned_in_hands(i))
            for i in range(N_PRODUCTS) if requirements[2][i] > 0
        }
        return _apply_six_day_budget_guard(state, action, requirements)''')
    t = sub(t, old_tail, new_tail)
    t = sub(t, '''    action = _SESSION_CONTEXT[seat].act(state, seat)
    _SESSION_LAST_STEP[seat] = state.step
    return _unpack_action(action)''',
            '''    context = _SESSION_CONTEXT[seat]
    action = context.act(state, seat)
    _SESSION_LAST_STEP[seat] = state.step
    unpacked = _unpack_action(action)
    if P["mode"] == "off":
        return unpacked
    overlay = _OVERLAYS[seat]
    if state.step == 0 or state.step < overlay.last_step:
        overlay.reset(state.step)
    try:
        return overlay(unpacked, observation, state.step,
                       context.selected_route, context.protect)
    except Exception:
        return unpacked''')
    return t


def params(*blocks):
    return ('''# --------------------------------------------------------------------------
# Tunable surface (module level so tune.py / port2/sweep.py can sweep it).
# The defaults below reproduce port/main.py action-for-action.
# --------------------------------------------------------------------------
P = dict(
''' + "".join(blocks) + ")\n")


g = retitle(patch_guard(SRC), "the six-day budget guard and route rule exposed as P")
g = sub(g, MARK, params(GUARD_P))
open(os.path.join(HERE, "h_guard.py"), "w").write(g)

o = retitle(patch_overlay(SRC, False), "h1's selling overlay (our market model)")
o = sub(o, MARK, params(OVER_P))
open(os.path.join(HERE, "h_over.py"), "w").write(o)

b = retitle(patch_overlay(patch_guard(SRC), True), "the guard knobs AND h1's selling overlay")
b = sub(b, MARK, params(GUARD_P, OVER_P))
open(os.path.join(HERE, "h_both.py"), "w").write(b)

print("wrote port2/h_guard.py, port2/h_over.py, port2/h_both.py")
