"""port/main.py + h1's selling overlay (our market model).

Generated by port2/gen.py -- do not edit by hand.

Original docstring:
Pure-Python port of ``the-35-0-tape-a-causal-shop-router``.

Exact, self-contained re-implementation of the native (C++/ctypes) policy that
shipped with that kernel:

  * ``source/policy.cpp``                    -- tape replay + route selection
  * ``source/include/six_day_budget_guard.hpp`` -- the only adaptive logic
  * ``source/include/sim.hpp``               -- enums / static data / ``fib``
  * ``submission_bridge.cpp``                -- per-seat session reset rule
  * ``_entry.py``                            -- observation packing / action unpacking

No ctypes, no local imports, and no use of ``__file__`` (Kaggle's raw-python
loader ``exec``s the submission with ``__file__`` undefined).

The two 719-turn action tapes are embedded below as zlib+base85 of the exact
space-separated text that lived in ``source/tape.inc``.
"""

import base64
import math
import zlib
from collections.abc import Mapping

# --------------------------------------------------------------------------
# sim.hpp: item space
# --------------------------------------------------------------------------
_ITEMS = (
    "WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG",
    "MILK", "WOOL", "FERTILIZER", "GOOSE", "COW", "SHEEP",
)
_PRODUCTS = _ITEMS[:9]
_CROPS = _ITEMS[:5]
_ITEM_ID = {name: index for index, name in enumerate(_ITEMS)}

N_ITEMS = 12
N_PRODUCTS = 9
N_CROPS = 5
WHEAT = 0
FERTILIZER = 8
GOOSE = 9

# sim.hpp: unit ops (index == enum Op value)
_UNIT_OPS = (
    "PASS", "NORTH", "SOUTH", "EAST", "WEST", "PICKUP", "DROP",
    "PLACE", "PLANT", "WATER", "HARVEST", "FERTILIZE", "DIG",
    "BUILD_COOP", "BUILD_PASTURE", "FEED", "COLLECT_FERTILIZER", "CARE",
)
OP_PLACE = 7
OP_PLANT = 8
OP_FERTILIZE = 11
OP_FEED = 15

# sim.hpp: market ops (index == enum MOp value)
_MARKET_OPS = ("PASS", "HIRE", "BUY_LAND", "BUY_SEED", "BUY_PRODUCT", "BUY_ANIMAL", "SELL")
M_HIRE = 1
M_BUY_LAND = 2
M_BUY_SEED = 3
M_BUY_PRODUCT = 4
M_BUY_ANIMAL = 5
M_SELL = 6

# sim.hpp: static economic data
CROP_SEED_COST = (10, 20, 50, 100, 80)          # CROPS[i].seed
ANIMAL_COST = (300, 400, 500)                    # ANIMALS[i].cost, i = item - GOOSE
LAND_PRICES = (1000, 2000, 4000)

# sim.hpp: shops, in sorted(SHOPS) order
_SHOPS = (
    "BAKERY", "BRUNCH_SPOT", "FARMERS_MARKET", "ICE_CREAM_SHOP",
    "PET_CAFE", "PIZZA_SHOP", "SMOOTHIE_SHOP", "YARN_STORE",
)
_SHOP_ID = {name: index for index, name in enumerate(_SHOPS)}
SHOP_FARMERS_MARKET = 2
SHOP_ICE_CREAM_SHOP = 3

# _entry.py: tile-kind packing (index == enum TileKind value)
_KIND_ID = {
    None: 0, "EMPTY": 0, "SOIL": 0, "LOCKED": 1, "WEED": 2,
    "COOP": 3, "PASTURE": 4, "PLANT": 5,
}
T_COOP = 3
T_PASTURE = 4

BOARD = 10
MAX_UNITS = 40
MAX_SHOP_INSTANCES = 8

# policy.cpp
K_TURNS = 719
K_ROUTES = 2
K_SEGMENT_TURNS = 72
K_DECISION_STEP = 216

# kag::Config defaults used by the policy (submission_bridge.cpp only ever
# overrides ``episode_steps``, which the policy never reads).
CFG_HIRE_MULT = 1
CFG_MAX_ORDERS = 10

# six_day_budget_guard.hpp: SixDayBudgetGuardSettings, as set by policy.cpp
GUARD_INTERVAL_TURNS = K_SEGMENT_TURNS
GUARD_MIN_UNIT_PRICE = 2
GUARD_SALES_FIRST = True
GUARD_PROTECT_STATIC_CONSUMPTION = True

# --------------------------------------------------------------------------
# source/tape.inc -- zlib + base85 of the two 719-turn tapes
# --------------------------------------------------------------------------
_TAPE_B85 = (
    "c-p;PZL;Jlu6)1GDryNJ0XF;J*z5AAgfg*D_l=2(IJc+Dg)s&srBX@$<WKtZzx*kG{#O0TpPaVO@~8dzTh>qgej?xh<Ujw}z"
    "hZy&&)?<G-}1@w^ZmVSAJ?<d`^sXz*sk2#KfjGv=IuYnmG=kk%Kh(hw^_^w;L5yQZQ76Hg?r!j3ro0i{XXvTw_YtS`}6D{?-"
    "zFS_kNsQ&Bw_+a(M8)zn>EBeLZ+~4<7G*Tz>a*{~+GGj|0@ft%t6fJBzulk5`);+a8v&pXR=u+_zutrO-co-xNkB!TY9gUpp"
    ";k_qDyu;l7F7H$B`p!TV1C{(RSC#VhrvT<@xkYwf383!<98<~!GD_;#_Mpa1Xvy1CDro#f@u#8LbC@@Hhu9=7Y>`ctksCSj*"
    "In>v5J|Ft9VZApH{8IUC`&oT_OUHswq&p(%IkBq;r@GT^~Fk{~<7=WSg&HaA(a(qi{>f!J7fBd_1dbe%Z$}u&*ttm52KlPrt"
    "ag!~_CD%x#urzL)D0^FNcHvLG)=<2n;|`HNFJZUnV=HYOQ#X<7wbZALRAPC{b5{!PN)Ge3UM@izfBrSnurC_+Nz#{`X5%7ZT"
    "dv!DnU9NX+edLPQSIH@_VwY%)ZLFs#HOKn(ZiG<ugGD+)ZM+njmULLni`S%WJIp@rQ2=m-1RfYfBN^&b!fYaGj3aI!0#cK?-"
    "w@G#WHj>+i5d-AlK0xW=S5q2wF_;%4;8%(AaAJ-8L)Nt_kWUcnKewXDXqsJa`z+-|V<E_L+j;bM`~VaZjPib!bw^y6!`R@jB"
    "#v?Tb^vb=}RQb@PKV?5%`NvtO@j_Z;kX5|-O$dg5?NaD&GeWv_F4MjEF|I$R;_Xg2)5h+j&4$0c^)`{BNy>G3yjJAqD?OvP("
    "E&8$hr7upS+UvkBxEo_ye)98BV?wz2;JT4J@;oexAU1B;}j58ZI|I>R>Wc}=1vlem*pW6^4n!gno00Fi*jn2;2d0}Qb7_Q|-"
    "-y1PID|A<|>2iHZ(Efq-5H4wtm*`_xbZSLUAEHugySotI_b<P&%KN%3k1JBBJ>FXxXCE`i2WYUZxylUeV&;vR&<nf1jc=l3G"
    "irJkZSmE!#7y)FWYob-I!oGME7-H|%povc0j{ZzomuyncTRu3uW7@*_AiOk9qjHniF>fPY3y(GDqL(BnpuxnYv^tCYj9su=&"
    "k8XVw=eF=(?J&uuJrs$n1)Jy|(S|K8?3Ax!r#`7TvaJA23lncUA)_V*6MRfOGU(`#q)hJ*Uh<S!X8u^;$B!EBnIU7NC!X8Po"
    "g6%ItHVe(~qG%l5x4)NU4Pwzi)c(|^1t<7|D$?+XI;!THnh_ZXV^MY|d}+&6b+4htSMaSv0C7apyG0W?i)_jg07W_oGpP=<G"
    "Rpmw&nvuk1v^SN)v%|5-w;LkSp7uW%qvYKv;&e^dy+9$DaU@qpW-3#vlSL|+r#!X+te%fIe8(tc)3;p_3K=h>u4RGl6eP<ta"
    "me5)W;aVS`wUhT>LeLX#-dr51(Dt04`+F<yod-<%WXL59d0g+~<d<t^sOww|TTQ3;pm4i$bW$TG1Ny#OgnM!pV-fUM79p`2^"
    "{E7(|GJAM;PZ8`BL0(hWaiYgwfc2eBC4MW&~KxweFs^<&-`aKS`o7YHS`nz;S%TPy>}@1#bG#F%qYZcKp&S&i<_{J?R0;WTb"
    "9(O9PH&{ZmwZLrwCMJyk?J$)jmb+k3}YOOpmT3%$+d?GPZ-Vq-EMnv2ja+*}Te<v+EeP?ky;}Z3+uL+{-r5NdwV12yQ?adJ?"
    "z&{yYlqb!hmljxFS{MJhqo6puomHW0%bG79q^tQa%1JplOv0>;NKfT6Qnf1H#Zx4@!}6rj}d+`zm^*MpmBaYypM2qugRW&(q"
    "Hq{Nhj@uLTOhW;T)0N!lI%Nzs=&XIlk@z-B(Uyt4I)Hw$Fz=Pa=_<gkIjN8FhDd*lL$FRhdaG82a=Rno1k6)i50}jhgjERdb"
    "wzj9R_W`40{i0h(SC$xrvA%TZP@K;+*vXB)5+kh~QxUfvEz#bb9g7*X8L%-KpXf{Hn0TNAB*Z(7t;Wuv0V=bUs5RX`IlNE?>"
    "1#0iY+zi7+NTY5KQ76y(GqbV=6ZM2L<GRW4xC8dZ2JQ3IcyUa(u*1mK_L$kt&STEkjP3Tt7C8H7EpQJjhM#CX^3dj^vz-{`B"
    "=|3as9?N1xR`Xy><&#{=z~P6VT|f6GtSv;P}FE@a&GR48SUJ(_n3zC8hH)<@~7Hb#J4P99DJ=RXj+8^VIqiai18q%>NqSUx{"
    "x{<Ghe-hT~HS#(wUL8Sj7j!)#Uu0bHMU$Rmg?0uJHdgKbcT@jEmhxT4GULfW;&^kj(c{j!?{AE*GuS);Wg4qb`^)rmPX!_>i"
    ")TnQi<e0cZPS}@+i#wpGEqQPqPXrg0&(GITC!EK~3WgOgngGFO2q#N09vHo$u$kK7?qy4J{IRnUX8ckOK^E?r(&CJfek;(uM"
    "C}47AVs>`WVyDGroDEL{f?Fp>@Xxny*4Ec1E6qZyUz)7jK`9TMrab*5aLD(F<j?GpAupR>v^=wtdp@ZCY$R5OC(^$RX#B=xb"
    "dRKe?cQAtbL?s}QJ)Z`RJ~nD!D{UdI*2(Z7OxEdiOzUv((P3V+Y*#1a&%kLo=*216ho)8IR)sV26C2nSWj2t%a?V1ZQDm>PX"
    "v{H4ax>)mMyHle}*8<vKhkr%H7Fxd-=C<Dfbk;H=C_5p{vW?A(#?rL)%&Q4m(dVhkh64(>X6lhA}yN9C_Nujf5=(glX^n*;?"
    "P*m9V^O*mhlhPC(<vDfQhwerT<O9dyeU^sZntT_L?yPze*rhszA$sBSmNtl7@2Ja~QQ%x!z-IOn@XRxkvtxO34Ckg1&uBYD!"
    "jTDLc1hB?s*oXw7y;@$~(VA&OyM0e>Z0m^~_`ell4p1rEzKRY4S^mP4YTsgS>%lPCk%sMJ(@R9r-ukO3T9tZ9G<(y51u0N8Q"
    "yPM>ea#4a|oBtIMzRC^SY5<`u6lHHFBk1UH+;YDnB?%ojubl55@2R&3pz|!CXG$&v1aq-~Y;(0;`;bfdi}$B>jHKh*{Wf%LP"
    "=&=vt3ii*+)nKx9=e*qeaoxyj1H0QWM(hG6Cjp10IrM-t|dNti$hZ|Ob8smhHIPv_J_gmqmP*YuM%rCDhcRK4>JKuQRuzIr+"
    "LvwiDnWsv=TVO_HvjW;Z>|8=SDi&*~?ZoKMM)soec(TBgexTCTO%-X>@o)5rXgZ8efQ@IK*#iAcNZ2)NGNuAp=p7B{NH$l}m"
    "87?fYP<{XC!8E-fgqogAzE07T&4?hPz=JFye#V~L{){EYC(FH)VqON92nkJi1tjPdf#n+6G*-Ha9oGnMEWKY+`9Op!wjuf$g"
    "e0p;Yas(ZbKeH1{~W%K#nqTW9$({ibPu_@O`|3K;CN_-y;@SPu&oj06W9#b%8hQ=hb?Opts+#P8Tq^HC?a=I`DJW`Ll{Teb^"
    "hue}y;@?mkofstE#}~~9W@RkWJQSh`U}sRUbtNQ9^GE_7OkWxJfC9o7z7XUzbcAR4{AQPMPk<YgSW(`J`_be65wn{K8wa-lL"
    "B112jG;cBrvnnnYl4#49E?O_14@|pr$sUpp69wXP<mq;=zotAn<ALy@66A}z+nh2!)!zN_>(i{|H>SH4%_hF5aR3$!@3H=8~"
    "3J^dT23y$C8|`rRdx?5|8D$7W23a`g4UY*t%Rp3v-!s<kPuP>T$puD~dvxP>akA3@8@n<E|9V%4g4njaDJiQ{0&MZXE$TN=D"
    "Yuh_Wei7`-sFR%+}DGwm`?tsoUJ*ihzB+xJ-GDv1@%GTn5KmKGMAfxMuSz4vH}664(51wK&110^iM(h1n`FixN{BJxxuCYR$"
    "lW#&G`vbCpi>MSXx3=_@wWM}MA_YOb+nuaR=W$zhL_@D+bp<X4*jeTSET-m~UP(=SB*iu9V)DUN7V)eczx0_M~`8o2Vw`1Ms"
    "@kXa9y>|R>J>O=8Q4u-OrOuWup(Q3j`L?LGJ#SW01lA&4wm+Eqop7)eEDLOV<l&flwRiL{XV#f34Ygd63j)ZNEA~5j7=x+33"
    "D9RyM|Aw3tG$^GZ^Zcl5oO+S{rDz@lsq9|u-<KfcmND{pO0Gfb*R%MbmkmotZ}Gh3T-)Yw1=Sr<SL47_i=kfS@}W;+k%#w<$"
    "H_<e2pDYX0TS`)77~N$Z@tr?=UmsFfaluafHCcVrqM33hCMaK_XjMNaY7`fIz6RQgo4coD!zO!irk*8~^8s35~zn7$^y<^8i"
    "4Z2Y~WTelgy_$B6B7r4s*!1A7{wbx0fv$!&3TZX@T8i6p(6w`QvXFf>C7(He7Ik+M=yiZ}%n&%pMDRDU2~2+-Yf8u>^^Q!LR"
    "sfM)=~%A?3s0i+~%m(JX8W!SC-+_}$!2J=mpCZjYO9nMS!HD+l*EQm%kCsdUIpSs)rmUqKQ9$IEd-!O`Tx*HPO+3G$jBA9{F"
    "5rmNc@iTMG9j^8+>+^6%ye=f>I593J22gY2AH5Ja$q(kT^TlrJb1s${Q+L6I!ln~?OABzGP!c*hf2S~P#gAvfg)6qb{J=9Tg"
    "!$@HD`OV1u=*%rkOFzyOn`P+Nu3F!@g!O3A!3FLaZqV>1hLO~uBVZZIL(o&M<W7qX`JMpz&HIhzsN+l`d_3H%jXhvoUO01T)"
    "!R$7+dW>E#D=cdpH*X;@gg20dpmGxZH8yz6+(FtWe{q5V{9S%z(K$HtNIAL{pp2j)A<shE(e^EhPuLU5`dXhdObT_Db_o7#a"
    "WV`kJ5XTE|tIXPrgRGh5tft%3?a9V!FRZXryFCo@%5(`=??HwidsHJY7u99$uiuqb0t=Q+`<xA~N#Pchu_^Y*E7Yjl^(-n?2"
    "L!u3Zec9^DApYLKW$8@U^$_9jVpi7alB|MsC-4vP#sl@Fv1MTq(&yD@#AFRVWT^OIn^<r}^R=cD-BgYp2`%ewp(QWE?gUqhP"
    "$=N|6bo!!Pit`xi21d{F^}%&r!&|v0$CvG{2JQAPt5B)fCB90*8wX$+uSC|=6Q-G_v1t`RA(@hf+e`;`A7ZZIwgbq&lV;dpX"
    "B+kZqZ?6CYQ`brE3Adh#<Eic;5HpfXis@swiHE_Lz6H#Wo#%11e9@mFWm1;b3I9A9=MK{x3NM+P?sSr*X}$imN?X@It4Qa)R"
    "Xe*jZ9Ol9xImMqa~`pq|{}PDMay8LZB6EEJeQha-(*a8}%^{d{T~dWS7N}CKhe*8x!#^GX)7c<5U2KZyDbqG-f%G!ebEccJc"
    "<5#<e-KqG=(nn6;iPr0qoB8$_h5S$hdtpgY5qy${MT@?i&FuGOai*IVLP=$jhiG7d#Xg(O1spTO5?^dw};swm8R>saOgb|aE"
    "&Sy*jQpS#b4;Y<+Fohyjbe0(RZE{qN)F--uhfAU^@9&!V7dk&OEty{Ah)?{6X<)~wRTY<z#XIn7-AG#0?;nvoB2*A77gE}|b"
    "1=c|aSAtbP+%87(o=PR$kGQL|<p4aBm~&h9>~`4GJ8Pl>>)BjI){4Sq5QG$JE-3|0!;UV5n+E80z7S8sRtI*m5--hj%rsO!o"
    "C|Ha2nwJKB~hiwHq1*gYP^m1803j7<!AH&rMPxMf+bT@8Q>hsxI?0%@-=4k8^eBZe^KHD0Vqlb8TiZXL>ChrGbV8iNDQlagE"
    "6`n=9uNgN)tf9S%RNkm<q?kZn0o%Yxf=@!j6ThnJ{k)IDY*hAOfyCkkV3ysDfP00-`83gCY=7NU7OjUWfVBC>M6Lp$R!i3^Q"
    "M&SGQtZ6yTI*V!{dLS4xjr5jA`&{id?w41?Iz@=$@QTMEo9Kz24<rW=08{@{O@)u;#kpg_@qdf3EB**iUn<*wMpKE#{MgVIc"
    "6=oW~V87I&ZA5g47TBZ6WnZ*D|)yu5oJVzZeNr*537`sXK2O<F@&?0?jY&{EQ$xY&2lGMnVRb(y?WbH;cX>Jq}+qe;FA5>wE"
    "8*tQFaYb^<s5+I!&zr|hJxir79#70!7sQRR4vIShoq+yO9oEM&MrW5aEFeD_d<|oq9!3DHA*F{fY<O)L3#E{Er+ARvLBd!l7"
    "YRvB$P5&g=m-}e@=0T!dt<fx-4cM!Hbn1HNZbM<2pxTi?nuB}cCCKMp*m?!qSZ0ul~`F4@{d-YXbt|AjqwY3i$bMq8rx2eKw"
    "oEwNi(<YtUN=*?sPSskd*3NTQoDrqmPWnf2K(2;FwkCOsH|#MrT4E+=vP@CBipjR)<n!V8nJ|P=B^C@5Ca(EjsJ^z)AOW4>p"
    "X|%s`ocMpS_|Q$0;AJjySGw{_}M)kg|IddM+n6pKTr0YF7FHzh|W+(4|5%ARQr8FE-w((}X!rG+KksqM~JabK}iA~Z!RjZ-T"
    "l*_srn^<Kaagy|P_=0dN8gy0tkA8=G(DI|r`Vv`8IN)Hv3GrTQ|_7zsTkTHwEjV<7cR7Rm}q<FBiu|)tvA^k6Sr2~cs=+l8B"
    "#6uf$CSaRI5M+w<AgURNYa#~3a(#equ~NoXd~b{rOesm;t4mW3jYB5*mL6lq75Y}WxSgn)V{PY0ZuG}YT@VTX54aM0j)B$ET"
    "R)%-OrbX8UBZkPC<{|E4;3v6qG%!y6<;K>2_y`t1R`&W<`t%a@jlAX2zlWMScgI=C8RSX_(`$#ag56}(gF%45&2lS(P<Aw`<"
    "-RI5-r&N;De5UE7;#;Y*7L}(+CV9K&<E?v0aTFa@Qk|ijHy|WDX`kYc!nvd?UImDnRd3u=(-^byIb3-<rh0#W3LnS|qGWBa@"
    "7%hJB)gcepavAtky1RD~L*LFR478&O~y^Mfcs#-7sg_5iBH4)>(hB*};4U-_<Giu~}7H#^$U>86Z0%PL~ZZA_a@X(kXSrbwA"
    "k;t9qz>Y8ngl>v}f!23+$WhStb0m7va*^3f2B}Rzi4O;@ZR=%tMA^kGf0i!4YqY$Fc^GKQ)0_PkGA(fGb8D4P~lLZu{&kGp="
    "Y@wvyV)@`>rqIUUDLJ|^9K^@|_2K9UTHp|TA)#gW^R1UuF#ty#COj!WFynLzVsaMd8y3bTIY&fTP>0m8(>(MD1!VxgD#QsCu"
    "A;ASfE8DRR64>diN;4}{mFs9U5p8(!L0;gO2|D9`L+%l$XW=`RP{H7!6U#cpmS7Br#p&&V5XW{dcBhYkawd5xhSMf39Ke6`N"
    "X6$I*YqFaFN)OS6aE#LCNptZ!}zb1hI>iA@yZ&7dLv|rjI%1smaNeAM_$IUJu4um<Cc}^2rGocmRGKm52w)!xWXAB6=a8sZ^"
    "ja|1UxGBK<<%ud{4O!g-Lk3x6LD<S$*0pY_Tp#mWmN|2J>fxECmcZ-|TT1~P@t?r?qaYi%JI2bg)&w!JlJT<BmS^m2kg+A<G"
    "NX1PSiRp#E2)jHKE`IcC4BXQ|=wmYLCRvNLR!yV#oy*`a{W_+b}UalRzA{v%5qEesX7I1*&p@=;TbABach5P^uaOT!I<nLK+"
    "4JU<O3Kat9Q*fyOU<ND2ij_$Y1s+7DCXxYqI?Ma{sa)sEN1591j%hdOz!haeNO7Nw73;@QWB`Rrl*o~uyxRcOmw^LuqxH<EV"
    "$Sj>MFL@sCOju1KiPv#jc2){-6+kawhGaTUqh>nK{!;mdU_rzVA)b$#T;@dW23CZ<nM|;b`RoK@|Imcc=-!$sJ7Yk1`0SWW1"
    "?Q?yg5AT*^Njr(XP{QU`ph4tTuH1G_A99W{nXlkch}pQm_CVa;}q{33G5FSkm8gIFFmbynazgC2I#T^g2-5U=eNwaPeJkzao"
    "6a>|dR~J1$%Mi3h$6e8;miy-fI=l*9(Y=vZ-x$SwfN%FN^HfV#bSW}6#lWoA#Q&z8p(Dk!B_nK(xw=8fqWWXfhk$re@uG7{S"
    ")QjTF3Qke9S^4FN)fr**b7-pGvy0aarQt`(`Bn^}#`}2hMNqDpz<qWH^%=7zw3UaQ4>(gW9tni4#j<3wBVkY|$&A_e%0#eMd"
    "g<@+=<pvOWvW$i#(Y-xQ#g|I}B>UedJEoG&;S7R3xpaW1%Ri$KW9g=Nd)Dj`Y|wv@Lvyi`+Gd+YSvK}`AqlTy!)`H-V||dHV"
    "@FOpey3nXba|&Xk-@&bUIKiT9)QpoUptco#L?n1Rk4B&O8jdz0^8@!IYj^fCueOHW|oG%HKEe5{6VLIO%Q|@gZP!AEMk;Em#"
    "0yK%*{OBC3y{0j2*0OJPU(`#CZTR+NaJ4lR)*#cKRMvfyK9FzH@exXxL+k14jt6G}D5R#DeQ^;u<Q~n`a|>v`<FGb71*Wrcn"
    "p1pbY2(n^?bK<qxivqSLDRZB)S?YUd)@S(M07bW2+n%tP!`wbYEA6EyET6UU<kR?CisTyC{`)!Kz-bvlDc));Zgs1dz>UYtq"
    "fwxxyX>b}>CCfAGxz5ex?LS+zjx?}&>X9`8VXz#MI0)RdzMV_Z29Id8@L%2{LdBIWgqhmnWW{87S*+u~*)H5X-gT-%M7<c!K"
    "eO%5-Se(?q%rs)@+3sMis_&-2GL}xl7MTE}_fgROOnXX<i!zBL3c(V~IJo|N<R?s~KSej~Zg|HizRfFt=SovDtOR8n>VcLZ1"
    "h-k|rmhjoa#<&V08MB4ghFtO?gm9ipS+P}(dP~(I|Ek8&Op!808|xW^pSFzo(`FklpOP&41=$;5Eea)xK}JP4bLG;b4W^_b)"
    "gHRYsOD1$p?5}yiR%l^u6?;_zp4)O#K1W5f|nuz9>#mLRFDb?ftz`@8pwXo!CR>H*V>_uoKfz@z91--qXfFWV+860YzEhZqF"
    "}bWsKmkW5n~nH;G3!ex(5d)+wJ-@e$CL87L5i^Sy5%?B^@1l<s%5brd^4#D<-C^Cdv6`~K@r9p}Qvkd~jY{_Uy#zOh%Ijt*V"
    "{hz2a|QSBoE-REx^WJEzNd^jYef>%XK3E2jMG!!0Q6%)JKUwxt4+ntql6_bqdwcX2>?EAAM7pr~`^qot906;lMh_jVe-6Gbb"
    "OeI*s+!XLTCHfkGOb{M;SV?)p<?Zl1kHmowrhe6l!)G5?2%|_@5z{(-*gALDGe}7H=k6g))2(rtp$cf{iDxzp{_A);qKy4RV"
    "&`eDc9ifta~t`?*-dj6fUPVrfRFrx^)81}o=zo?vQQ+veX`&{U8pEfA$y<Fa)Nx?nd;v5FI&#Bh+9S_#xhs#&oj6z9xEcGLW"
    "l8|#F4`U%S6gt7&`8Y>jxf`lwVcrGliXqII*h0!pi&mXE+s$4pbrm3=!2n<|T*4m<j~R@Y&b9>{Fhx(1aku{R5BQ0aXoDMKC"
    "kjUE|$Rnt;r!D+=_Lb9XtUHt*j`8ER-GVew9yMUkIOYq-||{EckHP03j}(KGJ0Cly36+@>@-E>q4n?d?RCDHibnt6@>6<B{`"
    "*C*Yjp16X|TybH*8PQ<7CRDF2}N1)Deo?FEJH~{{n;{JwgCkzRfkb-|@$lDBAzljdZKbUTPbvBZ|Iy~VDwF`l~^#!XgRMZ!S"
    "`}FB?5@i}>_Xn;HI|TM2z@A$A{s4ht<Iiv&bWpRRToxhw(PX8PUB8Dc0y{59nW_#jBHz6MoNp(L#4DfYlYi_}GrUzvYl@<1!"
    "2&#qXaF?gyIqgGA5xaj<)Z8X8@(M!e;6;<dTDcgO?i=6dEZ)}4P<mM+(U-iMiAdOSnGbO)z^6D=Jbdclp7K6Ov<MLJ`4$FQ0"
    "eYS$KR^*FUwuX02IQ3Z0tR4U+CUwrw5b_2atyisDb*@bVN(YGi}odDYN`$bO!reUqc@>7Ot#ep(Y-j+R^}y)qDc3?O80{GT2"
    "{>yREMO%g!mOdc@LK3uWE$>@QC}XDIMDqRI!JDnISo2<zEs<avF+*siSm0nFi8i*qdZiM(HVfAERcYPs7i<^yo$ak6_G;^%n"
    "b-nXA)){j^2>I3`VdbPOh&vQx>z^!|4u@VMkcyO2Mw)egsJi7;v_dYJad%1tW&Mr3t)WNMso_`yv`V-EtnH$?4ma(7azMb5+"
    "U+pDQ-!k4eg^@|{zG=!Uo!vK7qq+Ms9!q+-Z-V!o{{6|vNu<bME+fEd#;IHjqME<vJ5aJ<zFm;+(ET;qtn&GD@loH7vK#W|_"
    "HX?uPo<{Y75lH3Anvn=Z{rNeA<F(Kqf%>e55v{q@z1SaH~zZ9w~+9{jD4?Q01}G8I{tEeOKj@l@AQBCyK{QCBgfjV+G(W$V!"
    "bCWDgODXW460Me@^zc+U&xgdaWTM%^W*K`n=5Y<*_SKAEsVQecDJRmbW~2rQoi_!@uk05+tUy7WxvZWmsQaYBzL7!nRzmP=J"
    "q%Y}-fqBo<t><FKZDw&;AFg8NQ9yAH1i?988?K#*}Ga$PdzLrkym>uXPjJODGs_)q`-w8_B`Ly`mfJ>>HJ!ZxM<=fU0Uj}HX"
    "2NJB2bc9BXH<@?zi3Fg;P?B%D8`3c65GtX3T($aVsl+e%z7XuJ~0B66A3$0`2brTLSRXv$phrF+SaVog34@DnpBMq=EC}=%j"
    "Iex6^XED|=T!KMV^P-Zgx5@Fs0W@8RquKELB7Q0H9hcaF?}v9CQ2p$hNjj@d-VJD6+i7M^GQQAm;QSInp>!H6eyn+qUTHK|w"
    "tIpv+#74NOH3z=ab`2lf9xY0tsfB53+69}z$2Q!6&L^kwm6N>&enNhW;qzH<wf6F=3#~I3N~FpC~35RU_FFO+T$hq*cF{x(b"
    "I>h)Y|SYgl<&4_f~mdm*sIq3bn_kK+()TW{wZgpqlz5R!6qa8#AF7c6}S)1Yy;io`E9TI`~bU94BBd0oZAStzgfd3FO+YB$^"
    "|+JF|Y&GL3Y|dYXIfUlOOAsFKOhMx@M|{?g>H>8>v?&>^-o-hH3ArJZCMO<&Sfb!56oOjp<?dQD`0%KU07eblEZ^_boHST;|"
    "XsITYE4q1uzu^s^D=(YBHO6_}2nT4{>O!m99irtlcVQ&l2$HI*1{bObJIZwa%^V{X5C@{NOsM%U}uzNKjn_kwgevVx67X<1b"
    "evBrNGtf|q({J|;r~+#&F^S6X{l>HxSJ|B-3u0_yyFU<et%P%u;oTjmoh|O{npi<Wo1DI*GYaQt*74~$dvbLnGJC_Rsum8+#"
    "ay*};hm6q&(8>1+3lwthOvx@=f{GJsPDZjL>P6vvyVDijgAf1Ixgu@LUj>13xHz9-tTC8&d>e5bxIt|3^(dS+MrCsxpDH#H8"
    "a$8E&-(yHFWJi|8Ki<pOb$&WtW{Lq4{#evI&viTZBYuD3##zt2?Y4p!DFAc4X#sI6|Z26IYNLa>cUN`wqg@S%&hifaUDJZ|E"
    "lt2|YB>049qahNH!dLd*tqEF$MNVPT2klYt~I<q#Pei_!QD2f})wBI7lCY^?SvlrY7P+;mKjuCt=9Oc0LCB}7p+YsP7{C78{"
    "tEIGSIVY+nr6NTWT%vTN#bkaZ}CHkQOVdzQR_WScFxYwcKw>q|v!xpIoSyMa;ecAvM6$qm+@4<>OGus1@FG$lO9@9cX!iNg;"
    "wPY0Da4A<zHDwLVn+zgB*%^>u1rx>vGl4-pQesT1XY^pt&_4tTz?&s%y&y<H+PL(`?WB;SI^{W1fACt$R%2<6+rd^T=iVj9u"
    "*8&bnR-g+K-Giwt8rs?#F$Qaha>k?k9ADP`bD>nt}Kk4#7dn<hvIyu!A|BplfXsF>06x(V@)L@Ab^35$@oNH8c^@)00|Y3Q7"
    "U$Eb_NYlnWaR1c|&-i4ANIZ#*71_vHXlR)cv?5bj~9smzP+xW=2GU$xF<s?%rX-dk))#h4i9ELr~`O@huqCWv+LdnA%A)6Ri"
    "<|WL}JJ(>OT|5lx!DS&Stg>)9r*f2ntKuH`et(Tmupe?iUfgYNC9I#XPrq9JuhPye%eBEVYJDH1|X(LEPgC|?Ki^pqT4P{FO"
    "7rQ4jYT4y-Xz}!6#vDa8@O{uF&>aqsbzCeu=BpI(Ru(*#^>H{3-x{558&fSKBjhk1hp@+~R{TQOiW4p=Fym?ol)<>R*b3BRg"
    "1M9{IGco;HAVRmk8P0WH;=4}E=g9ngBT`SQyKPw{P(A{~Tc(;#b|fp6NM7c}z^vdL02ZBnRA%fA_hKT<&+1GH6$nbcutKIy_"
    "Nk(-j*=__;^XyGK5g3kC}31hwTt!QV9ASuHFoUMaqyFDfx<}mpEpS=+HEDAG2xRe?=-6`zY?rZ54YN!fHA)Oj|%IeP~E)jd^"
    "Fsv)!ulze0I%kwfF8+ARF-+Pwklt#F}et1xjIHXr5P_kEGt}O6;h1+(R|GBkRVhD^xT?v24Z4U^Ny>q0)At<%WuFi;^NWa9}"
    "#k#2Fu}#wvM<`!*}aTlOlL#cdO1-zMbv7AS5v(vZZ$B)J+rK#FRMrS_lMALr0qW<9-|mcka)@v|CRVtD_&!-Zq~Z+s=Oo71<"
    ");6OHXg3Ixl#-!L4ikA%uDu-HjwN;brM<+)&ATeZAJ%<<eLWS$r=x2@TlVfPtI8cR2Z~=5_8HqQ|KRm0M0|((0qFZmLKqr9W"
    "f#4~2EC<oUHb^HIwjU_*t8+XoZ*LDAe3O{F9;<|WNFU3Mmlp-?NE0Vvf8o_}H|a@{R?p?Sg|GXnJ>+Y$$w_kA`JZ}oTku(Tz"
    "i}Pp4$z$dLnZVxc2ut=Lj~~E)m<)LZ%W54N~X)Gj83diAp#+9n-gd8zDIh4sBB>YYeXbj*?J}W7CTZaX77hC=GjQv9?7-f8@"
    "<DE+S<c-#y*t*31=Lv0W%B8!gIxx7*K}M>EXE<9zny&8n>hp+RowMG5SLXX)H4m|MZ-7MVh87Vt`<1F8YD?#pqPCd<ClsxQk"
    "e!t`cy37UBEmmbm4|e(7ulot9ez)2KbXV61m{p7A0>W>%)@-2OuJu0%0DH=Geu7A&dY>>*vth2($>)-)9A`jr>(dBNf!iuvy"
    "EMPjX`o*!`c+ECwfYW@2#JU@ityQ!X?5&Lz!r~)|k@k<~U8A^zLrUzbukA@7UUIxX0<C&RBB&>77%d$%w<aAPTmLs*G?0f_-"
    "eUZH$`f_4c)p9QA0W9E%D_2CHBY3bdcfJ#02=jaa4QNb_xlHJvqWf5(g~-mJ$N*gXN_LpeC3r-zf(R;61<;rrMAU*M3azapC"
    "kqZ#VVY$tv>=j)xz)bMKeQJKdjxN`O=|z^p~rO%l0YDTF{tniJA^zWuKY-eld-)gSfL4@!ZHLSSw@fXQWnwb6bLqDNa?7Fv^"
    "=yZ7MBQ&<W!W?#nvdyAX+*p@^1ID5{^`>0L={7T4RcO$t*-Sza%bwQZB`i=43bNK9$Rhcwq9WZTSVv&B~jO-t64_^G^Nnjou"
    "r>ovi6kRege|nX_I`2FKaIKh`nNTugdi8amlwd)yqtDxeR<2-6y#dnXz-#%BS(lgzT;>ow={SV_qajm<<f>t3nr{p^XKeDbC"
    "U`Siwei1Gz^7>R=0)*i$GL~wZtY9Az`D$NYxqutG<I$*4N*XBkKu&?S=N}G)yNck^QwLBNy*`cd!=%!@~cHoK|IQh)a;d-T5"
    "yA56O6R**9dzqFju)#yZX!<Na{Ig?m4VT7yM`AgS5x|3YZ0_3_?#I%ooqJ5FxZ53%ira4^C}8qs>bez@y)Nft!-WRCw?Y!v#"
    "rY)}dvIV5mKi5wAHTCbvK9H$m(8US-DroelLxUzws!z0p^Wox9)KoBn2QwS^j`#@ddy2}Ue8jq6^5ObhrFGBZSa3R=GbecR#"
    "uE_-byCrGA=Hb7~Y--pP31kKm?RnwyaYE&gKEvedm<V?0_7&L$_!z+a2bv#}FpM=_>OjAucw}IM!IsybfU_d1S6#fpa_dyF?"
    "klE5N0E>CSRxUw3}^HkgX6Mk7EIH}GLha|NT>r&%#1%V|b)8@LrZEO{n>GRFJgR(=fAm_ojOTL$yo%*n%=7tRs*kb|=TJ8Ik"
    "eh8;QpasD)Le(3Hf+nK-$@5GIotE9L4-SlX^g@xN?wzr%Xq|nC#3xG~eYDC=cGMn_#?X;V$gqOhvsvvWu*N(8lC?yiQvdjp!"
    "KJ<u^u=Dr2!m*R}jLE;h>7<@1=Mcp*{e<>8kHmB)`3;?WYLWLN!K`BHUma9(AC+Apm1%|NA=*<+!7(Lzh0}Q;Xcyp^%T(#Nj"
    "H9@1<J(PewQ1ym@5WiC<Z6G6fDU9+ULOOvJp}gNdz`@n^!padS0#pncN^I2j271C8*nD7%eL2wN^u!hY)`l9z}MZ*2sJ&<e5"
    "8eJH~{68v(E`R^*+ALG!g*_x@nm4lz`jd4^V3#asrAO242bnU}l}sdh96R!Sw?_&07vLB0+|HBiMImcCnAWeK_WXviTS6QlT"
    "NJ%=zwf4fKvj7BQ%vj_{&q6Y8M)KkN_l^LpkZD|Qfskj%jOWec7Pw$aXvH{p`ZhBYGS@MNaM1P#*%o|&;X{jEJ(9RLjk<kt{"
    "R3o+H-&|=+NZc{vb4c2_wDV0LN{QdOMz3IQJy&|r|ZnCih(f`JQsJ?7C4_3E4MCbeQ$iaiS=h%rDFjzi%5WCBwn1FDdHL)HA"
    "xht^sm6@1+-5|RY*a6u_2cZMV1WP271(;_!co46sV1*^tdrS-H1Psm$tpm=3eB$Xr*3Ku&$I)j&)o3@@NW|giA0ihE$OmT~@"
    "?D4{#<n_It8Ay*6DgJD?pM;;Lb(`VU(O6dn0Iyo4oV`>H|RnfTXc*&C@9u>w#&Gw`k5b+LGwC|2-BYDsOS&^gQ){B?noV7hm"
    "nBBmZAmxsMda4mG#1V6x-d-266?PMFLxP^Si}<REM%%Nf~~&0(@T2z)oz=J0dpQvDQM5TI!(Jx)GOduSMA~up9^|FA1)YG7J"
    "ZtRmAbdah<Sovgl&~PPmhO(U*E9uRo8;_<uMwb$&)sOc6wp5{N~lP%K^nN4>mI6AwW}K@oA9il5G#1)2S)dgf)CNpm3(2r6`"
    "{s>+Jp(JmgckC`3+CYV@HT`}MubecfGt-{*3g@o`*0oTwjf>02eLm71mM?qBX=FNGl>jxbRb{MkZG*dLhO7yFCNGD1Uwu8vO"
    "rR3C*<vvV0B?Afw>%o1-`~d(aYwY1^nK7*2HxERXbjJQNZNgB>gtZUR5$$6w!^{u%);<#|HE^)4R|O2)l?mJVf)xD<KFVt5V"
    "xp6ri9!LZ1}Zyr&}`J{5Yhq-#a=5%(h6Ikd4`|>RwR`JDxcXYi>#}SWn01KM9x~Yvv=9Er#h8Ib2DzG>V3M=OivJ{z2g<UQm"
    "oPMOc*Ez|KLT`)A*1KzJgrFdL$<*@gmY$`9GRcCOA4j!o>I<^CllE(D(^j(dN_mv@=3s#4TL2iLFd!y=`E>4&4Q$hBT$UWmY"
    "L3tbU)zQ-vo5>_7vv&&dpF&e`!b_@To*9$Vw1pwZ1^n3>s2i#u2z{kb0K=jvRQMBiMZY3Ryk^GT;r7_Jwp0>{vbWoCRbOW<<"
    "GAgb5WaeBy{0k8rql!&W=Jf8H11l$R(-@U_w68wc3dH_`xvQDzF5q#iQFC-hc55zhb)Hn=Zr;G=Hmu@yA#UQM+UZwYHLpnt7"
    "`9Zv%a-5xyeAa&4F}(yN0GuiVz=uSJIo+dKC>0{HDU*<hg>L7U>!a#ve_bZm|6>@U9b^awLnz@W-jZs|)Qwo|dMku$p;Om^g"
    "yU>;%nx`(HBHMji9s3_&XlMqhmnxi%{cBbz>9Td0JFCXzhiMv1hI!km9Z$8P%;<3>tP5$Q!9%!;n-R`0AQK*MQs!u+jZOxlm"
    "XoOqSymKqAet+X)+-(c;0P@g$yx`o{;ho5@iW_1`w8JRzoPLz%r)dzNWZxGtYucUi{n#U;~Yb5Eu!`^H%JiM}N3Ka^{)#%{Y"
    ";T+05A2qm~klGFy2vWzYg(Pe~2qj(LH-B{}ZDx@>!fqN6%^Bs;2>tfMVqr=Ws93I<sRFI(-L+dHYGlrNkiI-SmXI@vLMk*4b"
    "T8oh^sB;!j7mxCTKb0L-uJ&Xm2cV`b3ElZ8~XGg-#*}4_AX;7`%KOco`>s33x-lhMeL!tWsJHR6|0VHAepRlH=n&v{$GjKRZ"
    "o;6#jS{LxTflPE^`2Jj<FF$Y=^7Fnn-~;)W$wCyubz07!!02}Dsvw>`7~T>&6D~3myuULMZf^rSE%gqbN}110fX_S|qjA_W("
    "~wi9#@#Xd*n#2YK_yYpt8-T@hs`>p2DNVxu#~-<l3!s%G7d_KFG?Tu92w0ez$l&0*}~k!igO!|+YLP9B|gitAA3>f#~5rik<"
    "pmSTzm&@LpXV~M))UZq9Y)b8XU3J$mIa}&w~?@GZQgi0dM?dMTjAD48#h)B~b>0iT35x6CAmnLL~0|ie!7qfI_BMfB^uM6UN"
    "FS^^%GF7UO=-*&2t3Kc-~f|26)|p6Q6Z2qhXm8Pskp@SK<}PZ-%$EDt3wgmz8c&H=DF_C-Q+`zsa*sMuf}R<+LQ;aq|i6i(W"
    "97rT-RGjhsGiCMFa0RTX3U05zeX4MJGbc6vXt<Go;K6pq>yESu+v5;77AvxdESmrl?f(BZh4;&K9ErsMb82WW20_wE<r!YDW"
    "DCX#7@^YddK=GDnRLnRm%nG@Y-<k25N-+#nl6I_QftPj4FG{bZo;P0oRobUB#4eE&DL`egjKV5sR9!&^2KiqPmM^Cuu&@)@Q"
    "Lz<!v6Mv_Pdwd~Gq+=E-K&7R9H2s5GEdyguUEahso%Ot2Tt8yS8iO%2>~7G1lMmXZW;6lHIN+c3KAKC7~|%8A|P64Cx4`|RK"
    "#sDfZs{Fs#qM!jDlLkBvaQVJ?OE=t40CAe}XmG{ulX`J!DDt4A30bC?KSd>0d;gs^)0lGE0)k1DSGp6LM1cA+gi~NTxD@Zcq"
    ">Ri=0Wrfh=Hf<ODY8%EbUUwo~rNc4P}E=d;qS@Q#f49dEg6cdn`(W#^|TCAw0dBvxV;f)#*yDeUd`yN-$e*oCfYWGn$L;!Bx"
    "MxK?hj9cp=i0t!(7C}CF(<hRZU&M+;PSQadfH7!3(Oj{9H)etI!gi&W4y3VSgyGMW$fQLHUC)lM~M#e~H2jvNPYlSLytYf=E"
    "B4?qAlEPFw^oHMs5Z0dHqc*{koG&A;s%3)_I!&4g+jYIbh@SfPauXRdBAu=@1-O!TXyKG&;M=^Sq;X9TAgd{}>J31=Y=H<u^"
    "flkNIj3ciijZBg>F<h5yOU=uK~JLcV<&Jq>BpTgs#uCqSz5VFWpG0wC0ek`3fyD@_zYT*1~`EAjcvLz+3~rS$LFF5c_3vx$Z"
    "WO?@j>CO3(_(>VId3oKOUT^%*a!@^p#XhydC6DqLYrR^que3re3JfXjur)wbJsk8V9k&4JNAXxX~4c9;^(uUa`=Q2WRT5u`T"
    "nn81Cq-IWoyY>=GE_!tjVS;xp|-wa;^!DqjfZ>Z2L9zJx6kvqzgHaud0*=vD|#s9^ammj&|=uFTyM0v^MX5cM<6u@Ch#KRv7"
    "v9_BV2dIb|#(g4X)gA*b^a4m$>?3PWL2Odf^r-KOlfg`m@n{f92P~3_63Sp?h8Bs0A!Q|rbhp9@mfFcocc7YB$lyj)!<#`C*"
    "q}}RYI2Sb#FDm@^8V*HU`B6s4;>fJ5EeED$ndVqd%;aK?qNAh`$d>bzE?;Jec(fXpDFhvBVGleYGwN1OZ|opIW-Rupp2IGPg"
    "BfX6fUHqiJlk%m4;xn=3vHpu$pc*?qXj-Bn1Y&b_a<$Pd!P`eIH)X65l#Rq$DQ2ol&I8eZA4NUB^|R<QQfq=+4y6vXr1d=7a"
    "}d7NZ&${`a)*Otxgjn(aN2u%yL%5A~CXu&^Qx$CUdq(jiJ5(4?E52wVh@R08?2=y$z+;#za04zMw~hcfxiQu392cnd{A4r7E"
    "87ILjejjzeaITb@1BsepCln<>LJf&Wg?PfKLzKrS~iEs>R^&Td=3Mv??S_L^yEbzEzjBF)oRl>l5YLgkT9dY+o1zlT0p9qSb"
    "O_-&SDmlW$)ooZxqMEQ!*JAr<Q49Ar`=u!ZG+TQZC!a5vGSXp|5+4gvFuRSM~>se32AShpx{TR^mDOi;u$jF|)LEcY67Y~+z"
    "-A$NgT?SmTb=$_SZtrguCS(?-PCz9xcChF0n<U~TnQ$79PH_H=8E&!Xy+SSl(cL+2LdM&TbaC!UwoEt^6Qn21)(v$!S`t>dt"
    "Hk2_H+0YBiLN$f$j&6;kACWi(`N|Nbjq}7gE-QeUNa+6o=(4@Fcn}Yhl6kxgfe~lFm4dzan)`jGzJtY)7xqX=l__y%4N1#x&"
    "EHDLo26U2Z5{Gj5s?3NdU6Mo;m$7PUI^Wki%*fQidUTv=i3_Y;k``<d}f_l-z{oD5&Yq(D=Fmb_du`1#+URP=IsOzVUXLv1#"
    "hJOuyX#i&voe>(etv8OlN`Q|~;<Ahqds=t^?@yz~JRJQW<0`ta*KRi||RKzsc&Sl;2S6P(X!e&7Yu2moVQ82ydck@V3>yM1_"
    "Jj>W!2p!#$UVv**#+q?kcX+-qihN(g?AOYH)NKqMP-nPn(OfR_dz03pI`eEnm=;@aXJMUBSrBJ$G^f2AF+bv#X-xl(+%-5Te"
    "<L#;K5mDHXgbB>Pi97AW61IH6i>oX^xP~`z=###)=*Aeofj?no9G%9LoMgt%2Jver;kQ~D``Z<vseYj)wH=d9$~~!|UW&dEp"
    "%q~CuI*2zTKBMKqT$j|Fszxy%Q={JP>^xdO2}tC2RcK&?5J2}*Vo--nV-r$Pfv7^g~*AX(Dw_|o(E6%P<cp1W8#H{cZMSr3C"
    "%MCVBNadInmg>vVaDl0K2zf=QtoR@=61GJXIb;P!zBJq7HP-UR<ju3kyx)fzXNB?S2pNx%Zpwf{@^H0RE6^Izh`}6DgFP#bP"
    "jL3-&KetA)Y8TzVM@E;*G%VYROS=+8tHEe-MQYUeQ5IF>gCsv8)^Sbi!Q&>u2V?Ssyl+Ky<`3tdVNjJM@M*+N3WdyEw+T-72"
    "pL{NJ7_GoxZ&*NJVoSl8Zh?0k$c0E3Taa<|hULFcO6cY@S^$0TK6Lhw$=&?3?5lmRi!r1B$(-;shBr20Os!k8`I}M4F-czeg"
    "U%s7KJ$MN+&Z{FG`jC%fVY%4SQ5kXo{g+Gx&&4t_mjCDwpp!DE5>Q?YTLM?X09!dS{N!o^fhIz|-}O9GJ#P^UOa~l$%k(fow"
    "={ib+_cvy{GGXF#4UolClEPAm2j9^33f_Yxd1;8*KPjCK;}<IVunEa$U}NG)BAn40>IrYtlk?`xW?epwg}1<5X(bYm1GFhK;"
    "=VbTfVS3-iFZ1$gvgajS2Hu%-a`c)0jxIEf)`jtY&9uVFM4wS&94Y9Ed{G#xkFwePH&=d0fNxJEaN0N)Naogna;d73R6-2bz"
    "6I6#!u1I-7YY(wQ7^-8P8o+U^i!1Q&drYFKr=J-yP!L<y@An55XmtK)-$hn^oOnQso(NZvnJ1DKT$FM_T-rbt7DRJllwcd|M"
    "$>LF6De4#sO5=j35@0V9+ShIicOEQ>|l?7>KDr}i&A`Z=A^7A)8KhmR&u2?4Z+<7i87)gyX(Z0<Oa=)O1$NWr|Zl3vBn>1AD"
    "BeW?j0O<^s5Jm@&ISqPnL_D!i5#*D&G_pP^Jd*~Wv<;)9QJAVOapPz@8hAy@tRyQN0Gag0p1N)AT=Agt*q!;;nW&3wo3Qy?z"
    "}Ob@;tDI#(=mn@#)4tT*70LC*0W7}>SCD+>2vhxCdqF}+6wUS7XIDlg-qh!SlTNEn_<Z36OKj)jbtiWMCnHN4Rf)44h;h&o{"
    ")^cF78|R6gO+80UPHk4i=!L(87S)kLvyiTVPonB+rzR;wL3`p&b%MX(Q|HzGmJ8;pN#dgRj9y_gK~c2aZk_AO"
)


# --------------------------------------------------------------------------
# Tape decoding (policy.cpp::decode_action)
# --------------------------------------------------------------------------
def _i16(value):
    """static_cast<std::int16_t>."""
    value &= 0xFFFF
    return value - 0x10000 if value >= 0x8000 else value


def _u8(value):
    """static_cast<std::uint8_t>."""
    return value & 0xFF


def _decode_action(encoded):
    values = [int(token) for token in encoded.split()]
    if len(values) < 2:
        raise RuntimeError("invalid encoded tape action counts")
    n_units, n_orders = values[0], values[1]
    if not (0 <= n_units <= MAX_UNITS) or not (0 <= n_orders <= 16):
        raise RuntimeError("invalid encoded tape action counts")
    cursor = 2
    units = []
    for _ in range(n_units):
        op, arg, quantity = values[cursor], values[cursor + 1], values[cursor + 2]
        cursor += 3
        units.append((_u8(op), _u8(arg), _i16(quantity)))
    orders = []
    for _ in range(n_orders):
        op, item, quantity = values[cursor], values[cursor + 1], values[cursor + 2]
        cursor += 3
        orders.append((_u8(op), _u8(item), quantity))
    if cursor != len(values):
        raise RuntimeError("trailing encoded tape value")
    return (n_units, units, n_orders, orders)


# kag::Action{} -- the value-initialised default: one unit, {OP_PASS, 0, 1}.
_DEFAULT_ACTION = (1, [(0, 0, 1)], 0, [])


def _load_tapes():
    text = zlib.decompress(base64.b85decode(_TAPE_B85)).decode("ascii")
    routes = text.split("\x00")
    if len(routes) != K_ROUTES:
        raise RuntimeError("tape blob route count mismatch")
    tapes = []
    for route in routes:
        lines = route.split("\n")
        if len(lines) != K_TURNS:
            raise RuntimeError("tape blob turn count mismatch")
        tapes.append([_decode_action(line) for line in lines])
    return tapes


_TAPES = _load_tapes()


# --------------------------------------------------------------------------
# sim.hpp helpers
# --------------------------------------------------------------------------
def _fib(n):
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def _is_animal(item):
    return GOOSE <= item < N_ITEMS


# --------------------------------------------------------------------------
# _entry.py observation reader.  The native build packed the whole observation
# into a C struct; the policy only ever reads the fields extracted here.
# --------------------------------------------------------------------------
def _read(value, key, default=None):
    if isinstance(value, Mapping):
        return value.get(key, default)
    getter = getattr(value, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(value, key, default)


def _count(mapping, name):
    """_fill_counts, one entry."""
    if not mapping:
        return 0
    return int(_read(mapping, name, 0) or 0)


def _packed_tile_kind_and_animal(tile):
    """_entry.py::_fill_tile -> (kind, has_animal, what)."""
    if tile is None:
        return 0, False, 0
    if isinstance(tile, str):
        return _KIND_ID.get(tile, 0), False, 0
    kind = _read(tile, "kind")
    crop = _read(tile, "crop")
    animal = _read(tile, "animal")
    if kind == "PLANT" or crop:
        return _KIND_ID["PLANT"], False, (_ITEM_ID[str(crop)] if crop else 0)
    if animal is not None:
        return _KIND_ID.get(kind, _KIND_ID["PASTURE"]), True, _ITEM_ID[str(animal)]
    return _KIND_ID.get(kind, 0), False, 0


class _StateView(object):
    """The subset of kag::State that this policy actually consults."""

    __slots__ = ("step", "n_shops", "shops", "prices", "money", "n_quadrants",
                 "hires_today", "shed", "n_units", "inv", "rival_tiles")

    def __init__(self, observation, seat):
        step = int(_read(observation, "step", 0) or 0)
        self.step = step

        market = _read(observation, "market", {}) or {}
        price_map = _read(market, "prices", {}) or {}
        self.prices = [_count(price_map, name) for name in _PRODUCTS]

        town = _read(observation, "town", {}) or {}
        shops = list(_read(town, "unlocked_shops", []) or [])
        n_shops = min(len(shops), MAX_SHOP_INSTANCES)
        self.n_shops = max(0, min(n_shops, MAX_SHOP_INSTANCES))
        self.shops = [_SHOP_ID[str(shop)] for shop in shops[:MAX_SHOP_INSTANCES]]

        farms = list(_read(observation, "farms", []) or [])
        if len(farms) != 2:
            raise ValueError("ShopForge needs exactly two public farms")

        own = farms[seat]
        self.money = float(_read(own, "money", 0) or 0)
        positions = [_read(own, "farmer", [0, 0]), *list(_read(own, "hands", []) or [])]
        self.n_units = max(1, min(len(positions), MAX_UNITS))
        self.n_quadrants = max(0, min(
            len(list(_read(own, "unlocked_quadrants", []) or [])), 4))
        self.hires_today = int(_read(own, "hires_today", 0) or 0)

        private = _read(observation, "private", {}) or {}
        shed_map = _read(private, "shed", {}) or {}
        self.shed = [_i16(_count(shed_map, name)) for name in _ITEMS]
        inventories = list(_read(private, "inventories", []) or [])
        self.inv = [
            [_i16(_count(carried or {}, name)) for name in _ITEMS]
            for carried in inventories[:MAX_UNITS]
        ]

        self.rival_tiles = farms[1 - seat]

    # policy.cpp::animal_tiles
    def rival_animal_tiles(self, animal):
        result = 0
        rows = list(_read(self.rival_tiles, "tiles", []) or [])
        for row in rows[:BOARD]:
            for tile in list(row or [])[:BOARD]:
                kind, has_animal, what = _packed_tile_kind_and_animal(tile)
                if (kind == T_COOP or kind == T_PASTURE) and has_animal and what == animal:
                    result += 1
        return result

    # six_day_budget_guard.hpp::owned_in_hands
    def owned_in_hands(self, item):
        result = 0
        for unit in range(min(self.n_units, MAX_UNITS)):
            if unit < len(self.inv):
                result += max(0, self.inv[unit][item])
        return result


# --------------------------------------------------------------------------
# policy.cpp::choose_observed_tail
# --------------------------------------------------------------------------
def _choose_observed_tail(state):
    if (state.n_shops < 3 or
            state.shops[0] != SHOP_ICE_CREAM_SHOP or
            state.shops[1] != SHOP_FARMERS_MARKET or
            state.shops[2] != SHOP_FARMERS_MARKET):
        return False
    return float(state.rival_animal_tiles(GOOSE)) > 1


# --------------------------------------------------------------------------
# six_day_budget_guard.hpp::calculate_six_day_requirements
# --------------------------------------------------------------------------
def _planned_quantity(quantity):
    return max(1, quantity)


def _calculate_six_day_requirements(state, tape, start, end):
    purchase_budget = 0.0
    starting_seeds = [0] * N_CROPS
    starting_items = [0] * N_ITEMS
    seed_balance = [0] * N_CROPS
    item_balance = [0] * N_ITEMS
    hires_by_day = [0] * 6
    quadrants = state.n_quadrants

    for step in range(start, end):
        n_units, units, n_orders, orders = (
            tape[step] if 0 <= step < K_TURNS else _DEFAULT_ACTION)
        for index in range(n_units):
            op, arg, n = units[index]
            quantity = _planned_quantity(n)
            if op == OP_PLANT and arg < N_CROPS:
                seed_balance[arg] -= 1
                if -seed_balance[arg] > starting_seeds[arg]:
                    starting_seeds[arg] = -seed_balance[arg]
            elif op == OP_FEED:
                item_balance[WHEAT] -= 1
                if -item_balance[WHEAT] > starting_items[WHEAT]:
                    starting_items[WHEAT] = -item_balance[WHEAT]
            elif op == OP_FERTILIZE:
                item_balance[FERTILIZER] -= 1
                if -item_balance[FERTILIZER] > starting_items[FERTILIZER]:
                    starting_items[FERTILIZER] = -item_balance[FERTILIZER]
            elif op == OP_PLACE and arg < N_ITEMS:
                item_balance[arg] -= quantity
                if -item_balance[arg] > starting_items[arg]:
                    starting_items[arg] = -item_balance[arg]
        for index in range(n_orders):
            op, item, n = orders[index]
            quantity = _planned_quantity(n)
            if op == M_HIRE:
                day = min(5, max(0, (step - start) // 24))
                hires_by_day[day] += 1
            elif op == M_BUY_LAND:
                extra = quadrants - 1
                if 0 <= extra < 3:
                    purchase_budget += LAND_PRICES[extra]
                    quadrants += 1
            elif op == M_BUY_SEED and item < N_CROPS:
                purchase_budget += CROP_SEED_COST[item] * quantity
                seed_balance[item] += quantity
            elif op == M_BUY_PRODUCT and (item == WHEAT or item == FERTILIZER):
                purchase_budget += state.prices[item] * quantity
                item_balance[item] += quantity
            elif op == M_BUY_ANIMAL and _is_animal(item):
                purchase_budget += ANIMAL_COST[item - GOOSE] * quantity
                item_balance[item] += quantity

    for day in range(len(hires_by_day)):
        first_hire = state.hires_today if day == 0 else 0
        for index in range(hires_by_day[day]):
            purchase_budget += CFG_HIRE_MULT * _fib(first_hire + index)

    return purchase_budget, starting_seeds, starting_items


# --------------------------------------------------------------------------
# six_day_budget_guard.hpp::apply_six_day_budget_guard
# --------------------------------------------------------------------------
def _existing_sale(orders, n_orders, item):
    result = 0
    for index in range(n_orders):
        op, order_item, n = orders[index]
        if op == M_SELL and order_item == item and n > 0:
            result += n
    return result


def _add_budget_sale(orders, item, quantity):
    """Returns (ok, new_n_orders); mutates ``orders`` in place."""
    if quantity <= 0:
        return True
    for index in range(len(orders)):
        op, order_item, n = orders[index]
        if op == M_SELL and order_item == item:
            orders[index] = (op, order_item, n + quantity)
            return True
    limit = max(0, min(16, CFG_MAX_ORDERS))
    if len(orders) >= limit:
        return False
    orders.append((M_SELL, _u8(item), quantity))
    return True


def _budget_sales_first(orders):
    sells = [o for o in orders if o[0] == M_SELL]
    rest = [o for o in orders if o[0] != M_SELL]
    orders[:] = sells + rest


def _apply_six_day_budget_guard(state, action, requirements):
    n_units, units, n_orders, orders = action
    if (state.step < 0 or GUARD_INTERVAL_TURNS <= 0 or
            state.step % GUARD_INTERVAL_TURNS != 0):
        return action
    purchase_budget, _starting_seeds, starting_items = requirements

    orders = list(orders)  # kag::Action result = input;

    available_cash = state.money
    for item in range(N_PRODUCTS):
        sold = min(max(0, state.shed[item]),
                   _existing_sale(orders, len(orders), item))
        available_cash += sold * state.prices[item]
    shortfall = purchase_budget - available_cash
    if shortfall <= 0.0:
        return action

    candidates = []
    for item in range(N_PRODUCTS):
        price = state.prices[item]
        if price < GUARD_MIN_UNIT_PRICE:
            continue
        protected_total = starting_items[item] if GUARD_PROTECT_STATIC_CONSUMPTION else 0
        protected_shed = max(0, protected_total - state.owned_in_hands(item))
        available = max(0, state.shed[item] - protected_shed -
                        _existing_sale(orders, len(orders), item))
        if available > 0:
            candidates.append((item, available, price))
    # std::stable_sort by (price desc, item asc); candidates were appended in
    # ascending item order, so the item key is already satisfied.
    candidates.sort(key=lambda c: -c[2])

    added = 0
    for item, quantity_available, price in candidates:
        if shortfall <= 0.0:
            break
        # static_cast<int>(std::ceil(shortfall / price)); shortfall > 0 and
        # price >= 2, so ceil() >= 1 and the truncating cast is a no-op.
        needed = int(math.ceil(shortfall / price))
        quantity = min(quantity_available, needed)
        if not _add_budget_sale(orders, item, quantity):
            continue
        shortfall -= float(quantity * price)
        added += 1
    if added > 0 and GUARD_SALES_FIRST:
        _budget_sales_first(orders)
    return (n_units, units, len(orders), orders)


# --------------------------------------------------------------------------
# policy.cpp::Context  +  submission_bridge.cpp::Session
# --------------------------------------------------------------------------
class _Context(object):
    __slots__ = ("selected_route", "protect")

    def __init__(self):
        self.selected_route = 0
        self.protect = {}

    def action_for(self, step):
        if step < 0 or step >= K_TURNS:
            return _DEFAULT_ACTION
        return _TAPES[self.selected_route][step]

    def act(self, state, seat):
        if state.step < 0 or state.step >= K_TURNS:
            self.protect = {}
            return _DEFAULT_ACTION
        if state.step == 0:
            self.selected_route = 0
        if state.step == K_DECISION_STEP:
            self.selected_route = 1 if _choose_observed_tail(state) else 0

        action = self.action_for(state.step)
        if state.step % K_SEGMENT_TURNS != 0:
            return action
        end = min(K_TURNS, state.step + K_SEGMENT_TURNS)
        requirements = _calculate_six_day_requirements(
            state, _TAPES[self.selected_route], state.step, end)
        self.protect = {
            _ITEMS[i]: max(0, requirements[2][i] - state.owned_in_hands(i))
            for i in range(N_PRODUCTS) if requirements[2][i] > 0
        }
        return _apply_six_day_budget_guard(state, action, requirements)


_SESSION_CONTEXT = [None, None]
_SESSION_LAST_STEP = [-1, -1]


# --------------------------------------------------------------------------
# _entry.py action unpacking
# --------------------------------------------------------------------------
def _unit_order(op, arg, quantity):
    name = _UNIT_OPS[op] if 0 <= op < len(_UNIT_OPS) else "PASS"
    if name in ("PLANT", "PICKUP", "PLACE"):
        item = _ITEMS[arg] if 0 <= arg < len(_ITEMS) else _ITEMS[0]
        return [name, item] if quantity == 1 else [name, item, int(quantity)]
    return [name]


def _market_order(op, item, quantity):
    name = _MARKET_OPS[op] if 0 <= op < len(_MARKET_OPS) else "PASS"
    if name == "PASS":
        return None
    if name in ("HIRE", "BUY_LAND"):
        return [name]
    item_name = _ITEMS[item] if 0 <= item < len(_ITEMS) else _ITEMS[0]
    return [name, item_name, int(quantity)]


def _unpack_action(action):
    """submission_bridge.cpp::pack_action followed by _entry.py::_unpack_action."""
    raw_units, units, raw_orders, orders = action
    n_units = max(1, min(raw_units, MAX_UNITS))
    # pack_action zeroes the struct first, so slots the tape did not fill read
    # back as kag::UnitAction defaults ({OP_PASS, 0, 1}) for units[0] when the
    # tape declared n_units == 0, and as zeros beyond that.
    packed = []
    for unit in range(n_units):
        if unit < len(units):
            packed.append(units[unit])
        elif unit == 0:
            packed.append((0, 0, 1))
        else:
            packed.append((0, 0, 0))
    farmer = _unit_order(*packed[0])
    hands = [_unit_order(*packed[index]) for index in range(1, n_units)]
    market = []
    for index in range(max(0, min(raw_orders, 16))):
        order = _market_order(*orders[index])
        if order is not None:
            market.append(order)
    return {"farmer": farmer, "hands": hands, "market": market}


# ==========================================================================
# h1's selling overlay: our market model, re-pointed at this tape's shed.
#
# It only ever ADDS units to a SELL order (or appends one when a free order
# slot exists), and books what it pulled forward as debt repaid out of the
# tape's own later SELL orders.  The tape's order ORDER is never changed and
# nothing is ever pushed off the 10-slot cliff.
# ==========================================================================
_OV_CROPS = {
    "WHEAT":      {"myd": 4,  "interval": 0, "maxy": 6, "ongoing": False},
    "CARROT":     {"myd": 3,  "interval": 0, "maxy": 4, "ongoing": False},
    "TOMATO":     {"first": 8,  "myd": 8,  "interval": 1, "maxy": 4, "ongoing": True},
    "STRAWBERRY": {"first": 10, "myd": 10, "interval": 2, "maxy": 4, "ongoing": True},
    "MELON":      {"myd": 12, "interval": 0, "maxy": 6, "ongoing": False},
}
_OV_ANIMALS = {
    "GOOSE": {"interval": 1, "held": 4, "product": "EGG"},
    "COW":   {"interval": 2, "held": 6, "product": "MILK"},
    "SHEEP": {"interval": 3, "held": 6, "product": "WOOL"},
}
_OV_PRODUCTS = list(_PRODUCTS)
_OV_MARKET = {
    "WHEAT":      {"base":  25, "T": 400, "bf": "sqrt",   "bt": 0.80, "af": "log",    "at": 0.20},
    "CARROT":     {"base":  35, "T": 450, "bf": "hinge",  "bt": 1.00, "af": "sqrt",   "at": 0.70},
    "TOMATO":     {"base":  60, "T": 200, "bf": "hinge",  "bt": 0.40, "af": "sqrt",   "at": 0.60},
    "STRAWBERRY": {"base": 120, "T": 100, "bf": "sqrt",   "bt": 0.70, "af": "linear", "at": 1.60},
    "MELON":      {"base": 250, "T": 300, "bf": "log",    "bt": 0.20, "af": "sq",     "at": 3.60},
    "EGG":        {"base":  50, "T": 332, "bf": "hinge",  "bt": 0.40, "af": "log",    "at": 0.20},
    "MILK":       {"base": 160, "T": 122, "bf": "sqrt",   "bt": 0.60, "af": "linear", "at": 1.60},
    "WOOL":       {"base": 200, "T": 105, "bf": "log",    "bt": 0.20, "af": "sq",     "at": 3.20},
    "FERTILIZER": {"base": 100, "T": 200, "bf": "linear", "bt": 0.40, "af": "linear", "at": 0.40},
}
_OV_SHOPS = {
    "BAKERY":         ["EGG", "WHEAT"],
    "PIZZA_SHOP":     ["MILK", "TOMATO", "WHEAT"],
    "BRUNCH_SPOT":    ["EGG", "WHEAT", "STRAWBERRY"],
    "YARN_STORE":     ["WOOL"],
    "ICE_CREAM_SHOP": ["STRAWBERRY", "MILK", "WHEAT"],
    "PET_CAFE":       ["CARROT"],
    "SMOOTHIE_SHOP":  ["STRAWBERRY", "MILK"],
    "FARMERS_MARKET": ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY"],
}
_OV_PULL = {p: 0.0 for p in _OV_PRODUCTS}
for _shop, _prods in _OV_SHOPS.items():
    _m = 2.0 if len(_prods) == 1 else 1.0
    for _p in _prods:
        _OV_PULL[_p] += _m / len(_OV_SHOPS)
_OV_SHOP_INTERVAL = 3
_OV_MAX_SHOPS = 8
_OV_TICKS_PER_DAY = 6
_OV_I0 = 10000
_OV_HINGE_GAIN = 8.0
_OV_LAST_DAY = 29

# --------------------------------------------------------------------------
# Tunable surface (module level so tune.py / port2/sweep.py can sweep it).
# The defaults below reproduce port/main.py action-for-action.
# --------------------------------------------------------------------------
P = dict(
    # --- h1 selling overlay -------------------------------------------------
    mode="lookahead",       # 'off' | 'greedy' | 'lookahead' | 'model'
    items=["STRAWBERRY", "MILK", "WOOL", "FERTILIZER", "MELON", "CARROT", "TOMATO", "EGG"],
    lookahead=40,           # turns of the tape's own schedule to pull forward
    wheat=1,                # 1 -> also manage WHEAT (animal feed: keep a reserve)
    wheat_days=1.0,
    wheat_start=300,
    fert_keep=0,
    start_step=0,
    price_gate=0.0,
    hold_gain=0.0,
    sell_bias_glut=2.2,
    sell_bias_tight=2.0,
    hinge_meter=0.5,
    shed_target=88,
    unlock_trust=1.0,
    opp_weight=0.85,
    opp_mirror=0.7,
    mine_w=0.7,
    horizon_days=0.6,
    tranche=99,
    drain_gate=4,
    window_cap=24,
    win4=[0, 4, 3, 2],
    hold_horizon=0.2,
    opp_press=0.0,
    endgame_day=30,
    guard_protect=1,        # 1 -> honour the guard's static consumption reserve
)



def _ov_shape(func, x, T):
    if x < 0.0:
        x = 0.0
    if func == "linear":
        return x
    if func == "sq":
        return x * x
    if func == "sqrt":
        return math.sqrt(x)
    if func == "log":
        return math.log(1.0 + x)
    if func == "hinge":
        if not T or T <= 0:
            return x
        u = x / T
        d = u - 1.0
        return u + _OV_HINGE_GAIN * (d * d if d > 0 else 0.0)
    return x


def _ov_price(item, inv):
    p = _OV_MARKET[item]
    base, T = p["base"], p["T"]
    if inv < _OV_I0:
        amp = p["bt"] * base / _ov_shape(p["bf"], T, T)
        price = base + amp * _ov_shape(p["bf"], _OV_I0 - inv, T)
    else:
        amp = p["at"] * base / _ov_shape(p["af"], T, T)
        price = base - amp * _ov_shape(p["af"], inv - _OV_I0, T)
    v = int(round(price))
    return 1 if v < 1 else v


# _OV_CUM[route][item][t] = units of `item` this tape sells over steps 0..t-1.
_OV_CUM = []
for _tape in _TAPES:
    _sched = {p: [0] * K_TURNS for p in _OV_PRODUCTS}
    for _s in range(K_TURNS):
        _nu, _units, _no, _orders = _tape[_s]
        for _i in range(_no):
            _op, _it, _n = _orders[_i]
            if _op == M_SELL and 0 <= _it < N_PRODUCTS:
                _sched[_ITEMS[_it]][_s] += max(0, _n)
    _cum = {}
    for _p in _OV_PRODUCTS:
        _run = 0
        _c = [0] * (K_TURNS + 1)
        for _s in range(K_TURNS):
            _c[_s] = _run
            _run += _sched[_p][_s]
        _c[K_TURNS] = _run
        _cum[_p] = _c
    _OV_CUM.append(_cum)


def _sched_window(route, item, lo, hi):
    """Units of `item` the tape sells over steps lo..hi inclusive."""
    lo = max(0, lo)
    hi = min(K_TURNS - 1, hi)
    if hi < lo:
        return 0
    c = _OV_CUM[route][item]
    return c[hi + 1] - c[lo]


def _pickup_reserve(action, item):
    reserve = 0
    for order in [action.get("farmer", ["PASS"]), *list(action.get("hands") or [])]:
        if (isinstance(order, (list, tuple)) and len(order) >= 2
                and order[0] == "PICKUP" and order[1] == item):
            try:
                reserve += max(0, int(order[2])) if len(order) >= 3 else 1
            except (TypeError, ValueError):
                reserve += 1
    return reserve


def _town_demand_now(shops, item, step):
    demand = 1 if item != "FERTILIZER" and step % 24 == 0 else 0
    if step % 4 != 0:
        return demand
    for shop in shops:
        products = _OV_SHOPS.get(shop, ())
        if item in products:
            demand += 2 if len(products) == 1 else 1
    return demand


class _Overlay(object):
    def __init__(self):
        self.reset(0)

    def reset(self, step):
        self.last_step = step
        self.debt = {}
        self.sold_today = {}
        self.day = -1
        self.opp_pipe = {p: 0.0 for p in _OV_PRODUCTS}

    # ------------------------------------------------------------- observation
    def observe(self, obs, step):
        me = int(_read(obs, "player", 0) or 0)
        farms = list(_read(obs, "farms", []) or [])
        self.me = me
        self.farm = farms[me] if me < len(farms) else {}
        priv = _read(obs, "private", {}) or {}
        self.shed = dict(_read(priv, "shed", {}) or {})
        self.invs = list(_read(priv, "inventories", []) or [])
        market = _read(obs, "market", {}) or {}
        self.inv = dict(_read(market, "inventory", {}) or {})
        self.price = dict(_read(market, "prices", {}) or {})
        town = _read(obs, "town", {}) or {}
        self.shops = list(_read(town, "unlocked_shops", []) or [])
        self.day = step // 24
        self.hour = step % 24
        self.day_left = _OV_LAST_DAY - self.day
        self.drain = self.drain_rates(self.shops)
        self.n_animals = 0
        self.pipeline = {p: 0.0 for p in _OV_PRODUCTS}
        for row in (_read(self.farm, "tiles", []) or []):
            for t in row or []:
                if not isinstance(t, dict):
                    continue
                if t.get("kind") == "PLANT":
                    self.pipeline[t["crop"]] += self.plant_future(t)
                elif "animal" in t:
                    self.n_animals += 1
                    a = _OV_ANIMALS[t["animal"]]
                    rem = max(0, self.day_left - 1)
                    per = min(1 + a["interval"], a["held"]) / a["interval"]
                    self.pipeline[a["product"]] += t["yield_units"] + rem * per
                    self.pipeline["FERTILIZER"] += rem
        for p in _OV_PRODUCTS:
            self.pipeline[p] += self.shed.get(p, 0) + self.carried(p)
        if step % 6 == 0 or self.opp_pipe is None:
            self.opp_pipe = self.scan_opponent(farms[1 - me] if len(farms) > 1 else {})

    def carried(self, p):
        return sum(iv.get(p, 0) for iv in self.invs)

    def plant_future(self, t):
        cd = _OV_CROPS[t["crop"]]
        age = self.day - t["planted_day"]
        if not cd["ongoing"]:
            room = cd["maxy"] - t["yield_units"]
            last = min(cd["myd"], age + self.day_left)
            days = max(0, last - max(age, (cd["myd"] + 1) // 2) + 1)
            return t["yield_units"] + min(room, days)
        k = age - cd["first"]
        done = (k // cd["interval"] + 1) if k >= 0 else 0
        left = max(0, cd["maxy"] - done)
        left = min(left, self.day_left // max(1, cd["interval"]) + 1)
        return t["yield_units"] + left * 1.5

    def scan_opponent(self, farm):
        pipe = {p: 0.0 for p in _OV_PRODUCTS}
        for row in (_read(farm, "tiles", []) or []):
            for t in row or []:
                if not isinstance(t, dict):
                    continue
                if t.get("kind") == "PLANT":
                    pipe[t["crop"]] += self.plant_future(t)
                elif "animal" in t:
                    a = _OV_ANIMALS[t["animal"]]
                    rem = max(0, self.day_left - 1)
                    per = min(1 + a["interval"], a["held"]) / a["interval"]
                    pipe[a["product"]] += t["yield_units"] + rem * per
                    pipe["FERTILIZER"] += rem
        return pipe

    # ------------------------------------------------------------ market model
    def drain_rates(self, shops):
        d = {p: 0.0 for p in _OV_PRODUCTS}
        for shop in shops:
            prods = _OV_SHOPS.get(shop)
            if not prods:
                continue
            mult = 2.0 if len(prods) == 1 else 1.0
            for p in prods:
                d[p] += mult * 6.0
        for p in _OV_PRODUCTS:
            if p != "FERTILIZER":
                d[p] += 1.0
        return d

    def mean_drain(self, item, days_ahead):
        n = int(days_ahead)
        if n <= 0:
            return self.drain[item]
        base = 1.0 if item != "FERTILIZER" else 0.0
        known = self.drain[item] - base
        n_now = len(self.shops)
        tot = 0.0
        for t in range(self.day, self.day + n + 1):
            future = max(0, min(_OV_MAX_SHOPS, (t + 1) // _OV_SHOP_INTERVAL) - n_now)
            tot += known + base + future * _OV_TICKS_PER_DAY * _OV_PULL[item] * P["unlock_trust"]
        return tot / (n + 1)

    def forecast(self, item, days_ahead, extra=0.0):
        d = self.mean_drain(item, days_ahead)
        return _ov_price(item, self.inv[item] - d * days_ahead + extra)

    def supply(self, item, horizon=None):
        if horizon is None or self.day_left <= 0:
            scale = 1.0
        else:
            scale = min(1.0, float(horizon) / max(1.0, self.day_left))
        mine = self.pipeline[item] * scale * P["mine_w"]
        theirs = max(self.opp_pipe[item] * scale, mine * P["opp_mirror"])
        return mine + theirs * P["opp_weight"]

    # ------------------------------------------------------------------ policy
    def model_q(self, item, avail):
        horizon = max(1, self.day_left + 1)
        total = max(avail, self.pipeline[item])
        q = total / horizon
        q *= P["sell_bias_glut"] if total > self.drain[item] * horizon else P["sell_bias_tight"]
        if _OV_MARKET[item]["bf"] == "hinge" and self.inv[item] < _OV_I0:
            q *= P["hinge_meter"]
        q = int(math.ceil(q)) - self.sold_today.get(item, 0)
        shed_total = sum(max(0, v) for k, v in self.shed.items() if k in _OV_PRODUCTS)
        carried_total = sum(sum(v for k, v in iv.items() if k in _OV_PRODUCTS) for iv in self.invs)
        overflow = shed_total + carried_total - P["shed_target"]
        if overflow > 0:
            q = max(q, min(avail, int(math.ceil(overflow * avail / max(1, shed_total)))))
        return max(0, q)

    def window(self, item, step):
        g = int(P["drain_gate"])
        k = int(P["lookahead"])
        if g == 0:
            return k
        if g == 1:
            return 0 if _town_demand_now(self.shops, item, step) > 0 else k
        if g == 4:
            return min(k, int(P["win4"][step % 4]))
        if g == 2:
            free = (4 - (step % 4)) % 4
            return min(k, free)
        shop = 0.0
        for s in self.shops:
            prods = _OV_SHOPS.get(s)
            if prods and item in prods:
                shop += 2.0 if len(prods) == 1 else 1.0
        cap = int(P["window_cap"])
        for d in range(0, cap + 1):
            s = step + d
            pull = shop if s % 4 == 0 else 0.0
            if item != "FERTILIZER" and s % 24 == 0:
                pull += 1.0
            if pull > 0:
                return min(k, d)
        return min(k, cap)

    def hold(self, item):
        spot = float(self.price.get(item, 0) or 0)
        if spot <= 0:
            return False
        base = _OV_MARKET[item]["base"]
        if P["price_gate"] > 0 and spot < base * P["price_gate"]:
            return True
        if P["hold_gain"] > 0:
            h = float(P["hold_horizon"])
            nxt = self.forecast(item, h, extra=self.supply(item, h) * P["opp_press"])
            if (nxt - spot) / spot > P["hold_gain"]:
                return True
        return False

    def __call__(self, action, obs, step, route, protect):
        self.last_step = step
        if P["mode"] == "off" or step < int(P["start_step"]):
            return action
        self.observe(obs, step)
        if self.hour == 0:
            self.sold_today = {}

        market = [list(o) for o in (action.get("market") or [])]

        # 1. Repay what we pulled forward out of the tape's own later orders.
        #    Anything still owed after this turn is forgiven: the tape's sell
        #    quantities are aspirational, so a carried ledger would choke real
        #    sales later.
        if self.debt:
            kept = []
            for o in market:
                if len(o) >= 3 and o[0] == "SELL" and self.debt.get(o[1], 0) > 0:
                    try:
                        n = max(0, int(o[2]))
                    except (TypeError, ValueError):
                        n = 0
                    cut = min(n, self.debt[o[1]])
                    self.debt[o[1]] -= cut
                    n -= cut
                    if n <= 0:
                        continue
                    o = [o[0], o[1], n]
                kept.append(o)
            market = kept
            self.debt = {}

        items = [i for i in P["items"] if i in _OV_PRODUCTS]
        if P["wheat"] and step >= int(P["wheat_start"]):
            items = items + ["WHEAT"]
        endgame = self.day >= int(P["endgame_day"])

        extra = {}
        for item in items:
            stock = max(0, int(self.shed.get(item, 0) or 0))
            reserve = _pickup_reserve(action, item)
            if item == "WHEAT":
                reserve += int(self.n_animals * P["wheat_days"])
            elif item == "FERTILIZER":
                reserve += int(P["fert_keep"])
            if P["guard_protect"]:
                reserve += protect.get(item, 0)
            already = sum(max(0, int(o[2])) for o in market
                          if len(o) >= 3 and o[0] == "SELL" and o[1] == item)
            surplus = stock - reserve - already
            if surplus <= 0:
                continue
            if endgame:
                extra[item] = surplus
                continue
            if P["mode"] == "greedy":
                want = surplus
            else:
                k = self.window(item, step)
                if k <= 0:
                    continue
                want = _sched_window(route, item, step + 1, step + k)
                if P["mode"] == "model":
                    want = max(want, self.model_q(item, surplus))
            want = min(surplus, want, int(P["tranche"]))
            if want <= 0:
                continue
            if self.hold(item):
                continue
            extra[item] = want
            self.debt[item] = self.debt.get(item, 0) + want

        # 2. Merge into the existing order for that item, else append -- but only
        #    while a free slot exists.  Never reorder, never push a tape order
        #    off the 10-slot cliff.
        for item, q in extra.items():
            hit = None
            for o in market:
                if len(o) >= 3 and o[0] == "SELL" and o[1] == item:
                    hit = o
                    break
            if hit is not None:
                hit[2] = max(0, int(hit[2])) + q
            elif len(market) < CFG_MAX_ORDERS:
                market.append(["SELL", item, int(q)])
            else:
                self.debt[item] = max(0, self.debt.get(item, 0) - q)
        action["market"] = market
        return action


_OVERLAYS = [_Overlay(), _Overlay()]


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------
def agent(observation, configuration=None):
    seat = int(_read(observation, "player", 0) or 0)
    if seat < 0 or seat > 1:
        raise RuntimeError("ShopForge native policy failed")
    state = _StateView(observation, seat)

    # submission_bridge.cpp::kag_submission_act session-reset rule.
    if (_SESSION_CONTEXT[seat] is None or state.step == 0 or
            state.step < _SESSION_LAST_STEP[seat]):
        _SESSION_CONTEXT[seat] = _Context()
        _SESSION_LAST_STEP[seat] = -1

    context = _SESSION_CONTEXT[seat]
    action = context.act(state, seat)
    _SESSION_LAST_STEP[seat] = state.step
    unpacked = _unpack_action(action)
    if P["mode"] == "off":
        return unpacked
    overlay = _OVERLAYS[seat]
    if state.step == 0 or state.step < overlay.last_step:
        overlay.reset(state.step)
    try:
        return overlay(unpacked, observation, state.step,
                       context.selected_route, context.protect)
    except Exception:
        return unpacked


# ---------------------------------------------------------------- cash guard ----
# Measured on 19 ladder replays: the tape commits ~$2,830 of its $3,000 on day 0 and
# then runs the whole season on a minimum balance of $0-9. `_do_hire` silently no-ops
# when money < cost, so if the balance touches zero exactly when the morning HIRE
# orders are processed we get NO hands at all. One farmer cannot water 19 crops: every
# plant is a weed within two days, the livestock starves, and the game ends with a bank
# of exactly 0. That happened in 18 of 117 games; the hires that failed cost $4 in total.
#
# The tape's own six-day budget guard cannot cover this -- it protects the static feed
# reserve so strictly that it never fires.
#
# Walk the market list exactly as the engine will, and only if the HIRE orders genuinely
# cannot be paid, raise the shortfall from the cheapest thing in the shed and hoist it to
# slot 0 (orders settle in list order, so position is what funds them). Gated to the
# opening days, where every observed death spiral began. Verified bit-identical to the
# unguarded agent across 40 normal episodes and 3 stress configs.
#
# Every name here is suffixed: the module above already defines P, _fib, ANIMAL_COST and
# LAND_PRICES, and shadowing ANIMAL_COST (a tuple indexed by int) with a dict silently
# broke the agent into a 3000-bank no-op.

_BASE_AGENT = agent

PG = dict(enabled=1, max_units=4, buffer=5.0, last_day=29, min_fails=1)


def _gfib(n):
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


_G_SEED = {"WHEAT": 10, "CARROT": 20, "TOMATO": 50, "STRAWBERRY": 100, "MELON": 80}
_G_ANIMAL = {"GOOSE": 300, "COW": 400, "SHEEP": 500}
_G_LAND = [1000, 2000, 4000]


def _guarded_agent(obs):
    a = _BASE_AGENT(obs)
    if not PG["enabled"]:
        return a
    try:
        farm = obs["farms"][obs["player"]]
        market = list(a.get("market") or [])
        if not any(o and o[0] == "HIRE" for o in market):
            return a                       # only hire turns can fail this way
        if int(obs.get("day", 0) or 0) > PG["last_day"]:
            return a                       # every observed death spiral began on day 1
        prices = obs["market"]["prices"]
        shed = obs["private"]["shed"]
        # Walk the list exactly as the engine will, so we fire only when the hires
        # genuinely cannot be paid. Orders settle in list order, so everything ahead
        # of the first HIRE moves our balance first -- buys included.
        money = float(farm["money"])
        already = int(farm.get("hires_today", 0) or 0)
        n_quad = len(farm.get("unlocked_quadrants", []) or ["NW"])
        short = 0.0
        n_fail = 0
        for o in market:
            if not o:
                continue
            k = o[0]
            if k == "HIRE":
                cost = _gfib(already)
                already += 1
                if money < cost:
                    short += cost - money
                    n_fail += 1
                    money = 0.0
                else:
                    money -= cost
            elif k == "SELL" and len(o) > 2:
                money += min(int(o[2]), shed.get(o[1], 0)) * prices.get(o[1], 0)
            elif k == "BUY_SEED" and len(o) > 2:
                money -= _G_SEED.get(o[1], 0) * int(o[2])
            elif k == "BUY_ANIMAL" and len(o) > 2:
                money -= _G_ANIMAL.get(o[1], 0) * int(o[2])
            elif k == "BUY_PRODUCT" and len(o) > 2:
                money -= prices.get(o[1], 0) * int(o[2])
            elif k == "BUY_LAND":
                money -= _G_LAND[min(2, max(0, n_quad - 1))]
                n_quad += 1
            money = max(0.0, money)
        if short <= 0 or n_fail < PG["min_fails"]:
            return a                       # the hires are already funded
        extra = []
        need = short + PG["buffer"]
        for p in sorted((p for p in shed if shed.get(p, 0) > 0 and p in prices),
                        key=lambda p: prices[p]):
            if need <= 0 or len(extra) >= 2:
                break
            px = max(1, int(prices[p]))
            k = min(int(shed[p]), int(need // px) + 1, PG["max_units"])
            if k > 0:
                extra.append(["SELL", p, k])
                need -= k * px
        if not extra:
            return a
        return {"farmer": a.get("farmer", ["PASS"]), "hands": a.get("hands", []),
                "market": (extra + market)[:10]}
    except Exception:
        return a


# Kaggle runs `[v for v in env.values() if callable(v)][-1]` -- the last callable by
# INSERTION order, ignoring the name. Redefining `agent` keeps its original position,
# so the helpers above would be picked instead. Delete and re-insert so `agent` is
# genuinely last.
# --- variant: keep a small cushion during the opening, instead of only reacting ---
_GUARDED = _guarded_agent


def _cushion_agent(obs):
    a = _GUARDED(obs)
    try:
        if not PG.get("cushion", 0):
            return a
        day = int(obs.get("day", 0) or 0)
        if day > PG["cushion_last_day"]:
            return a
        farm = obs["farms"][obs["player"]]
        money = float(farm["money"])
        if money >= PG["cushion_cash"]:
            return a
        market = list(a.get("market") or [])
        if len(market) >= 10:
            return a
        prices = obs["market"]["prices"]
        shed = obs["private"]["shed"]
        need = PG["cushion_cash"] - money
        added = False
        for p in sorted((q for q in shed if shed.get(q, 0) > 0 and q in prices),
                        key=lambda q: prices[q]):
            if need <= 0 or len(market) >= 10:
                break
            px = max(1, int(prices[p]))
            k = min(int(shed[p]), int(need // px) + 1, PG["max_units"])
            if k > 0:
                market.insert(0, ["SELL", p, k])
                need -= k * px
                added = True
        if not added:
            return a
        return {"farmer": a.get("farmer", ["PASS"]), "hands": a.get("hands", []),
                "market": market[:10]}
    except Exception:
        return a


PG["cushion"] = 1
PG["cushion_cash"] = 20.0
PG["cushion_last_day"] = 3

del agent
agent = _cushion_agent
