"""port/main.py + h1's selling overlay (our market model).

Generated by port2/gen.py -- do not edit by hand.

Original docstring:
Pure-Python port of ``the-35-0-tape-a-causal-shop-router``.

Exact, self-contained re-implementation of the native (C++/ctypes) policy that
shipped with that kernel:

  * ``source/policy.cpp``                    -- tape replay + route selection
  * ``source/include/six_day_budget_guard.hpp`` -- the only adaptive logic
  * ``source/include/sim.hpp``               -- enums / static data / ``fib``
  * ``submission_bridge.cpp``                -- per-seat session reset rule
  * ``_entry.py``                            -- observation packing / action unpacking

No ctypes, no local imports, and no use of ``__file__`` (Kaggle's raw-python
loader ``exec``s the submission with ``__file__`` undefined).

The two 719-turn action tapes are embedded below as zlib+base85 of the exact
space-separated text that lived in ``source/tape.inc``.
"""

import base64
import math
import zlib
from collections.abc import Mapping

# --------------------------------------------------------------------------
# sim.hpp: item space
# --------------------------------------------------------------------------
_ITEMS = (
    "WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG",
    "MILK", "WOOL", "FERTILIZER", "GOOSE", "COW", "SHEEP",
)
_PRODUCTS = _ITEMS[:9]
_CROPS = _ITEMS[:5]
_ITEM_ID = {name: index for index, name in enumerate(_ITEMS)}

N_ITEMS = 12
N_PRODUCTS = 9
N_CROPS = 5
WHEAT = 0
FERTILIZER = 8
GOOSE = 9

# sim.hpp: unit ops (index == enum Op value)
_UNIT_OPS = (
    "PASS", "NORTH", "SOUTH", "EAST", "WEST", "PICKUP", "DROP",
    "PLACE", "PLANT", "WATER", "HARVEST", "FERTILIZE", "DIG",
    "BUILD_COOP", "BUILD_PASTURE", "FEED", "COLLECT_FERTILIZER", "CARE",
)
OP_PLACE = 7
OP_PLANT = 8
OP_FERTILIZE = 11
OP_FEED = 15

# sim.hpp: market ops (index == enum MOp value)
_MARKET_OPS = ("PASS", "HIRE", "BUY_LAND", "BUY_SEED", "BUY_PRODUCT", "BUY_ANIMAL", "SELL")
M_HIRE = 1
M_BUY_LAND = 2
M_BUY_SEED = 3
M_BUY_PRODUCT = 4
M_BUY_ANIMAL = 5
M_SELL = 6

# sim.hpp: static economic data
CROP_SEED_COST = (10, 20, 50, 100, 80)          # CROPS[i].seed
ANIMAL_COST = (300, 400, 500)                    # ANIMALS[i].cost, i = item - GOOSE
LAND_PRICES = (1000, 2000, 4000)

# sim.hpp: shops, in sorted(SHOPS) order
_SHOPS = (
    "BAKERY", "BRUNCH_SPOT", "FARMERS_MARKET", "ICE_CREAM_SHOP",
    "PET_CAFE", "PIZZA_SHOP", "SMOOTHIE_SHOP", "YARN_STORE",
)
_SHOP_ID = {name: index for index, name in enumerate(_SHOPS)}
SHOP_FARMERS_MARKET = 2
SHOP_ICE_CREAM_SHOP = 3
SHOP_BAKERY = 0
SHOP_PET_CAFE = 4

# _entry.py: tile-kind packing (index == enum TileKind value)
_KIND_ID = {
    None: 0, "EMPTY": 0, "SOIL": 0, "LOCKED": 1, "WEED": 2,
    "COOP": 3, "PASTURE": 4, "PLANT": 5,
}
T_COOP = 3
T_PASTURE = 4
T_PLANT = 5

BOARD = 10
MAX_UNITS = 40
MAX_SHOP_INSTANCES = 8

# policy.cpp
K_TURNS = 719
K_ROUTES = 2
K_SEGMENT_TURNS = 72
K_DECISION_STEP = 360

# kag::Config defaults used by the policy (submission_bridge.cpp only ever
# overrides ``episode_steps``, which the policy never reads).
CFG_HIRE_MULT = 1
CFG_MAX_ORDERS = 10

# six_day_budget_guard.hpp: SixDayBudgetGuardSettings, as set by policy.cpp
GUARD_INTERVAL_TURNS = K_SEGMENT_TURNS
GUARD_MIN_UNIT_PRICE = 2
GUARD_SALES_FIRST = True
GUARD_PROTECT_STATIC_CONSUMPTION = True

# --------------------------------------------------------------------------
# source/tape.inc -- zlib + base85 of the two 719-turn tapes
# --------------------------------------------------------------------------
_TAPE_B85 = (
    "c-qZfTbAsouDsthiW~w+fX)0Tb}Ri9C_;Acy+6+Cb*fKSIZ2ESl0u<S{^U>k{U?9Q_ox2kPf"
    "pwK@~8d&TtE8zbNT&QK3R@Gu%Gq&S^54ef8?i~gYLgS|0CbucK+e}McG_`jh5%HDffqeub1E"
    "HmHXG#e|RxpU_REj|6csGjv<y0`c$!hJic?EfSH#2l)YlvXVu+8;0Yc#UCo6#`YJV3I;J^%@"
    "BSD3DL<#<dprE9Vff)w3!Pv(-n3(a$N#^t-hRJbSIjr>SKI0JYdkfd?)aq)zjy!5dR@o9w?B"
    "Tb{Y`S;dtb4dpXufI>NH+*-<#m~+Mnyo>-x*<+|Qry-Ph=N_^H>O`k(c>!fwO@$2eZh48F|_"
    "vw+>2&F}WB_BS*)zs2_7{a$tMkmYv~he!PTm;EI_f3Mrs;-)U<^Y_(dyL$iaF@bI_FVo<%O*"
    "jpA<<2Z~josGvy}Ykz=DJ+rCCPkG3a;pnSCoG+#=n?{{*R22{@{x5BilF8{#r0Q{GDI5TZQb"
    "p-%F+g+ike*C6QsTL_3pQ(cRt+j)>vq_UEseiai4Ja9ig=qtPIhn6NTWrMOYbJQY96{Y7GSw"
    "cU?7&2v#V>2;oq9VREdF7^x8X?4kpT!ZW<QW<VV?YFh<&%5Wgjd(b5?%wU(-QVUl%ESrL>x#"
    "i!>+>mWmxx%k|FFUI!O`6}SPSgg=%{A25#1|y?6o$(c<c>r^QI)*Z@(~dlI(RA?_T>+J4G;J"
    "ny+l`%{4EGbE}4TySQJOyD9T1*15BH)17slJ-Xv=)ZKQrFPXU;bwkc~BV<eWX+VEn0?zKfFV"
    "(z&qpi8!1wA*XeLw8sp<wvaJrQ?+*h6+RJ9fQ>ab-4<=22OPsh%O`bYU}BHs>_R{H&OFA%WY"
    "v*spHGp0Dw4-<DqA8CAG{o!w>T)Hr_oh2G^GPe?s4tY(pOWXTslWS^~YbMJ~mU*3NavG(0>W"
    "iXjE?<j9&SL?I)YeB^y7z=a_hIP{URku!&xJ_=4rQtE!^JCvi>+~Fpv#1Gs6xHpR(a_~_2e?"
    "bTcM^@I<cfJ(>UQVoyy|w_m0H-{Z@AxCePxg9u{W8+t6LydE_9|u&a5>F`wPrX_62ba?{L93"
    "``Cp3z>O@j4KriY&2~}2CK=4QW0UMR$gs(8n>;w&5hgOa0BJrwE<<+Ba<^&w&prT7>vg!@W@"
    "K<WoVRE%Z0;=V@WMg{l<7M0p74y$bPt>D_ci$G=F$5@X1~77LpC?P`DT<j8+k%<gxKpoTz4a"
    "+-#shD(C$0>`-sGu+eXKJiza1mU?M{;`-&fL&h0T(H~kxUs>5&WQL~S--9Wl7S1?S$!*3rI5"
    "920}v*OR@<Wbe+;noa4tp0?tJCgn3_p{6PPfq7vCGKW-W48Tc2DaK?5bOGV&+2vi8Ug-=dQ{"
    "5);T-=Q=8Qorb6S>%fxfO$KVF6D@?&hUm}a2g4^PXg=CxBdtvsW~`_nEy*^!GIVs(bCZ^vqO"
    "r~mo8V*HX0Ji{Bo>}H6?o?+EFIAu(P=;iHn^I|sOj}-!+->=sGF#Oh12eucm7Uw4gM23n$io"
    "?^qKZ$ZKomka=eYSfWr5K{J=EQ#O=;mU}c>aF;RwdR9Sgd}%u*KocEU+B+%<q?OpTB`^9VX`"
    "jSUc(MC6Vp(!};Nn(@y4oyk_73s@JI_uT8{mv&zqMo#X|iGV$+CqSHRO>V6jT8?)KLcd(R(|"
    "1fa%rr%W-19k5J*5Pm)BeDhtkm)#F%&{=$RICBH?dxp<rY+L^kt^izY}e_(e}@Gy)a709=k<"
    "P+IAxRP<4(!T*r$N_xbKA+q%s{?nFJaBljcA$+rRs)x)P^xJ|#T@q3#rt>6Gjtn#jV04$-c~"
    "<HsIvn7>pRf??0g`BZ0%sn`;cJ5`c<=+lv&$kAVjB~RC}oJgeC$s3ra_t0mlJVxMiY4<0GW7"
    "$Ft$M#%<&$6F`RUAG2b#O!8p5NbCqFT4S9x=U!F4s8NcbIJmK}RPGj+68LHkWt#{a=INn)mt"
    "kYjrq|+Rd=pe6hoGKDP70s@aGf7Q8tAEG|IEp#!pedpX}{PaS>Ud|A|l_vBy_cB&3AIZA>LG"
    "SD!uWi%u?8js~P_K7ubCI>D~A}GMT2l<MP_@$C0$^ajNHDf2Q$4-ZXjxL(NmkQ1xoos_$Gj("
    "T1m|1m6zGGS*nK;(JgdV+30@~$Lzw({9OTcXS<?^WxAt}otFLf=~?NBl7&AZw*7BP1yEQqik"
    "WsmaG2hzV!s}d(}Sa=~{R?Ph^Q4ZImQo#J%*UBcd5+TeC3qCV$j^`%?jp)Fy?ap|ac^z4Al6"
    "M-7m|#=317gGL(8$C>u84=gOw{rp;IPwkDki2;0DSMp6G7YS%%|MF_MEN&ps-yxY*aS(u@Td"
    "aRaFmn4M115r^fJ-`lGn{L0ae)T+^Atk>!PB;v<tB<j;7#=j;SrpX&YZ!Kyi^;V1hz5v2bbM"
    "cLhiMhuY=a@6hW%VAQV#TX}3iHTXZ2hxr$yT8-lyFTVMc)4_;e59lII;|*zPJW?!Y+%xi2@U"
    "?UlAmdw4S*FpyT|TmYHlt{G9!Q^Fr1QRag{D^BXcS9;vNP7tgVn~WPA3{w*yv|u8X-JaXwM^"
    "E24z-XGU=JU!FIcMv&o2EC=D<J!3qD1H(A%eGuFk+_tjWY=hO|t*vj3l{Z{AT>FnE>vXGv1T"
    "CddWs2u*0ZrN89+~pR`NhbQmE3W}`W-k?NRj>|Jj9<Z8tngdv}JPk>pW&ch-wVqoTq$pR%;("
    "nLDskPd~jm<88@VQ>V;3of?Ux+4k6=dc;*1)?jWsX*}`%HP$oB?jIP9&ygSUbZNDme`lsxBP"
    "&QPvToA$j{}HxXHbZz{dC(V^!CfvNDfcUSA2!=u+*Fr)LNFcDrm?f^69#2FcHV{gbb}Wp)0&"
    "(!POQX-(VZZ|z0YSGeIM78^#O^>hbH6T#wi`AdwfubQk;9y2Rc*rbFcSW_}O|OWc75&<wMe<"
    "=Da%h6&toQD-Ryu`Q~m=*5Qk)9X^rM2Bi}QT&$fN<Enue6OuVk>(IfGHBxTOiI^yokPz}h+@"
    "<AkLj}?$0BvyvXKV%kYP%07Q%O;Z=*|dz9sXs<dtuhc@dmfw#jE?Nu*X5VFHSbRjQ(Kx+oum"
    "Nxg}i`XV~JO0>anruu34Ut`jU{zf8sqO9m7I^`-_;AFKD>{del^0ce;F9N)v?4fZ(CHOUiz&"
    "OXsEqd%>#Jj&hIcc9~dDlA4i2EsI}o2-!iR1poRyjoB15ZOs)_5eoO!xFLX{44<lU|7TMp$V"
    "6{2aaDOB_!gw4Y-=~n4>>&?K2l|j!2fvdJ%;&WvgG1!mw#FNAYG7473tB!_IPgJ=~*M-CHfu"
    "Bs+W9%HGdHg80D(1CG(azL{Q7Z?n?u@Vc^yanhbj?V)~usQCbL7@>Gasn0hogd^kAC*p5b-O"
    "cuh_&D4?c(E-%(VVzGFiP~rR{wO9;mVj7JCQjSmS!E!cX!Lo?7#l&9If|1kJd+f>Eq>k)KSc"
    "~$&}HS0cI*Jr9#1F1MMis@Cr-0O@MM5t?KZ23;UG=U6;-0A2#*=s}h!O^^4iG4uC83=mC~I0"
    "j_Bd;Fs&M2(K~`jG3V|$?SNSaZT=tv<LE2;uAStm;!F8`_tb36zjI6ne;dDo)Uw^`~0B!!mN"
    "xtnkOES4Defv!PXVmdD~kOaAW$)z&jKWKJd6c)~@a10tRS+6P^ihgAywfT=6`*KR=RtClX--"
    "*$r5IGzTI^nT;t=2PE&nCze8WMk28VO#}lzEK<6o-msdE71Npl`k$l3rnqPMGxM_%02xBdFk"
    "2Ts?nzq!c1essyJPss{sPv%Fs!Q(ywMUTkcYOA#JfL|hmpK<+ekd-Yx+F-r9W2-gQII0Xkjj"
    "M_CglJDs{i$jp@-KOvvRdEu{byWO*NVjn+xnIu#N(`6KzHCRkosVzKW7G4e2X?wwkxnJdhw%"
    "luL~#e&ItGFRF@K|sCp)zuOnw<80}hh-omsN~cgNj;6FSqk%h5?&}_sTD?~dRQmGn~KSw%GN"
    "0}$Eo|!=V6^XOGhc?mEJFVB23%i8Gz6;O=4AjpBbYFGSipPtP-=wugqPy=59R*s(%q?>F6BK"
    "KxqYJPiybK#<pL7U3a3GT-k~5G122lqtj$wJN{YEr|ALI4C1jNX|`;sEHR<U#+0?=jRqxoNX"
    "-LfmT!BVgiy20=YQ>tMj)nM;~n$MnN8+OKrL6yf}pYGiu#Tjc2JbC+~%M#j??fT*LacjZp7^"
    "Yv1Hy6eO9;cfk6Zb)_W`v34rD9@v3<*hq_Bb-<(7B%P*CLpw^&c_pnreRz*>5=QE*ve8D9i("
    "~T$W52|;MDuMbuR7zhdaKqWZC*C8>jAjXr|CP8vV4)ln2{Bj~><$+H#w5ZbQ0Dr8@M5KiBJn"
    "ciwvnAxQ~+B}Js)Ev#qWc}makJ#GEbo7o1CKmf-x>^pDTU%C%o6w{H#;5P)I(DBXS$DS73os"
    "-7tD_(5DSPGo%eIKEI`ef<C#&$su<JsxPGG1c5<-;x^VO+{kri$<+xk1E^KZKpKYc%;Q!D<k"
    "~rMH-*>tz?97WL6kG2>zLVUZeLP-W(GuoXf-q7JgoTUyPbA<x0)m!C1I7pxR`>b>yp^V6aZr"
    "iE~ijb{MW<GK3}-nZ&{z0(_?fl8OO<Rq|irZHjIJ?LUEybd7QZ#x^pg;4O4fS1^POnr?ddK2"
    "_>FKi4dyqi-c1<;xAm*<$+sR2-|f?r_7nd;ynurw)N<4GXd9wT52F}a}X=^s%S(+OH^F#f$Q"
    "@<*KhV`zHNY&140gpm7|R58d~ih#kKk`(ud`9sYyorYp&9-hXKY``*&o$Y~&uuc~JPa<5#F$"
    "i5)I?#J8V9=_l(XCR76U4Nk^@cXJ+e3_KG}XU1iF$GB8MMj7gvKS4?PKB~r_$|){?5huQ6=b"
    "FQ6T9lc|Ihrhjo7v_@d$ssrL8oc}bXo|L-^onY)eM_ysZ9b7TJ>gUofnsB(xNOujq{+_Y~}1"
    "0kbJl^zPC@+TH}t>L-x4Xw+(P$ghGcY;`khITlJp<9CRQ_K`K6vVHXS!AkD(c0=DURnBmru4"
    "*TmKtkWZ17=>mM9RGgQu5o63c%a4@+p}ZZbd5nW7gU0J)Bhc#9fL0n8$DM>zwT%8uIozbVcY"
    "hJ<2g3q8wk~_UHqdId~PI0&GJfZBS$*1>L#7F(;Ji2NeoO^?>T4?%P$9V{Fa$~r=_|L`v204"
    "s3<2hK;bJaf6d0QQvg6GDUmmUehGvQvL7;NZUCGJivyJTbT8cPOl;hR$ZUz(zX0oM#63V_j1"
    "^PA(qQj<Xz6>5M0Dpw(6DukOA}2(dj>9YPZs9dp(Ja;c3@v*WWO5AimzjZQM)UQx=#S>OeOP"
    "c%+w1ChhY3#RF<KBDlA&vxZI58M5>HIpxeo_QyS3b%qpaX_+Zv<vRJkgb#V}iu4dOIgqGY%r"
    "93*H3>=@%-sReN3IM&uuZ6xT7%uZtWK=c6G&jJX)9gb?NTevtZ}YTU9UX{KP(oNCP>=oQ$z&"
    "#o<i;ZAGzH(us0-tM$qNxC^Y$Jt(v%d4EjbVpwbZ)Jq$cY;EJxAu+j1kuFx#T=f9O0kuJ&Ay"
    "wigrPJ_=Bs`R@f5Jv%3Yl{%<Xs2)%WPxtVrI@=DwC-KR)Wlw0kGrhARD%D&O1Fg6?8H68&8c"
    "ND{Q+G%TA))~;-B@)e{-|sBS}4UCb13D{1VPX3wp`2vP<fK5NMxJdPB9X^jm{V(h$|&#bcdw"
    ")z_23-0@YJCObEB<B&s7{eJZ~(=!ebM=S>iPqI8kHzdXeCUJo23f&gz}HP6n+^}-x8q%qc5s"
    "9BtcU6|y?!)dW#YirLQ`9yv3ls!rBZ2`xxKZHWSX)ivrrwmF3Nt%VVlIS?UH$o7F)Ri6Pb$Y"
    "WJCBDu!6!z0$VEO93x)lSW0H8E4CVat=x>lZ#w{qWf0dE*YrIv?sQ{8f3W&?VEhl<hw?oOWB"
    "2md6UQ4iihfeHilu!)|fcX|@bU7m}5h&L$*r76bZW$av}%xHj?@ql6lGAb1-$t(sy5?*E>=N"
    "NCuBoo5aUhYE@%I2m}?G~+Wo~e;Gwx>DZ&Mhe*RQ1_Q$(fa6E)QJoMks0fxSg2|j!R@vemNh"
    ";plyh)j#I|hsVtV>yl?7dDs}gGcFsB?!y4-(wIk3W=nrLKeO}`ZoRa45p*$?U61R%40N77Nq"
    "YSKqQpmegRLGtq=9K`-`HiBNot{E{^5VOFDG&pNb#g?9k#{OG6B1%1O&USy>{0ZA{ktXCn9M"
    "0szeCHR=N?I{5(#-pE6=mK1+kHS0Z&n=T1{gI$r0{rgqt+;wVl;vs5_Ugp%cJGXjxomtkCY6"
    "|Nj7<D8s}pt<e(y>!Ghdx)k!@OjMXD5q=D_0+f2PE)wEgYn=E;@19GSjEQs34iqX`1P8_fW}"
    "vb^Bc?!$gie!Xp-4z+VTljquAE>~JBF{1Y=HETZ}v~*{uUX+8)a;7d30a0chL<13%Tu?7L_3"
    "vX2s|N3iX&cGvKUu=bh0gRl%auq8cTn4{(t%;eyWG=_#2ac#H7mMTM0DQ%l`?UL%B&DWH|2G"
    "D`1pXsi}mSS>@wyn<n!0dJ%-PGuu?gq=Y{2v{g&{-hJffDO?(9q58@c$+hU-z>5qAp(TBXCU"
    "5Tq#9w|RB-|gh{ENc8{-I5j?(DirI1xKAQt?P_p#&(y{!wdNCps3q1GO2TI|@D<=?;+#bg~="
    "DZTXx%FG%{5eE|{!9a1Cl2=gCejth_@=*6h0vyN4fJz|prf6PaW*8r*44{w~UV-&4gz`f=1B"
    "V|KTfOz?>s{gyY$a}kp(Q9^^-f7l;4lWMu|x~G-OrVIiv3Mm7iH-)4bVthA-&WtqBSI#@Br7"
    "Bk?{%zh1B^J{&d_~@Z~|rVI{Bl=}&CzcSqGQaR%Bjta>ApgsHkSql2fnGCCsV!2qCz+NVkKE"
    "uxhuu#ovdrXXX7>3DhoXi6`-jC8sdyOh^1OI{4AprKx;j8V%fWo|xj9s>3;bWEO0p~MyR`_e"
    ")Th;Eq}7z?PNX~rhUNmDH!kmM0pX`E)C=)aOFfQK~_LjEByGuH{cC;+?=qSf=rshA?_><T26"
    "v5FaxF|ZPATv(e)4HIKc1AL^!RgMVEQg`m65IUobwi3lh#Am!lR$i`HNR>!ur4@$2Gb0%aTP"
    "-!}*c57p2a_^>lMK0FrBND<&rmIx%vd6%Q&9JY>cV7~fM{XWvQQsyJnR$6#=sY+GVo;$>!{m"
    "2x>DSpYUCijkDEGtz+cL}bSg%~x0^}3uXp<3Rl}_5i-eF{O&vZb7%71_3K>mYl7>n|F=>s?A"
    "~cR}Bz7Put@r7mP}l(+D{7!%0FIRb{AJqts7%kt*8tl0{Zxd|NkFAWC2r2jc%^DJKOM%=V=;"
    "M<ZA@PI$wM6S2}K2kd54KW9PfnyJ4>P@oIYv0MEK!e{zr%8XT1_pzF>n11;*nV=L4nx4eN3E"
    "0txZ8JFp))E?{3N+o|E$qXlVPC1D}lbOKY_>JU(zxp=o$V&BQCqAD{)ImV~6u(GEtGcN;jkw"
    "83;nnCz8dv(LZ70-<Lw8jPBj`vX>3O5<=sYeJ0Tyl9RhR?#BWslyDi!H#_TjNZDGS{flrv$("
    "g;HC<$IRF%6rQotM(IQunQ>nRRFrY@M!*PvkteuppE$^7KgW9wxlTz|$p09a78khm3E>SK>d"
    "h%`^vR@_|#SQN>|B5-wpX7o4>Wz9%M7pv&`|5k0qHU65v93ZC=2tgrV_*+eyJmJfkwhq^X2j"
    "q`nFnRHDt}fzvU?Nv$uGO=@bU-hQhPF_ff`Utx~NxoxF?swkTE(fRE$Y+C1Onol`G<<dV^VG"
    "Yz!noa?~R%0IQ63l`|n624W}u&4lxeVZ<enLdsw}fU5PxE_P|n15^zJrz(J#@4EdJ;W2&suC"
    "jki=g*Xj;C_7Ln3-c`StTXlh*Dx42(|khRu3=?qSOFfEHl>(QDSc)13(5)W*U|I4RMyRGVPB"
    "-Y#-A{$doOIayG2cWPYf5JY0BYQ<$`p^7_;Sn=ocp%9tgbb!VqmrQ(u_XeKD(4&;DWN+`M<E"
    "p^=064M2G2$rssW7K_tuJEYDuCGMJH{(Je_WBaGRtVWIor}3K6&=6}$};b`M9=>e$~qSZSN1"
    "<onuKD|GhT7XL>(1=%U|OabA_mkHm}*XZqUb&L*B5G5^9@`Sw1>ZK(Uae9Kv~xDLfz-gAH5H"
    "CVfzAUEaxAcr?15!zLIK^STrIl+vy7$3r3R#Q2{sQ*jL5K5zOU0o+``D(Er%*j#U+LVuM8Sb"
    "P56cODB6hvtL+mEtr;^bdj!=^>r6&rh8pM=$H@!(yt?B>pIs*;I8#%LD>jcAnX^Awz|}B|bz"
    "u$xECLfP7$&r%rQ2AOP=Py~nR-f04uJ-d1I=zq&jynL1z^Wk5+tliY55CCs8xp*}cC?VAVA7"
    "bTh(-LjwslN)=e$(pf?a!j#NPoWY?j6PRnsVOhlv2*Z3vp}7}D65anWLBbHKQFo+4TsP|glz"
    "MBMQU=*+^(qpakru}X-D1o!0T>BUX^-u+*qAKkLi|Yw}oTW^w8c5<(d~9Pd~Z`AJRXlkwR2-"
    "L;#`oOxep|+h2~1PBtZDPnR<sma+GOqd3T2!A0aOpfFG+!NdIxYFthkJ(C*JGI>4c7-XDZm1"
    "f^$VIez1*;mx{LhtS&rbqJ=&eNZwp}Pr2zlRUr4y9?Hg_2lj$9j0aYit1<F*ujeQi$htmXIg"
    "})UfsQ7sqm)w`U_;r^oIm>p&~y^q@UG0Odtk_OD##sY7liCE08*!{}Qsguc&W^A*co!(K=!#"
    ";xR8p}H`FsQ*nRd4<tCuVKLfeJ<T;&w~sFlcNB|%<gu9m{fn^;R15&ERO!h@OS*1vAO-mWBn"
    "T@WSUAX+SFY>ZEQ!TJ-rcNnsLdd;64rAlUOY!XtK=g_9N%N(!c?$q=!_01jA(p8F<<L(Pt3$"
    "@s$;7_dBXTYONpQ#7?~YG9$3NesLc9oO4-aNc&G%e)m+K-#D^Q&5Bn5u>pH}q#0bql=)Kz*;"
    "JsD?OK#n@Tf=)BRe#Zc*Db^Vp?1Kqc2qXyR#ayVp2F`Y5B4x3V%1_Vzu{yymWD>04Nu6z0{Q"
    "!`Xc(IgbJ|W-4yUSCBhznh~RE`+DSQJ40qT~BylW+NpN-I-r3s~!c0<DHnoN~TVtm^gJgDpo"
    "*qIxhdnMNk~bYH5Fb1-OyDfC!Q>(XBqFW#6bmmU{N#q?{GoqT%p<T>3<e02zp&orkn7V>eJK"
    "k?%iDw+Tv5DGd7?rNK&6!n`3U559X9lT969?Ea+&MsOWZslM<|-_Y$Bu>h!LM;;FZ~!G42S!"
    "jx3oaLGCx4CMpA!01{^(1p@LSGq5sRIU-SAqtXRTB%&dL-=|OvgVLBl1<4KGPyJ|dB(%s?2!"
    "7nb6b}d*)=W^b!_3ryr-My6&p_e|jsk%i5fF3JS+0}?hgUVnKoSFEkTmo<fybWlxXDfnr;+;"
    "ec;jS<ZKNku>x#=oq}Q_z)T4X>Q9|{4Hx_l=a^A28oVk1eoA1MU0a?>PDZ7VK(Now0MVWJKG"
    "yCHLjGdJG8$zEjBwbu0|COn45i)<%C6>Q1?)s{OlfLTlZ~=maK<4^_zvpWG3&VtZ*!7}>!FY"
    "dQ{IDjq4}o~-4D<(h4EqNR1450Y73IPRt&k==m7My%Q6y{YqfF`t7?JPU0J`uABMQssxj~V="
    "Ylg)t8BI~NO%#F>(IRNXy)z0EgMS5Xt<f(6X_EVt9r`22GNAGz0rP&e9xb5-n6kggxpERA01"
    "ejMpQ8HJx&r!n>_LNaB{GF9hbz<opM-=vsE~N3{O4jVcOlDA2$iz2r?vgzc&9q;qcSx}cLz{"
    "&3%>mvR#)6ggg7P2k9udY$2uSSp!m@4*Nd5W&|Id$%;k`rYsdSQ^Z(`15z!;UzCN`ctojW;l"
    "?UrvcS?T!W)J1385lg{$AA1`ztQHzmA78e!`E2O`WI^7r3dnjwoe~k%omuCo%-Dw2|AmF8b3"
    "86i6>}VT*!{5ctVP{>v!-WK<p@P1>C39Ole4^AK$zG1%Ha>1UvjH+J1KU!}zImRlO7#6>q=a"
    "t{WLR1(J%}Cn4cH=XpfmyZ>gru4CWZAHUa??F`>Lg9qz$UHrW|jpxCG1i#n!Z+X71zq}4P@8"
    "wfNx4cex@63$Zudo}jz%hcxYG#-P>{fer?^hv1V(rQARdNN%E0Sy3&;9N9x?L?KO4vVtUtPA"
    "V_um47S(yfxZNkZ0pE}=EBCt}Lt^n=b=Sv6++g;HguPFaujDIl?{T~@4{lOLaC{jC|t+4W`+"
    "O5LMzG|TNZ=3)b_DZxf$rau0-Qb7-N>_azrIFaROb3ldgVZQ&w^JdsIXe~BhrLb#Adt1ISRv"
    "NZGb$F481me87HgF`r?*|AQ4D^aNQL8%?P#Bs&k+wNF5?;#^IjCfjk&MrI6(N>c@!BJn#jCF"
    "On>722Ga*eci&(wuxF#A%6oM<*HN}%>831`M@4lI%j5#(Fll10s|1kh^My++3zg?N3dvZ^Zq"
    ")-X(A-VI$y?*lQDVpJ(E+IlP{Gh<khfz2{Ov*s`SucAmw>ao?@JxPfCOUk?={EfwC~3frQ?3"
    "u<(>$UP&B}$T`!<4k|v+kEAG@Y#GEc{LqR^)#%p++;|oz|<2-%GwdZTR+qb3HcSbc)b$V-eT"
    "ZoM8OI;(t;XEPrys$=sq}GxzOj0t>rbKbN)|gn5f%Vqj<HTq(PF=}c+0|uKw%eCjMZL_k5}c"
    "B>PLVLeh<}XBkWO1o?)iL<J_(VqM^Q=YMds;|OT2dyjiuy@d0Ogr=jgoZcH5O&*k;;wf8SYs"
    "Wsj?=)L?tF{1hl<T_OW#dvYR^EwEI%V4HnxLVw^!7P&CsuizQyC@(!6%1kQXnPe_oIoV`D`N"
    "5b-exQuDJLEmdV|xAUb0XNTD`i*C9+5}CU0&Py5FICn%yo=kY77|Q=<WA4_~~sf)f9JqnTKq"
    "V){|L%mg!29vms=+Cx?)J_pA^@yYJ}lBNAtB8y)*Cnv~Nk<+k}S*o%J7H|O@4yj-y@$x04#$"
    ";P;LEBAlrmYG6{H4*(Tg<~^df3ROW_!EhVm(Cwnf5K3ywKSBrEoUe4#Vke&>;1EBA7Egs{RO"
    "eEpB%je`YrXz@~f5n;T-=Q=8Qorb6S>%fxfO$KVF6D@?&gedjEQ?8I<&`gzw|^*ZZDEbIFeE"
    "lg}$CMwHXH9ZvuAcg6T69cQi%1hWJ7wUgJiQ0SEi(aYQEgm68Au_fTZ?GGdFg~^Qk{Ye3lp+"
    "X^yb^0XAx%5bNeEV!?N<FMkq|RSEy1Cdgp1&WzRYTIAr?zbmiKWaF$yKV6GU)@bt;6IJ(3jD"
    "{C6?{;JtkXq&gt7yt)Kp>*Qq0~O~h`q%Fhz$dDT!h;s~(s2Up$CLVja5JNOQk((oVVIyzH&#"
    "K%D0JAf6@>lRW)Xb<k;6GJZJlBQijWP6(cC<!<mxk3)lcAftFcUS;JUET$MUhhYVQ#N@%?v%"
    "WYeF}(=`(B7aD${|*7##}e#|jRe?z8G4$=S`9^r||(PNq|`zo1}uct(1(Yw`H8#~bD^Rfb^L"
    "^Kw4b*<vcG*}!+IB=^v#BRz#;JKmC~>sU^os85HI>Wlk5^jRv85%^r%{YffM4dfi=&r;IoLK"
    "0*7Dzb``TJ!n+jU|Qx%zDK18oFHLV7jwK6BIYfEI4-L!k?pzb1Nua7yvNp1MW1OQA74(*lfP"
    "o;W;1M`C!#-L=FpH9Df$iUJf0Q-P_A~t`XClJ|iGzP*!Y~iOEqCd_?@#b6(46NOCkD<pO61v"
    "Mip96H4WpJ;+yV#4nX8#ie-7*vZ?Gj)B6dEiq(J!5O4;@mt14jZ70F>L_$f%OexV`j^n7A8P"
    "V5jtIv@RDDsx;+IQ^noo%fMX%*bfwUKEOlo5hbBDr$2<uVC{hSUF=Ij)_m>CM2U<?aYUR0kD"
    "8LQ#7vdOGO2s5Bm<YwF)&rb*%!4=b2Uuuyrs4J7a(`dwmlv*5uJLYw0WMZ#%ipm_d{E<#kHr"
    "SO1zL{E)wa4|`t?O>>WIW<PcDsfZ78Y{Yp0I+T1$61D_S6_&QhyXvwKWZL=KAB&p5=vO0+_%"
    "-{*1?a&Q8Gf0n#{wRdZ0oPiBh3nX3Bra6(+bS;G=fy-RdD39=uw;g+Kee>wUR>hV?_^GdPO6"
    "7WvSII&q&ABm#1M<J7AnL2nSR{}<=OQ2`cDXg=5^yF|i7bTeyz!4ZuNwc{6AkfsY8mwL1!vH"
    "L-UQ!4j;yC-~+W{*}*TvkAIG+dzcPJtKnGuw=8fcOH{(g|kgc|6F)wn9OIC|RqAh<KQZKcfs"
    "HZ{EAt*vj3l{Z{AT>Fa>{g_{s!{6k&9$-hE)art~8Rywb?l@uvk``}%5+0&0d-)HeEt9iffh"
    "b4{RqtpEyGcIC>6Se8Af{>I;ZUa4S&0;0BEj;8rByT%6d#dB);nldabp#Bpp0#5dR9JdoNL>"
    "DRrd5x+4tbCSyV2FVE_LJ+bl;z&1Mo#I-cd<!KK`<=zZ9fOJQ2vpoRH&Lu$QkbwRcUZYbNa^"
    "DfM%8@wQy)}#)FilD@Y(VZZ|z0YSG-Rdj&5+DJIIH0WPoYHZ+#|L#N#km)~d{_scW~M@B>w%"
    "Ef(;-nqgKLaB7WuMaJG1iO@ttq(24x+-sM_HZIc;Elzs1GcxiPL9h%q6V^9Od-N%RHI#TBsw"
    "Bq2R0NQ#?<E!{7lu+bmTj+`LKdWDf{XS)7J<=e^SU*<c1BdZ5W_$|F`tllr@Gs}m-PBy%Z2e"
    "I9sudvRnj<2tTbTg?}AH!Ffdu6LjxcV;}b^XknJ%qBesR7i->V0?rokrwI!))NBFTD_T&LI|"
    "%3xLi((LV_{Yb2t7E37nI`P&idqJcV0wwrjGYN9pIPwSbXlr+q^+6OSw9+prI#?2B?0ERW}A"
    "JS*XmF9P5aywCb^tmiI#|%V+6&H-uD9hy~Y9tOz$8yp3c8*?W7Y(!$IK$U>qXst3CE_|EkC;"
    "hPQB`H{XCXoSV1oh2XkgzIuZjqo=Xkx;%shjYw$GSj1`TtMpx|9d0PLke2>3B+D0-(n&7v5D"
    "_&BN?R+36h^NHJ;>P}@4!SHmG;mVj7JCQjSmS!E!cX!Lo?7#l&9If|1kJhv6npc4xRU%h+is"
    "BfUseImaODX>RWPox8)JcL+4{6~iAy#rvKRMlEu5GY%%Y|*^(7GKRq|-zZ0UkZTk|)5G=>Hz"
    "#!Ypeo7&Aj_lG*Vt<C+kK-x`*Z%@a9Ym_pTefza<d$<4KWI%tdu^H?I;*#Ub43$rrrXr6dPG"
    "Qe*w23uEL=WTCEz>VoE1Mg5k_`u`(Si821m;UNp%Xpp%aDx&n6I}5;x<5aBt2wIPnuyMGVi6"
    "<gg~QSTpcivuDbyEzRH&GnWpCy*3BkphbP2=f|1qWc3EHsa<&XQY2t{aL_hH$SwgBvs7=L!h"
    "@R9xH?My05b1!%(r5@Ts67T*<9!B!cZ6ooRuj%vTm;PKW434g0poO{2sE5bmw`L~x1USnbC^"
    "PnvfRU&c81Qk|Xq|+uQz3DaKax*sg5{MZ7W+OBBM)=u-l?aC>Y2QNjMuY%Sig>pp~aD?Qb{1"
    "TvgJzil!Au2mC@rDGO0$zxt3VSE8&F_mRey%s)u#bPuTb-k-BWKPMJAQ-G@F8>(p5~N-3}Oe"
    "%TXKd~ZbM7Pu6LiOZ9T%Oo(QAm@F9VWZFobJwl8TMvTjUxZmYI>$3mT45v3+um)htw(Lse3{"
    "VYkTnk@4c^ZC?2WaaPtyaa8HwMgA^X&>{My;atnG9!s7yAV=7j)dmT!BVgiy20=YQ>tMj)nI"
    "S;Z~umDyyj1k`fHEC?D~uBh*rVFyJC%WVz{<2X&Ch|78QbL-uR+XG_Byd(OoZr=lg2okLKSR"
    "fJr%iZHu^Ii^hmxR7Kr|6<vDhWX?(Ak786`)m7RNMJXC?8)!<#o_!!kg~Zf3-4GwGuzB#)p4"
    "qBIcPbl*GsXN?ahYP`)p9XJQe~9R%v;iLeNixjrDgSSg}NyiB=mByG$IY&rFOjFA+-4-#9xP"
    "C>~$fs$`>ivA0BL#cma9Ie-I(1+?qc(P$&wgxeMm@esVcNVS%o&j-Sh22EBRP<$!8)_uwAD_"
    "PuC5P|O?*LRL!16%@O$wOi)dBrjfcyXe@@C1)R<1dZE;jEqtW#!1>%|S)@t``};4+1pA>%Hm"
    "5A3Fuc`QJgEuaUP&PhMyK7ch{PND@dE?19I7$;;F-2suEGF8mip~r8f0X(S}0oBN0J%z4kCq"
    "n)?VX^cvE`cv;@^mv71o>W=P(Ga{6iKG;o>6rlWQ}t&susW6CJeW}FaiQ~?8^r>W|N0d7#M9"
    "*zdt_gMA?RoHZUMb#ZHcM*2WI?88sQU0>G#o<1T&&t&VrFFjNcZcad&!djn$7BLq0~$U*NU%"
    "kv#}AXza`H@6qL#{Tc@`MR5P4XX7kG|6{o?r#jYGHX6oSgrSv6;O%N6)r0j;LC}%>O$36opD"
    "&@^W3cq#?gf)eL5yb0F;vhFs#?1wTle(LoI(b;vXY=F)b8A$6NNYnRbdRIL8{p=2;HVax*(~"
    "RfHdK?zP<@6htJ=><kiS-^(oBTK#NMns3*}=u8fN6os5Siy_NR(S-%8jCdwSXNyMHyiaSopi"
    "XUoLtZF2m689R&i+q@#nQt~t}Hd;Jp<Gg9jqsaxfQCmsIO1}eqN4K`mRl8AsVX^%hn~x<=J1"
    "otDhXN%Li?XS2u;N#j>zz@_h|@cDVjA97;l-OJR@A^?d6N1uHnO4NmV(wQDa4$Ymh93iCvJl"
    "yDwDaCQ#a%;uj6w9RI{+ae!N56T0yy~489v-)A36S}w*$Hw>iLjI&McQCYI1L|JUaIhMYJDi"
    "1{CStiGLb97VbOnMl+Q$2_Um&zb0(hBMkdgtH9~TSJ7&?DoU#HPCT0@O2+PZtVb6<a%D}{N2"
    "cIX>vY1o?pDPL@apBag09YVk5$i2X}<jFso@+M#JNva5)b?*iz9u>!IZ#3Hv9{s}1{P*4k^l"
    ">YM*TC!B`UiD2OUOqcx}m59I*s9ALKG^X-w9wqhD^wtL>OWTEZD9K3mjQfywUs#_K?fvUp5d"
    "wF{QkD3+aiO3JaWs7)tPgb#gwQdQhO<0uI;B`AFc|Btm;G579`PfkF~<yJUDq;_AcueUq{NG"
    "CSS4U~)Y=N8EJN!4o{~`ToxW>xPdO+d5T+u-9_bNy66n@;!A5*@e8Eg*_`7Gzzw5)j4eMY=}"
    "x_OT?fOdQTPXPShcEVPdh}!*YtZJ80S6XyKapW2@b3p+5cx7(eYQ)_s(ymzh*nypgERVw>Jh"
    "F`0u#XWZFolDS^Qzz$QGrye~WM92bw!jSV(Qi|>4B9yhM;e7ppi3CQKF0yYWdyKmfNo}BC)>"
    "$yUKf7+;;>J=r`5`nLmO%irXU?8P-Z*+%EZ8*LvqwHrYdK|4(gQ@pfyMwi5Yups&aN*4N&xP"
    "(ux<<;gZk|lp5Z0^avpM;->gQtqw8Rf^#fbdur8~s_dZuo_*ADnGrySd1w#T=c|P85k0}@AE"
    "G>XQygXEF>V^*}?xrHKt_wqhd;<S3eTjPH?@IveqmcVX23qVx<dEI1G@c>Nocy4)W@pby2zY"
    "?us8sI*#9oc6V3~dVkXy_|F^CDK+=nDoo=u@(ELz<>vkUjJX_x?vSWa=UW8%ltW6P|Xae1IS"
    "Hv--4<922?f)E%~FwTcD=)7SI%#?*g40}FPImF9U>hAHx(-{4lHP%V3MxaB`A1bT*yvC>-eR"
    "KCv9u{ATTg6uZ>?b1g1y+Gm9Z<Yk-8o`jiB4nlh16NWQ>af~e77$JkiDVJ5Yb`eor=t~co@%"
    "-Mi4rC6n!AjZaRugDHI9F6_)kVD^)I3*rovSkg=vN;{{0uDnU7Yp@J`s9V7>GqCv&irBtLd7"
    "2Km2dGfECU6JHDlZDl+G54d-wPJtiQj}rh)uat<`k@{Y^`lE656(md8Gv=-3dox(=DMTqHau"
    "eIFM!1t=A#%(G-C6a>KF^9^}&I$1{f%g&#20`MOvYoQz0n#$GnLsqchbj9MQhaxtAyILVw6k"
    "&fg+Kc%v*sBaiM&7Ledh=k|m2@Jx|z<ie~NT|l88(>DgR@9w-a8l@^&bXu39fN||W3uTTRZ5"
    "gODwf}fY7D@~V5($(Ia=V}1dR`-hktv{+qDn;XacC^K$teshac$OF;tW}5#grYHzZn`rz(R>"
    "BFh1*~IQvy*!<Q4_GvrL*H;XJthyWpG35a)uyvU%3bakG<3S5g$p4&pIcBtIJ=;0+#71e1WO"
    "Hii8q&8RRZC!vxGJtpr<?2}9Ussq{{taAFOxA%_qg$V#O#Hc=h>MZ^%Z2KaDgg{h^Q`equig"
    "al(kT+)m|+V~gv*<{a|QGuCC4cPDCC7#V7&{WG>p!`;YZO^Z~ggtmpBAliQ8}iBMFl3xN<e("
    "igcD5OOycaey+?@?6X556oyWK#@VTF${dwP`Jc{;@qG|N*VivE#}}Yc62$0VHo|gwkV04kzG"
    "L4>&%=s%rgLV6k;)JVmoW8t_YR)k8k6q9nFN3qYM%fxM%{D~&_ZF)%+eMz+EIZ(Q+m;;qtmt"
    "6)v$JQX*si;`W+jz3r&Q15?4ZOHgyQt$IvnP3Pt?{Ef9x&X(5I&aHLJ4z#CXRj$l%=37lb|x"
    "KN0egzp*eu!}bWtH8q=OG*A2b}^MB>~snbUI>x9dE`_~5p{OzV9IJ|7?5Ferl8VJS%4vowdf"
    "#q-obi_6Zaz=(HKB70s-}*69dR{EaS+EOwB@q7TRSmO}V@_BN+<26*cPE6l#VClQMpj47p&X"
    "Q5ucUP=Tn-SR$lTQ1^yPt7MmeXko(up*|ieNb}hk_~KLszN{=WfAh8M=t^;WDl>y5GsG4k>&"
    "=KxG>r(J0^e>X?Y`dWgI7JLrY{l?O_hn_#tBAB;Eh5?6PKi+DoczC+F69g(T&6o1f|v69SA!"
    "pt_u|kaI6gAFVoJy&T(?j!k~TMl0*od#J8mft_V;mP5>`hF29%c>;nD>$TlV~p5!48`GmTB!"
    "o0&oAddH1dYvUv5>B7AU1j@lFaM)M^0QuvC?=`EdbDJ!b$U4;DE)6(kHZ&8h_Bs&{m5~lTx;"
    "<DX<WgqULA~=CkjE?3g-J{R)qy9!4msUwm3wYA$qD-6jr*QW#(l-E)t06Q9lKLX0L8|xZ;@+"
    "pH`pbND=R&uob8=@2N)!2V8P_P{_!_oMn&Rj*Bh8)m!6Cfil;q(WeB!6X2%0bDmZdC<T|5>H"
    "f^f7pfsrwwO6AJqGmD8p{u5YRfz3>>xc4WhHw4%tM9eY2V}ysY{d#lAgR<hwPV$MsdUY%)es"
    "J@+Wy<zj~vd6H$Nc&c6C~p=g_=SnsM3k@nS%+F~IDT4PD7H9#ViQZr(3qRfMWb};Wdy%53p`"
    "{b8hxOe#j;odzN(tu#RC0*33!P=8cVaOO<>Lez`m54Qg=$a_NqtyqDje&Y;9`y(dz$#;D;!F"
    "sK(AqcVMF!*Q!(&i#T(Oe56IVFv7yALKX3DOB8V`CgA6JCO^y$0G{w<w9Q?4TmdaukJE6XY="
    "0Y{V)<3On0=dgN!VGyMT;9{A%W{48|yQ^2Up%{GE3FnhiVi8|XS!Fa68}5Wjh}d#eAVL`@#~"
    "UgRLWwtq`Gq$#U>5*RLw#!`oONfXR;Buk-qMmjiSW=`z+0{O8PVNoshTCG3-k~yT_?w=+XY6"
    "*9?-57Qd3A50<qVZuscD>e(6+P3urxgfy)u&D|3DWo&PCRMs}iBcC!C9X%gxw&v?ZlJ9t$1E"
    "q{$y%oU<j9e%T&(V&lUmYG)~=Weqx%SR^)XohK$L!@L3+zPEdk+5dEI@yMW)iNMLIBQ9BsX-"
    "(d67#wf`jnCptE8b2cVhfcm#H`gZ=W}<gaB?XU={Qje(X=TP<5_K1FSv&?wfZ7h(q&1|4MNh"
    "D_65TttO;~=J{LfECI@}hC*ftQWB>)u+Y*ECZ%fUIY=v3YDQX^pZ9r*(*ckVY?IV!ZU_Y6j`"
    ")ezv%kn;bZ@J&x%<Qml52R&`+CllgiE%iJT;I25G&3dgOk+0dEk8Ug3B_cg4*!HOQ;jTz&yW"
    "}jd}{zSxiuPvFv!st)+`JRZteFGZ<y{v6)kvSU)cs1`UVM!c<@0i#n5Q=8ix0j~o7!AtPY%f"
    "!7UxM#R9qgPGMC^q6jW3P-P(B3{@b3+0*@98W*G2M^LV?uA811X5g~>}9a+FGofvo05rADrG"
    "n<WBUR}age)$D>D(9^w5A{O1`yA-)y;6&a7urLs}-U=NyBK^Q+SAn=CA3XDIuM8b|2efWs(E"
    "J>fk4DH^)_NOUg>M*Gk3w%LfpIy=_G^NscJhJaHi>cn!qk;_9D2KhuCt(>w?xj2^VygeJ)Iz"
    "4tjSrb<wrw3Iu1e6zH*}q#jutRPpCE08*!{}Qsguc&W^OZ<LH%e8exD`>lvNo|Wf~fyZC3%I"
    ">JFj8EL5~#|SMQp;mPk|$5s1`wzkV;OB9zcyoSxo$!`~wz=sU#D_47AO$TXE&w5dUR+Sra5C"
    "*SET$3YK+`!t9>vsy~fr<mF8N6!DV0^&TTJ}M2497l;HE5~Uzkct+Po)^l7``VwQ*7_k%?8M"
    "72GXlFSeP*a|$fL%@yqDtT-!_iyQ@`I8Ky1LC8cA#*t_`0u$fg#rNFWng;amdon1!ohWQPV4"
    "Z+LiAOlxa@^r!%c$^e(i7Ohih`LZPne>dX-8apVFdmN%zd7&`=uJ9)dgQCi;4m@f^2(x5sOh"
    "j-uJnf_$FoqFH&`IO6V$95ZIp4tE`PxE85T;D#Z??uxdj`qu{yaT|cn*79NF=XL61MulIwRM"
    "0Zfq!?f8?Jr?d%)tHhZh{(1I!E5!fmQ0|d!mSnqPk^=YWSl!c<@Z9)yMC|;;MQ6UGQ(#nN=1"
    "oFAEZVqoo&c1}4v~nn)uuT*}(X6x5nS4q}e3F4zW@E+>dZV%nGE0KoZ#Yd<1}Xt0&b}02pEC"
    "n1qm?5P)io+zz(gV%B_5$~k3dQEEUHs17k_krV(c~{_;CkQJRoRTGeN};LBUo>2b*x7fy5OY"
    "1p+l9Am*mCTqz4K65*#n5(8t9@a{T+$DZ-H>Gcbzk^1v^<79|!4<S_Ripxc$*Ru`OqkI8TLi"
    "Kv<*p6=5{?|$7@&RnV59bABO_eiidPI}^q*<z();gzn6{7_hn-TXngg#+Ny0}FCD^uShWd5d"
    "0EPr9#^+8VYK^X&Q+6#fq^#y;=)%q8P3H7j>LkWZN{=oQQeO?~|@z5FQ5AYcF4;Ti7+TAG1g"
    "%MgIO?E0d^}EYL2#MyDN&NsL@;w`dyB4MiPj58&GO+uu85XN#G)2)iQ3y&zi=YwrZf;Qk4VG"
    "FJ_(Uy&fco%!IxhM`22@@oVBU|`qb0NeQ}#DGS56`X05|5?6F=!}lEpCC7}y8ctZ{`J;FFMW"
    "2Ne>}l>c0;<t}6y3ZYUq_O!M?sBJaSIk~6#vAp>-7Y(Z`ZY4sT66Hs|GuUID4}DO4X!q;IOg"
    "!j-(_rQjv`_j{2LB)ZSL_l"
)


# --------------------------------------------------------------------------
# Tape decoding (policy.cpp::decode_action)
# --------------------------------------------------------------------------
def _i16(value):
    """static_cast<std::int16_t>."""
    value &= 0xFFFF
    return value - 0x10000 if value >= 0x8000 else value


def _u8(value):
    """static_cast<std::uint8_t>."""
    return value & 0xFF


def _decode_action(encoded):
    values = [int(token) for token in encoded.split()]
    if len(values) < 2:
        raise RuntimeError("invalid encoded tape action counts")
    n_units, n_orders = values[0], values[1]
    if not (0 <= n_units <= MAX_UNITS) or not (0 <= n_orders <= 16):
        raise RuntimeError("invalid encoded tape action counts")
    cursor = 2
    units = []
    for _ in range(n_units):
        op, arg, quantity = values[cursor], values[cursor + 1], values[cursor + 2]
        cursor += 3
        units.append((_u8(op), _u8(arg), _i16(quantity)))
    orders = []
    for _ in range(n_orders):
        op, item, quantity = values[cursor], values[cursor + 1], values[cursor + 2]
        cursor += 3
        orders.append((_u8(op), _u8(item), quantity))
    if cursor != len(values):
        raise RuntimeError("trailing encoded tape value")
    return (n_units, units, n_orders, orders)


# kag::Action{} -- the value-initialised default: one unit, {OP_PASS, 0, 1}.
_DEFAULT_ACTION = (1, [(0, 0, 1)], 0, [])


def _load_tapes():
    text = zlib.decompress(base64.b85decode(_TAPE_B85)).decode("ascii")
    routes = text.split("\x00")
    if len(routes) != K_ROUTES:
        raise RuntimeError("tape blob route count mismatch")
    tapes = []
    for route in routes:
        lines = route.split("\n")
        if len(lines) != K_TURNS:
            raise RuntimeError("tape blob turn count mismatch")
        tapes.append([_decode_action(line) for line in lines])
    return tapes


_TAPES = _load_tapes()


# --------------------------------------------------------------------------
# sim.hpp helpers
# --------------------------------------------------------------------------
def _fib(n):
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def _is_animal(item):
    return GOOSE <= item < N_ITEMS


# --------------------------------------------------------------------------
# _entry.py observation reader.  The native build packed the whole observation
# into a C struct; the policy only ever reads the fields extracted here.
# --------------------------------------------------------------------------
def _read(value, key, default=None):
    if isinstance(value, Mapping):
        return value.get(key, default)
    getter = getattr(value, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(value, key, default)


def _count(mapping, name):
    """_fill_counts, one entry."""
    if not mapping:
        return 0
    return int(_read(mapping, name, 0) or 0)


def _packed_tile_kind_and_animal(tile):
    """_entry.py::_fill_tile -> (kind, has_animal, what)."""
    if tile is None:
        return 0, False, 0
    if isinstance(tile, str):
        return _KIND_ID.get(tile, 0), False, 0
    kind = _read(tile, "kind")
    crop = _read(tile, "crop")
    animal = _read(tile, "animal")
    if kind == "PLANT" or crop:
        return _KIND_ID["PLANT"], False, (_ITEM_ID[str(crop)] if crop else 0)
    if animal is not None:
        return _KIND_ID.get(kind, _KIND_ID["PASTURE"]), True, _ITEM_ID[str(animal)]
    return _KIND_ID.get(kind, 0), False, 0


class _StateView(object):
    """The subset of kag::State that this policy actually consults."""

    __slots__ = ("step", "n_shops", "shops", "prices", "money", "n_quadrants",
                 "hires_today", "shed", "n_units", "inv", "rival_tiles",
                 "market_inventory")

    def __init__(self, observation, seat):
        step = int(_read(observation, "step", 0) or 0)
        self.step = step

        market = _read(observation, "market", {}) or {}
        price_map = _read(market, "prices", {}) or {}
        self.prices = [_count(price_map, name) for name in _PRODUCTS]
        inv_map = _read(market, "inventory", {}) or {}
        self.market_inventory = [_count(inv_map, name) for name in _ITEMS]

        town = _read(observation, "town", {}) or {}
        shops = list(_read(town, "unlocked_shops", []) or [])
        n_shops = min(len(shops), MAX_SHOP_INSTANCES)
        self.n_shops = max(0, min(n_shops, MAX_SHOP_INSTANCES))
        self.shops = [_SHOP_ID[str(shop)] for shop in shops[:MAX_SHOP_INSTANCES]]

        farms = list(_read(observation, "farms", []) or [])
        if len(farms) != 2:
            raise ValueError("ShopForge needs exactly two public farms")

        own = farms[seat]
        self.money = float(_read(own, "money", 0) or 0)
        positions = [_read(own, "farmer", [0, 0]), *list(_read(own, "hands", []) or [])]
        self.n_units = max(1, min(len(positions), MAX_UNITS))
        self.n_quadrants = max(0, min(
            len(list(_read(own, "unlocked_quadrants", []) or [])), 4))
        self.hires_today = int(_read(own, "hires_today", 0) or 0)

        private = _read(observation, "private", {}) or {}
        shed_map = _read(private, "shed", {}) or {}
        self.shed = [_i16(_count(shed_map, name)) for name in _ITEMS]
        inventories = list(_read(private, "inventories", []) or [])
        self.inv = [
            [_i16(_count(carried or {}, name)) for name in _ITEMS]
            for carried in inventories[:MAX_UNITS]
        ]

        self.rival_tiles = farms[1 - seat]

    # policy.cpp::animal_tiles
    def rival_animal_tiles(self, animal):
        result = 0
        rows = list(_read(self.rival_tiles, "tiles", []) or [])
        for row in rows[:BOARD]:
            for tile in list(row or [])[:BOARD]:
                kind, has_animal, what = _packed_tile_kind_and_animal(tile)
                if (kind == T_COOP or kind == T_PASTURE) and has_animal and what == animal:
                    result += 1
        return result

    # policy.cpp::plant_tiles, applied to the rival farm
    def rival_plant_tiles(self):
        result = 0
        rows = list(_read(self.rival_tiles, "tiles", []) or [])
        for row in rows[:BOARD]:
            for tile in list(row or [])[:BOARD]:
                kind, _has, _what = _packed_tile_kind_and_animal(tile)
                if kind == T_PLANT:
                    result += 1
        return result

    # six_day_budget_guard.hpp::owned_in_hands
    def owned_in_hands(self, item):
        result = 0
        for unit in range(min(self.n_units, MAX_UNITS)):
            if unit < len(self.inv):
                result += max(0, self.inv[unit][item])
        return result


# --------------------------------------------------------------------------
# policy.cpp::choose_observed_tail
# --------------------------------------------------------------------------
def _choose_observed_tail(state, seat=0):
    # policy.cpp::select_route as published 2026-09-03 -- this tape's own selector,
    # which is NOT the one the earlier tape used.
    if state.n_shops >= 1:
        if (state.shops[0] == SHOP_BAKERY and
                float(state.market_inventory[FERTILIZER]) <= 10232.5):
            return True
        if (state.shops[0] == SHOP_PET_CAFE and
                float(state.rival_plant_tiles()) <= 64.5):
            return True
    return False


# --------------------------------------------------------------------------
# six_day_budget_guard.hpp::calculate_six_day_requirements
# --------------------------------------------------------------------------
def _planned_quantity(quantity):
    return max(1, quantity)


def _calculate_six_day_requirements(state, tape, start, end):
    purchase_budget = 0.0
    starting_seeds = [0] * N_CROPS
    starting_items = [0] * N_ITEMS
    seed_balance = [0] * N_CROPS
    item_balance = [0] * N_ITEMS
    hires_by_day = [0] * 6
    quadrants = state.n_quadrants

    for step in range(start, end):
        n_units, units, n_orders, orders = (
            tape[step] if 0 <= step < K_TURNS else _DEFAULT_ACTION)
        for index in range(n_units):
            op, arg, n = units[index]
            quantity = _planned_quantity(n)
            if op == OP_PLANT and arg < N_CROPS:
                seed_balance[arg] -= 1
                if -seed_balance[arg] > starting_seeds[arg]:
                    starting_seeds[arg] = -seed_balance[arg]
            elif op == OP_FEED:
                item_balance[WHEAT] -= 1
                if -item_balance[WHEAT] > starting_items[WHEAT]:
                    starting_items[WHEAT] = -item_balance[WHEAT]
            elif op == OP_FERTILIZE:
                item_balance[FERTILIZER] -= 1
                if -item_balance[FERTILIZER] > starting_items[FERTILIZER]:
                    starting_items[FERTILIZER] = -item_balance[FERTILIZER]
            elif op == OP_PLACE and arg < N_ITEMS:
                item_balance[arg] -= quantity
                if -item_balance[arg] > starting_items[arg]:
                    starting_items[arg] = -item_balance[arg]
        for index in range(n_orders):
            op, item, n = orders[index]
            quantity = _planned_quantity(n)
            if op == M_HIRE:
                day = min(5, max(0, (step - start) // 24))
                hires_by_day[day] += 1
            elif op == M_BUY_LAND:
                extra = quadrants - 1
                if 0 <= extra < 3:
                    purchase_budget += LAND_PRICES[extra]
                    quadrants += 1
            elif op == M_BUY_SEED and item < N_CROPS:
                purchase_budget += CROP_SEED_COST[item] * quantity
                seed_balance[item] += quantity
            elif op == M_BUY_PRODUCT and (item == WHEAT or item == FERTILIZER):
                purchase_budget += state.prices[item] * quantity
                item_balance[item] += quantity
            elif op == M_BUY_ANIMAL and _is_animal(item):
                purchase_budget += ANIMAL_COST[item - GOOSE] * quantity
                item_balance[item] += quantity

    for day in range(len(hires_by_day)):
        first_hire = state.hires_today if day == 0 else 0
        for index in range(hires_by_day[day]):
            purchase_budget += CFG_HIRE_MULT * _fib(first_hire + index)

    return purchase_budget, starting_seeds, starting_items


# --------------------------------------------------------------------------
# six_day_budget_guard.hpp::apply_six_day_budget_guard
# --------------------------------------------------------------------------
def _existing_sale(orders, n_orders, item):
    result = 0
    for index in range(n_orders):
        op, order_item, n = orders[index]
        if op == M_SELL and order_item == item and n > 0:
            result += n
    return result


def _add_budget_sale(orders, item, quantity):
    """Returns (ok, new_n_orders); mutates ``orders`` in place."""
    if quantity <= 0:
        return True
    for index in range(len(orders)):
        op, order_item, n = orders[index]
        if op == M_SELL and order_item == item:
            orders[index] = (op, order_item, n + quantity)
            return True
    limit = max(0, min(16, CFG_MAX_ORDERS))
    if len(orders) >= limit:
        return False
    orders.append((M_SELL, _u8(item), quantity))
    return True


def _budget_sales_first(orders):
    sells = [o for o in orders if o[0] == M_SELL]
    rest = [o for o in orders if o[0] != M_SELL]
    orders[:] = sells + rest


def _apply_six_day_budget_guard(state, action, requirements):
    n_units, units, n_orders, orders = action
    if (state.step < 0 or GUARD_INTERVAL_TURNS <= 0 or
            state.step % GUARD_INTERVAL_TURNS != 0):
        return action
    purchase_budget, _starting_seeds, starting_items = requirements

    orders = list(orders)  # kag::Action result = input;

    available_cash = state.money
    for item in range(N_PRODUCTS):
        sold = min(max(0, state.shed[item]),
                   _existing_sale(orders, len(orders), item))
        available_cash += sold * state.prices[item]
    shortfall = purchase_budget - available_cash
    if shortfall <= 0.0:
        return action

    candidates = []
    for item in range(N_PRODUCTS):
        price = state.prices[item]
        if price < GUARD_MIN_UNIT_PRICE:
            continue
        protected_total = starting_items[item] if GUARD_PROTECT_STATIC_CONSUMPTION else 0
        protected_shed = max(0, protected_total - state.owned_in_hands(item))
        available = max(0, state.shed[item] - protected_shed -
                        _existing_sale(orders, len(orders), item))
        if available > 0:
            candidates.append((item, available, price))
    # std::stable_sort by (price desc, item asc); candidates were appended in
    # ascending item order, so the item key is already satisfied.
    candidates.sort(key=lambda c: -c[2])

    added = 0
    for item, quantity_available, price in candidates:
        if shortfall <= 0.0:
            break
        # static_cast<int>(std::ceil(shortfall / price)); shortfall > 0 and
        # price >= 2, so ceil() >= 1 and the truncating cast is a no-op.
        needed = int(math.ceil(shortfall / price))
        quantity = min(quantity_available, needed)
        if not _add_budget_sale(orders, item, quantity):
            continue
        shortfall -= float(quantity * price)
        added += 1
    if added > 0 and GUARD_SALES_FIRST:
        _budget_sales_first(orders)
    return (n_units, units, len(orders), orders)


# --------------------------------------------------------------------------
# policy.cpp::Context  +  submission_bridge.cpp::Session
# --------------------------------------------------------------------------
class _Context(object):
    __slots__ = ("selected_route", "protect")

    def __init__(self):
        self.selected_route = 0
        self.protect = {}

    def action_for(self, step):
        if step < 0 or step >= K_TURNS:
            return _DEFAULT_ACTION
        return _TAPES[self.selected_route][step]

    def act(self, state, seat):
        if state.step < 0 or state.step >= K_TURNS:
            self.protect = {}
            return _DEFAULT_ACTION
        if state.step == 0:
            self.selected_route = 0
        if state.step == K_DECISION_STEP:
            self.selected_route = 1 if _choose_observed_tail(state) else 0

        action = self.action_for(state.step)
        if state.step % K_SEGMENT_TURNS != 0:
            return action
        end = min(K_TURNS, state.step + K_SEGMENT_TURNS)
        requirements = _calculate_six_day_requirements(
            state, _TAPES[self.selected_route], state.step, end)
        self.protect = {
            _ITEMS[i]: max(0, requirements[2][i] - state.owned_in_hands(i))
            for i in range(N_PRODUCTS) if requirements[2][i] > 0
        }
        return _apply_six_day_budget_guard(state, action, requirements)


_SESSION_CONTEXT = [None, None]
_SESSION_LAST_STEP = [-1, -1]


# --------------------------------------------------------------------------
# _entry.py action unpacking
# --------------------------------------------------------------------------
def _unit_order(op, arg, quantity):
    name = _UNIT_OPS[op] if 0 <= op < len(_UNIT_OPS) else "PASS"
    if name in ("PLANT", "PICKUP", "PLACE"):
        item = _ITEMS[arg] if 0 <= arg < len(_ITEMS) else _ITEMS[0]
        return [name, item] if quantity == 1 else [name, item, int(quantity)]
    return [name]


def _market_order(op, item, quantity):
    name = _MARKET_OPS[op] if 0 <= op < len(_MARKET_OPS) else "PASS"
    if name == "PASS":
        return None
    if name in ("HIRE", "BUY_LAND"):
        return [name]
    item_name = _ITEMS[item] if 0 <= item < len(_ITEMS) else _ITEMS[0]
    return [name, item_name, int(quantity)]


def _unpack_action(action):
    """submission_bridge.cpp::pack_action followed by _entry.py::_unpack_action."""
    raw_units, units, raw_orders, orders = action
    n_units = max(1, min(raw_units, MAX_UNITS))
    # pack_action zeroes the struct first, so slots the tape did not fill read
    # back as kag::UnitAction defaults ({OP_PASS, 0, 1}) for units[0] when the
    # tape declared n_units == 0, and as zeros beyond that.
    packed = []
    for unit in range(n_units):
        if unit < len(units):
            packed.append(units[unit])
        elif unit == 0:
            packed.append((0, 0, 1))
        else:
            packed.append((0, 0, 0))
    farmer = _unit_order(*packed[0])
    hands = [_unit_order(*packed[index]) for index in range(1, n_units)]
    market = []
    for index in range(max(0, min(raw_orders, 16))):
        order = _market_order(*orders[index])
        if order is not None:
            market.append(order)
    return {"farmer": farmer, "hands": hands, "market": market}


# ==========================================================================
# h1's selling overlay: our market model, re-pointed at this tape's shed.
#
# It only ever ADDS units to a SELL order (or appends one when a free order
# slot exists), and books what it pulled forward as debt repaid out of the
# tape's own later SELL orders.  The tape's order ORDER is never changed and
# nothing is ever pushed off the 10-slot cliff.
# ==========================================================================
_OV_CROPS = {
    "WHEAT":      {"myd": 4,  "interval": 0, "maxy": 6, "ongoing": False},
    "CARROT":     {"myd": 3,  "interval": 0, "maxy": 4, "ongoing": False},
    "TOMATO":     {"first": 8,  "myd": 8,  "interval": 1, "maxy": 4, "ongoing": True},
    "STRAWBERRY": {"first": 10, "myd": 10, "interval": 2, "maxy": 4, "ongoing": True},
    "MELON":      {"myd": 12, "interval": 0, "maxy": 6, "ongoing": False},
}
_OV_ANIMALS = {
    "GOOSE": {"interval": 1, "held": 4, "product": "EGG"},
    "COW":   {"interval": 2, "held": 6, "product": "MILK"},
    "SHEEP": {"interval": 3, "held": 6, "product": "WOOL"},
}
_OV_PRODUCTS = list(_PRODUCTS)
_OV_MARKET = {
    "WHEAT":      {"base":  25, "T": 400, "bf": "sqrt",   "bt": 0.80, "af": "log",    "at": 0.20},
    "CARROT":     {"base":  35, "T": 450, "bf": "hinge",  "bt": 1.00, "af": "sqrt",   "at": 0.70},
    "TOMATO":     {"base":  60, "T": 200, "bf": "hinge",  "bt": 0.40, "af": "sqrt",   "at": 0.60},
    "STRAWBERRY": {"base": 120, "T": 100, "bf": "sqrt",   "bt": 0.70, "af": "linear", "at": 1.60},
    "MELON":      {"base": 250, "T": 300, "bf": "log",    "bt": 0.20, "af": "sq",     "at": 3.60},
    "EGG":        {"base":  50, "T": 332, "bf": "hinge",  "bt": 0.40, "af": "log",    "at": 0.20},
    "MILK":       {"base": 160, "T": 122, "bf": "sqrt",   "bt": 0.60, "af": "linear", "at": 1.60},
    "WOOL":       {"base": 200, "T": 105, "bf": "log",    "bt": 0.20, "af": "sq",     "at": 3.20},
    "FERTILIZER": {"base": 100, "T": 200, "bf": "linear", "bt": 0.40, "af": "linear", "at": 0.40},
}
_OV_SHOPS = {
    "BAKERY":         ["EGG", "WHEAT"],
    "PIZZA_SHOP":     ["MILK", "TOMATO", "WHEAT"],
    "BRUNCH_SPOT":    ["EGG", "WHEAT", "STRAWBERRY"],
    "YARN_STORE":     ["WOOL"],
    "ICE_CREAM_SHOP": ["STRAWBERRY", "MILK", "WHEAT"],
    "PET_CAFE":       ["CARROT"],
    "SMOOTHIE_SHOP":  ["STRAWBERRY", "MILK"],
    "FARMERS_MARKET": ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY"],
}
_OV_PULL = {p: 0.0 for p in _OV_PRODUCTS}
for _shop, _prods in _OV_SHOPS.items():
    _m = 2.0 if len(_prods) == 1 else 1.0
    for _p in _prods:
        _OV_PULL[_p] += _m / len(_OV_SHOPS)
_OV_SHOP_INTERVAL = 3
_OV_MAX_SHOPS = 8
_OV_TICKS_PER_DAY = 6
_OV_I0 = 10000
_OV_HINGE_GAIN = 8.0
_OV_LAST_DAY = 29

# --------------------------------------------------------------------------
# Tunable surface (module level so tune.py / port2/sweep.py can sweep it).
# The defaults below reproduce port/main.py action-for-action.
# --------------------------------------------------------------------------
P = dict(
    # --- h1 selling overlay -------------------------------------------------
    mode="model",           # 'off' | 'greedy' | 'lookahead' | 'model'
    # Tuned 2026-09-04 by MIRROR MARGIN against the submitted build, because the ladder is a
    # monoculture of near-mirror matches decided by 1-2% of bank. Minimal contributing set only
    # (mode, fert_keep, guard_protect, wheat_start); the rest of the sweep's picks ablated out as
    # no-ops. Holdout seeds: +2,616 margin, 64W-0L.
    items=["STRAWBERRY", "MILK", "WOOL", "FERTILIZER", "MELON", "CARROT", "TOMATO", "EGG"],
    lookahead=40,           # turns of the tape's own schedule to pull forward
    wheat=1,                # 1 -> also manage WHEAT (animal feed: keep a reserve)
    wheat_days=1.0,
    wheat_start=450,
    fert_keep=5,
    start_step=0,
    price_gate=0.0,
    hold_gain=0.0,
    sell_bias_glut=2.2,
    sell_bias_tight=2.0,
    hinge_meter=0.5,
    shed_target=88,
    unlock_trust=1.0,
    opp_weight=0.85,
    opp_mirror=0.7,
    mine_w=0.7,
    horizon_days=0.6,
    tranche=99,
    drain_gate=4,
    window_cap=24,
    win4=[0, 4, 3, 2],
    hold_horizon=0.2,
    opp_press=0.0,
    endgame_day=30,
    guard_protect=0,        # 1 -> honour the guard's static consumption reserve
)



def _ov_shape(func, x, T):
    if x < 0.0:
        x = 0.0
    if func == "linear":
        return x
    if func == "sq":
        return x * x
    if func == "sqrt":
        return math.sqrt(x)
    if func == "log":
        return math.log(1.0 + x)
    if func == "hinge":
        if not T or T <= 0:
            return x
        u = x / T
        d = u - 1.0
        return u + _OV_HINGE_GAIN * (d * d if d > 0 else 0.0)
    return x


def _ov_price(item, inv):
    p = _OV_MARKET[item]
    base, T = p["base"], p["T"]
    if inv < _OV_I0:
        amp = p["bt"] * base / _ov_shape(p["bf"], T, T)
        price = base + amp * _ov_shape(p["bf"], _OV_I0 - inv, T)
    else:
        amp = p["at"] * base / _ov_shape(p["af"], T, T)
        price = base - amp * _ov_shape(p["af"], inv - _OV_I0, T)
    v = int(round(price))
    return 1 if v < 1 else v


# _OV_CUM[route][item][t] = units of `item` this tape sells over steps 0..t-1.
_OV_CUM = []
for _tape in _TAPES:
    _sched = {p: [0] * K_TURNS for p in _OV_PRODUCTS}
    for _s in range(K_TURNS):
        _nu, _units, _no, _orders = _tape[_s]
        for _i in range(_no):
            _op, _it, _n = _orders[_i]
            if _op == M_SELL and 0 <= _it < N_PRODUCTS:
                _sched[_ITEMS[_it]][_s] += max(0, _n)
    _cum = {}
    for _p in _OV_PRODUCTS:
        _run = 0
        _c = [0] * (K_TURNS + 1)
        for _s in range(K_TURNS):
            _c[_s] = _run
            _run += _sched[_p][_s]
        _c[K_TURNS] = _run
        _cum[_p] = _c
    _OV_CUM.append(_cum)


def _sched_window(route, item, lo, hi):
    """Units of `item` the tape sells over steps lo..hi inclusive."""
    lo = max(0, lo)
    hi = min(K_TURNS - 1, hi)
    if hi < lo:
        return 0
    c = _OV_CUM[route][item]
    return c[hi + 1] - c[lo]


def _pickup_reserve(action, item):
    reserve = 0
    for order in [action.get("farmer", ["PASS"]), *list(action.get("hands") or [])]:
        if (isinstance(order, (list, tuple)) and len(order) >= 2
                and order[0] == "PICKUP" and order[1] == item):
            try:
                reserve += max(0, int(order[2])) if len(order) >= 3 else 1
            except (TypeError, ValueError):
                reserve += 1
    return reserve


def _town_demand_now(shops, item, step):
    demand = 1 if item != "FERTILIZER" and step % 24 == 0 else 0
    if step % 4 != 0:
        return demand
    for shop in shops:
        products = _OV_SHOPS.get(shop, ())
        if item in products:
            demand += 2 if len(products) == 1 else 1
    return demand


class _Overlay(object):
    def __init__(self):
        self.reset(0)

    def reset(self, step):
        self.last_step = step
        self.debt = {}
        self.sold_today = {}
        self.day = -1
        self.opp_pipe = {p: 0.0 for p in _OV_PRODUCTS}

    # ------------------------------------------------------------- observation
    def observe(self, obs, step):
        me = int(_read(obs, "player", 0) or 0)
        farms = list(_read(obs, "farms", []) or [])
        self.me = me
        self.farm = farms[me] if me < len(farms) else {}
        priv = _read(obs, "private", {}) or {}
        self.shed = dict(_read(priv, "shed", {}) or {})
        self.invs = list(_read(priv, "inventories", []) or [])
        market = _read(obs, "market", {}) or {}
        self.inv = dict(_read(market, "inventory", {}) or {})
        self.price = dict(_read(market, "prices", {}) or {})
        town = _read(obs, "town", {}) or {}
        self.shops = list(_read(town, "unlocked_shops", []) or [])
        self.day = step // 24
        self.hour = step % 24
        self.day_left = _OV_LAST_DAY - self.day
        self.drain = self.drain_rates(self.shops)
        self.n_animals = 0
        self.pipeline = {p: 0.0 for p in _OV_PRODUCTS}
        for row in (_read(self.farm, "tiles", []) or []):
            for t in row or []:
                if not isinstance(t, dict):
                    continue
                if t.get("kind") == "PLANT":
                    self.pipeline[t["crop"]] += self.plant_future(t)
                elif "animal" in t:
                    self.n_animals += 1
                    a = _OV_ANIMALS[t["animal"]]
                    rem = max(0, self.day_left - 1)
                    per = min(1 + a["interval"], a["held"]) / a["interval"]
                    self.pipeline[a["product"]] += t["yield_units"] + rem * per
                    self.pipeline["FERTILIZER"] += rem
        for p in _OV_PRODUCTS:
            self.pipeline[p] += self.shed.get(p, 0) + self.carried(p)
        if step % 6 == 0 or self.opp_pipe is None:
            self.opp_pipe = self.scan_opponent(farms[1 - me] if len(farms) > 1 else {})

    def carried(self, p):
        return sum(iv.get(p, 0) for iv in self.invs)

    def plant_future(self, t):
        cd = _OV_CROPS[t["crop"]]
        age = self.day - t["planted_day"]
        if not cd["ongoing"]:
            room = cd["maxy"] - t["yield_units"]
            last = min(cd["myd"], age + self.day_left)
            days = max(0, last - max(age, (cd["myd"] + 1) // 2) + 1)
            return t["yield_units"] + min(room, days)
        k = age - cd["first"]
        done = (k // cd["interval"] + 1) if k >= 0 else 0
        left = max(0, cd["maxy"] - done)
        left = min(left, self.day_left // max(1, cd["interval"]) + 1)
        return t["yield_units"] + left * 1.5

    def scan_opponent(self, farm):
        pipe = {p: 0.0 for p in _OV_PRODUCTS}
        for row in (_read(farm, "tiles", []) or []):
            for t in row or []:
                if not isinstance(t, dict):
                    continue
                if t.get("kind") == "PLANT":
                    pipe[t["crop"]] += self.plant_future(t)
                elif "animal" in t:
                    a = _OV_ANIMALS[t["animal"]]
                    rem = max(0, self.day_left - 1)
                    per = min(1 + a["interval"], a["held"]) / a["interval"]
                    pipe[a["product"]] += t["yield_units"] + rem * per
                    pipe["FERTILIZER"] += rem
        return pipe

    # ------------------------------------------------------------ market model
    def drain_rates(self, shops):
        d = {p: 0.0 for p in _OV_PRODUCTS}
        for shop in shops:
            prods = _OV_SHOPS.get(shop)
            if not prods:
                continue
            mult = 2.0 if len(prods) == 1 else 1.0
            for p in prods:
                d[p] += mult * 6.0
        for p in _OV_PRODUCTS:
            if p != "FERTILIZER":
                d[p] += 1.0
        return d

    def mean_drain(self, item, days_ahead):
        n = int(days_ahead)
        if n <= 0:
            return self.drain[item]
        base = 1.0 if item != "FERTILIZER" else 0.0
        known = self.drain[item] - base
        n_now = len(self.shops)
        tot = 0.0
        for t in range(self.day, self.day + n + 1):
            future = max(0, min(_OV_MAX_SHOPS, (t + 1) // _OV_SHOP_INTERVAL) - n_now)
            tot += known + base + future * _OV_TICKS_PER_DAY * _OV_PULL[item] * P["unlock_trust"]
        return tot / (n + 1)

    def forecast(self, item, days_ahead, extra=0.0):
        d = self.mean_drain(item, days_ahead)
        return _ov_price(item, self.inv[item] - d * days_ahead + extra)

    def supply(self, item, horizon=None):
        if horizon is None or self.day_left <= 0:
            scale = 1.0
        else:
            scale = min(1.0, float(horizon) / max(1.0, self.day_left))
        mine = self.pipeline[item] * scale * P["mine_w"]
        theirs = max(self.opp_pipe[item] * scale, mine * P["opp_mirror"])
        return mine + theirs * P["opp_weight"]

    # ------------------------------------------------------------------ policy
    def model_q(self, item, avail):
        horizon = max(1, self.day_left + 1)
        total = max(avail, self.pipeline[item])
        q = total / horizon
        q *= P["sell_bias_glut"] if total > self.drain[item] * horizon else P["sell_bias_tight"]
        if _OV_MARKET[item]["bf"] == "hinge" and self.inv[item] < _OV_I0:
            q *= P["hinge_meter"]
        q = int(math.ceil(q)) - self.sold_today.get(item, 0)
        shed_total = sum(max(0, v) for k, v in self.shed.items() if k in _OV_PRODUCTS)
        carried_total = sum(sum(v for k, v in iv.items() if k in _OV_PRODUCTS) for iv in self.invs)
        overflow = shed_total + carried_total - P["shed_target"]
        if overflow > 0:
            q = max(q, min(avail, int(math.ceil(overflow * avail / max(1, shed_total)))))
        return max(0, q)

    def window(self, item, step):
        g = int(P["drain_gate"])
        k = int(P["lookahead"])
        if g == 0:
            return k
        if g == 1:
            return 0 if _town_demand_now(self.shops, item, step) > 0 else k
        if g == 4:
            return min(k, int(P["win4"][step % 4]))
        if g == 2:
            free = (4 - (step % 4)) % 4
            return min(k, free)
        shop = 0.0
        for s in self.shops:
            prods = _OV_SHOPS.get(s)
            if prods and item in prods:
                shop += 2.0 if len(prods) == 1 else 1.0
        cap = int(P["window_cap"])
        for d in range(0, cap + 1):
            s = step + d
            pull = shop if s % 4 == 0 else 0.0
            if item != "FERTILIZER" and s % 24 == 0:
                pull += 1.0
            if pull > 0:
                return min(k, d)
        return min(k, cap)

    def hold(self, item):
        spot = float(self.price.get(item, 0) or 0)
        if spot <= 0:
            return False
        base = _OV_MARKET[item]["base"]
        if P["price_gate"] > 0 and spot < base * P["price_gate"]:
            return True
        if P["hold_gain"] > 0:
            h = float(P["hold_horizon"])
            nxt = self.forecast(item, h, extra=self.supply(item, h) * P["opp_press"])
            if (nxt - spot) / spot > P["hold_gain"]:
                return True
        return False

    def __call__(self, action, obs, step, route, protect):
        self.last_step = step
        if P["mode"] == "off" or step < int(P["start_step"]):
            return action
        self.observe(obs, step)
        if self.hour == 0:
            self.sold_today = {}

        market = [list(o) for o in (action.get("market") or [])]

        # 1. Repay what we pulled forward out of the tape's own later orders.
        #    Anything still owed after this turn is forgiven: the tape's sell
        #    quantities are aspirational, so a carried ledger would choke real
        #    sales later.
        if self.debt:
            kept = []
            for o in market:
                if len(o) >= 3 and o[0] == "SELL" and self.debt.get(o[1], 0) > 0:
                    try:
                        n = max(0, int(o[2]))
                    except (TypeError, ValueError):
                        n = 0
                    cut = min(n, self.debt[o[1]])
                    self.debt[o[1]] -= cut
                    n -= cut
                    if n <= 0:
                        continue
                    o = [o[0], o[1], n]
                kept.append(o)
            market = kept
            self.debt = {}

        items = [i for i in P["items"] if i in _OV_PRODUCTS]
        if P["wheat"] and step >= int(P["wheat_start"]):
            items = items + ["WHEAT"]
        endgame = self.day >= int(P["endgame_day"])

        extra = {}
        for item in items:
            stock = max(0, int(self.shed.get(item, 0) or 0))
            reserve = _pickup_reserve(action, item)
            if item == "WHEAT":
                reserve += int(self.n_animals * P["wheat_days"])
            elif item == "FERTILIZER":
                reserve += int(P["fert_keep"])
            if P["guard_protect"]:
                reserve += protect.get(item, 0)
            already = sum(max(0, int(o[2])) for o in market
                          if len(o) >= 3 and o[0] == "SELL" and o[1] == item)
            surplus = stock - reserve - already
            if surplus <= 0:
                continue
            if endgame:
                extra[item] = surplus
                continue
            if P["mode"] == "greedy":
                want = surplus
            else:
                k = self.window(item, step)
                if k <= 0:
                    continue
                want = _sched_window(route, item, step + 1, step + k)
                if P["mode"] == "model":
                    want = max(want, self.model_q(item, surplus))
            want = min(surplus, want, int(P["tranche"]))
            if want <= 0:
                continue
            if self.hold(item):
                continue
            extra[item] = want
            self.debt[item] = self.debt.get(item, 0) + want

        # 2. Merge into the existing order for that item, else append -- but only
        #    while a free slot exists.  Never reorder, never push a tape order
        #    off the 10-slot cliff.
        for item, q in extra.items():
            hit = None
            for o in market:
                if len(o) >= 3 and o[0] == "SELL" and o[1] == item:
                    hit = o
                    break
            if hit is not None:
                hit[2] = max(0, int(hit[2])) + q
            elif len(market) < CFG_MAX_ORDERS:
                market.append(["SELL", item, int(q)])
            else:
                self.debt[item] = max(0, self.debt.get(item, 0) - q)
        action["market"] = market
        return action


_OVERLAYS = [_Overlay(), _Overlay()]


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------
def agent(observation, configuration=None):
    seat = int(_read(observation, "player", 0) or 0)
    if seat < 0 or seat > 1:
        raise RuntimeError("ShopForge native policy failed")
    state = _StateView(observation, seat)

    # submission_bridge.cpp::kag_submission_act session-reset rule.
    if (_SESSION_CONTEXT[seat] is None or state.step == 0 or
            state.step < _SESSION_LAST_STEP[seat]):
        _SESSION_CONTEXT[seat] = _Context()
        _SESSION_LAST_STEP[seat] = -1

    context = _SESSION_CONTEXT[seat]
    action = context.act(state, seat)
    _SESSION_LAST_STEP[seat] = state.step
    unpacked = _unpack_action(action)
    if P["mode"] == "off":
        return unpacked
    overlay = _OVERLAYS[seat]
    if state.step == 0 or state.step < overlay.last_step:
        overlay.reset(state.step)
    try:
        return overlay(unpacked, observation, state.step,
                       context.selected_route, context.protect)
    except Exception:
        return unpacked


# ==========================================================================
# Survival override -- see NOTES.md. When the morning hires silently fail for
# want of cash the tape keeps running a 12-hand script with one farmer: nothing
# is watered or fed, every crop is a weed within two days, the livestock starves
# and the game ends at a bank of 0. Measured on real ladder replays, this trigger
# fires in exactly the games that ended at zero and in ZERO turns across healthy
# games, so it is inert except where the game is already lost.
# ==========================================================================
PS = dict(enabled=1, max_hands=0, from_day=1, from_hour=3)


def _dist(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _step_toward(pos, goal):
    dx, dy = goal[0] - pos[0], goal[1] - pos[1]
    if abs(dx) >= abs(dy):
        if dx > 0:
            return ["EAST"]
        if dx < 0:
            return ["WEST"]
    if dy > 0:
        return ["SOUTH"]
    if dy < 0:
        return ["NORTH"]
    return ["PASS"]


def survival_actions(obs):
    """Return unit actions that keep the farm alive, or None if not needed."""
    if not PS["enabled"]:
        return None
    day = int(obs.get("day", 0) or 0)
    if day < PS["from_day"]:
        return None
    # hour 0 of every day legitimately shows 0 hands: the hires have not landed yet.
    # Only treat an empty crew as a failure once the morning hire window has passed.
    if int(obs.get("hour", 0) or 0) < PS["from_hour"]:
        return None
    me = obs["player"]
    farm = obs["farms"][me]
    hands = farm.get("hands", []) or []
    if len(hands) > PS["max_hands"]:
        return None                      # the tape has the crew it expects

    tiles = farm["tiles"]
    n = len(tiles)
    half = n // 2
    shed_tiles = {(half - 1, half - 1), (half, half - 1),
                  (half - 1, half), (half, half)}
    invs = obs["private"]["inventories"]
    shed = obs["private"]["shed"]

    jobs = []                            # (priority, x, y, op)
    for y in range(n):
        for x in range(n):
            t = tiles[y][x]
            if not isinstance(t, dict):
                continue
            if "animal" in t:
                if not t["fed_today"]:
                    jobs.append((0, x, y, "FEED"))
                if not t["cared_today"]:
                    jobs.append((2, x, y, "CARE"))
                if t["yield_units"] > 0:
                    jobs.append((3, x, y, "HARVEST"))
                if t["fertilizer_available"]:
                    jobs.append((4, x, y, "COLLECT_FERTILIZER"))
            elif t.get("kind") == "PLANT":
                # one unwatered day already banked: water today or it becomes a weed
                if not t["watered_today"] and t["consecutive_unwatered"] >= 1:
                    jobs.append((1, x, y, "WATER"))

    units = [list(farm["farmer"])] + [list(h) for h in hands]
    acts = []
    taken = set()
    for i, pos in enumerate(units):
        inv = invs[i] if i < len(invs) else {}
        best = None
        for j in jobs:
            pr, x, y, op = j
            if (x, y, op) in taken:
                continue
            if op == "FEED" and inv.get("WHEAT", 0) <= 0:
                continue
            d = _dist(pos, (x, y))
            score = (pr, d)
            if best is None or score < best[0]:
                best = (score, j)
        # no feed on hand but animals are hungry: fetch wheat from the shed
        if best is None or (best[1][3] == "FEED" and inv.get("WHEAT", 0) <= 0):
            if (any(j[3] == "FEED" for j in jobs) and inv.get("WHEAT", 0) <= 0
                    and shed.get("WHEAT", 0) > 0):
                if tuple(pos) in shed_tiles:
                    acts.append(["PICKUP", "WHEAT", min(8, shed["WHEAT"])])
                else:
                    goal = (min(max(pos[0], half - 1), half),
                            min(max(pos[1], half - 1), half))
                    acts.append(_step_toward(pos, goal))
                continue
        if best is None:
            acts.append(["PASS"])
            continue
        _, (pr, x, y, op) = best
        taken.add((x, y, op))
        acts.append([op] if tuple(pos) == (x, y) else _step_toward(pos, (x, y)))
    return acts


_BASE_AGENT = agent


def _survive_agent(observation, configuration=None):
    a = _BASE_AGENT(observation, configuration)
    try:
        acts = survival_actions(observation)
        if acts is None:
            return a
        return {"farmer": acts[0], "hands": acts[1:], "market": a.get("market") or []}
    except Exception:
        return a


# Kaggle selects the LAST callable by insertion order, ignoring the name.

# --- layer 6: sell from earlier slots than the opponent ----------------------
SO = dict(enabled=1)

# typical size of an opponent's burst into the shared market; 10/30/60 all measure positive, 30 best
_BURST = 30
_I0 = 10000
try:
    from kaggle_environments.envs.kaggriculture.kaggriculture import (
        MARKET_PARAMS as _MARKET_PARAMS, market_price as _price_fn)
except Exception:
    _MARKET_PARAMS, _price_fn = None, None

# how violently each product's price collapses as inventory rises (sq > linear > sqrt > log)
_STEEPNESS = {"MELON": 0, "WOOL": 1, "MILK": 2, "STRAWBERRY": 3, "TOMATO": 4,
              "CARROT": 5, "FERTILIZER": 6, "EGG": 7, "WHEAT": 8}


def reorder(market, prices=None, inventory=None):
    """Hoist SELLs to the front, most money-at-risk first.

    Ordering by live value-at-risk (quantity x current price) beats the static steepness table by
    +1,565 on holdout seeds (43W-5L): it puts the order we stand to lose the most on into the
    earliest slot, and it adapts as prices move instead of assuming a fixed ranking.
    """
    if not SO["enabled"] or not market:
        return market
    sells, rest = [], []
    for o in market:
        (sells if (o and o[0] == "SELL") else rest).append(o)
    if not sells:
        return market
    if prices and inventory:
        # Rank by the dollars we lose by conceding the earliest slot, not by raw value.
        # Being second costs qty x (price_now - price_after_their_burst), and that gap depends on
        # the curve: MILK/WOOL/STRAWBERRY halve after 31-42 surplus units while WHEAT and EGG barely
        # move, so a thin product deserves the early slot even at a lower headline value.
        # Measured against value-at-risk ordering: +729 on holdout seeds, 44W-4L.
        def impact(o):
            item = o[1] if len(o) > 1 else None
            qty = float(o[2]) if len(o) > 2 else 1.0
            params = _MARKET_PARAMS.get(item) if _MARKET_PARAMS else None
            now = float(prices.get(item, 0) or 0)
            if not params or not _price_fn:
                return -(now * qty)
            inv0 = int(inventory.get(item, _I0) or _I0)
            later = float(_price_fn(item, inv0 + _BURST))
            return -(qty * max(0.0, now - later))
        sells.sort(key=impact)
    elif prices:
        def at_risk(o):
            px = float(prices.get(o[1], 0) or 0) if len(o) > 1 else 0.0
            qty = float(o[2]) if len(o) > 2 else 1.0
            return -(px * qty)
        sells.sort(key=at_risk)
    else:
        sells.sort(key=lambda o: _STEEPNESS.get(o[1] if len(o) > 1 else "", 9))
    return sells + rest


_TUNED_AGENT = _survive_agent


def _slot_agent(observation, configuration=None):
    a = _TUNED_AGENT(observation, configuration)
    try:
        mkt = observation.get("market") or {}
        return {"farmer": a.get("farmer", ["PASS"]), "hands": a.get("hands") or [],
                "market": reorder(list(a.get("market") or []),
                                  mkt.get("prices") or {}, mkt.get("inventory") or {})[:10]}
    except Exception:
        return a



# --- layer 7: tape patches found by search -----------------------------------
# Found by hill-climbing directly on the action tape (`tapesearch.py`, ~3,400 mutations), scored by
# mirror margin. Each of these confirmed positive individually but below the accept threshold; every
# one is a late-game planting edit (steps 476-669, i.e. days 20-28), where the tape plants crops that
# can no longer pay for themselves. Stacked, they measure **+211 to +221 across three disjoint seed
# sets** (60W-4L, 60W-4L, 63W-1L).
_TAPE_PATCHES = (
    (0, 661, 6, 8, 0),
    (0, 664, 4, 8, 0),
    (0, 608, 9, 8, 2),
    (0, 608, 9, 8, 3),
    (1, 661, 6, 8, 0),
    (1, 669, 7, 8, 0),
    (1, 664, 4, 8, 0),
    (0, 476, 9, 10, 0),
)

for _r, _s, _u, _op, _arg in _TAPE_PATCHES:
    _nu, _units, _no, _orders = _TAPES[_r][_s]
    if _u < len(_units):
        _units = list(_units)
        _units[_u] = (_op, _arg, _units[_u][2])
        _TAPES[_r][_s] = (_nu, _units, _no, _orders)


del agent
agent = _slot_agent
